package mx.redts.adendas.model;

// Generated 27/10/2013 03:26:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CClientes generated by hbm2java
 */
@Entity
@Table(name = "c_clientes", schema = "public")
public class CClientes implements java.io.Serializable {

	/**
	 * serialVersionUID long CClientes.java
	 */
	private static final long serialVersionUID = 2835623160481188025L;
	private int idCliente;
	private String idOb3;
	private String nombreCliente;

	public CClientes() {
	}

	public CClientes(int idCliente) {
		this.idCliente = idCliente;
	}

	public CClientes(int idCliente, String idOb3, String nombreCliente) {
		this.idCliente = idCliente;
		this.idOb3 = idOb3;
		this.nombreCliente = nombreCliente;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ClienteSeq")
	@SequenceGenerator(name = "ClienteSeq", sequenceName = "clientes_seq", allocationSize = 1)
	@Column(name = "id_cliente", unique = true, nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	@Column(name = "id_ob3", length = 32)
	public String getIdOb3() {
		return this.idOb3;
	}

	@Column(name = "nombre_cliente", length = 50)
	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public void setIdOb3(String idOb3) {
		this.idOb3 = idOb3;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	public String toString() {
		return this.nombreCliente;

	}

}
