package mx.redts.adendas.model;

// Generated 23-may-2014 0:38:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FeDetalle generated by hbm2java
 */
@Entity
@Table(name = "fe_detalle", schema = "public")
public class FeDetalle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idFeDetalle;
	private String ob3id;
	private String eanOUpc;
	private String dun14;
	private String descripcion;
	private String descripcion2;
	private String cantidad;
	private String unidadDeMedida;
	private String cantEmpaque;
	private String precio;
	private String porcenDesc1;
	private String tipoDescuento1;
	private String montoDeDescuento1;
	private String porcenDescuento2;
	private String tipoDescuento2;
	private String montoDeDescuento2;
	private String porcenDescuento3;
	private String tipoDescuento3;
	private String montoDeDescuento3;
	private String porcenDescuento4;
	private String tipoDescuento4;
	private String montoDeDescuento4;
	private String porcenDescuento5;
	private String tipoDescuento5;
	private String montoDeDescuento5;
	private String precioNeto;
	private String porcenIva;
	private String porcenIeps;
	private String cantEmbarcada;
	private String aduana;
	private String fecha;
	private String numeroPedimento;
	private String numeroInternoDePr1;
	private String numeroInternoDePr2;
	private String cantidadGratisDeM;
	private String tipoDeEmpaque;
	private String pagoDeEmpaque;
	private String costoTotalPrecio;
	private String importeConDescuen;
	private String montoDeIva;
	private String montoDeIeps;
	private String porcenIsr;
	private String montoIsr;
	private String porcenImpuestoDePetrol;
	private String montoImpuestoDePe;
	private String porcenExento;
	private String montoExento;
	private String porcenEstatal;
	private String montoEstatal;
	private String porcenCedular;
	private String montoCedular;
	private String porcenMunicipal;
	private String montoMunicipal;
	private String porcenHospedaje;
	private String montoHospedaje;
	private String porcenOtrosImpuestos;
	private String montoOtrosImpuesto;
	private String ordenDeCompra;
	private String numeroDeCuentaPre;
	private String cantidadRealDeKil;
	private String cantidadMinimaASurtir;
	private String etiqueta1;
	private String etiqueta2;
	private String etiqueta3;
	private String etiqueta4;
	private String etiqueta5;
	private String etiqueta6;
	private String etiqueta7;
	private String etiqueta8;
	private String etiqueta9;
	private String etiqueta10;
	private String etiqueta11;
	private String etiqueta12;
	private String etiqueta13;
	private String textoLibre1;
	private String textoLibre2;

	public FeDetalle() {
	}

	public FeDetalle(int idFeDetalle, String ob3id, String eanOUpc,
			String descripcion, String cantidad, String unidadDeMedida,
			String precio, String precioNeto, String porcenIva,
			String costoTotalPrecio, String montoDeIva) {
		this.idFeDetalle = idFeDetalle;
		this.ob3id = ob3id;
		this.eanOUpc = eanOUpc;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.unidadDeMedida = unidadDeMedida;
		this.precio = precio;
		this.precioNeto = precioNeto;
		this.porcenIva = porcenIva;
		this.costoTotalPrecio = costoTotalPrecio;
		this.montoDeIva = montoDeIva;
	}

	public FeDetalle(int idFeDetalle, String ob3id, String eanOUpc,
			String dun14, String descripcion, String descripcion2,
			String cantidad, String unidadDeMedida, String cantEmpaque,
			String precio, String porcenDesc1, String tipoDescuento1,
			String montoDeDescuento1, String porcenDescuento2,
			String tipoDescuento2, String montoDeDescuento2,
			String porcenDescuento3, String tipoDescuento3,
			String montoDeDescuento3, String porcenDescuento4,
			String tipoDescuento4, String montoDeDescuento4,
			String porcenDescuento5, String tipoDescuento5,
			String montoDeDescuento5, String precioNeto, String porcenIva,
			String porcenIeps, String cantEmbarcada, String aduana,
			String fecha, String numeroPedimento, String numeroInternoDePr1,
			String numeroInternoDePr2, String cantidadGratisDeM,
			String tipoDeEmpaque, String pagoDeEmpaque,
			String costoTotalPrecio, String importeConDescuen,
			String montoDeIva, String montoDeIeps, String porcenIsr,
			String montoIsr, String porcenImpuestoDePetrol,
			String montoImpuestoDePe, String porcenExento, String montoExento,
			String porcenEstatal, String montoEstatal, String porcenCedular,
			String montoCedular, String porcenMunicipal, String montoMunicipal,
			String porcenHospedaje, String montoHospedaje,
			String porcenOtrosImpuestos, String montoOtrosImpuesto,
			String ordenDeCompra, String numeroDeCuentaPre,
			String cantidadRealDeKil, String cantidadMinimaASurtir,
			String etiqueta1, String etiqueta2, String etiqueta3,
			String etiqueta4, String etiqueta5, String etiqueta6,
			String etiqueta7, String etiqueta8, String etiqueta9,
			String etiqueta10, String etiqueta11, String etiqueta12,
			String etiqueta13) {
		this.idFeDetalle = idFeDetalle;
		this.ob3id = ob3id;
		this.eanOUpc = eanOUpc;
		this.dun14 = dun14;
		this.descripcion = descripcion;
		this.descripcion2 = descripcion2;
		this.cantidad = cantidad;
		this.unidadDeMedida = unidadDeMedida;
		this.cantEmpaque = cantEmpaque;
		this.precio = precio;
		this.porcenDesc1 = porcenDesc1;
		this.tipoDescuento1 = tipoDescuento1;
		this.montoDeDescuento1 = montoDeDescuento1;
		this.porcenDescuento2 = porcenDescuento2;
		this.tipoDescuento2 = tipoDescuento2;
		this.montoDeDescuento2 = montoDeDescuento2;
		this.porcenDescuento3 = porcenDescuento3;
		this.tipoDescuento3 = tipoDescuento3;
		this.montoDeDescuento3 = montoDeDescuento3;
		this.porcenDescuento4 = porcenDescuento4;
		this.tipoDescuento4 = tipoDescuento4;
		this.montoDeDescuento4 = montoDeDescuento4;
		this.porcenDescuento5 = porcenDescuento5;
		this.tipoDescuento5 = tipoDescuento5;
		this.montoDeDescuento5 = montoDeDescuento5;
		this.precioNeto = precioNeto;
		this.porcenIva = porcenIva;
		this.porcenIeps = porcenIeps;
		this.cantEmbarcada = cantEmbarcada;
		this.aduana = aduana;
		this.fecha = fecha;
		this.numeroPedimento = numeroPedimento;
		this.numeroInternoDePr1 = numeroInternoDePr1;
		this.numeroInternoDePr2 = numeroInternoDePr2;
		this.cantidadGratisDeM = cantidadGratisDeM;
		this.tipoDeEmpaque = tipoDeEmpaque;
		this.pagoDeEmpaque = pagoDeEmpaque;
		this.costoTotalPrecio = costoTotalPrecio;
		this.importeConDescuen = importeConDescuen;
		this.montoDeIva = montoDeIva;
		this.montoDeIeps = montoDeIeps;
		this.porcenIsr = porcenIsr;
		this.montoIsr = montoIsr;
		this.porcenImpuestoDePetrol = porcenImpuestoDePetrol;
		this.montoImpuestoDePe = montoImpuestoDePe;
		this.porcenExento = porcenExento;
		this.montoExento = montoExento;
		this.porcenEstatal = porcenEstatal;
		this.montoEstatal = montoEstatal;
		this.porcenCedular = porcenCedular;
		this.montoCedular = montoCedular;
		this.porcenMunicipal = porcenMunicipal;
		this.montoMunicipal = montoMunicipal;
		this.porcenHospedaje = porcenHospedaje;
		this.montoHospedaje = montoHospedaje;
		this.porcenOtrosImpuestos = porcenOtrosImpuestos;
		this.montoOtrosImpuesto = montoOtrosImpuesto;
		this.ordenDeCompra = ordenDeCompra;
		this.numeroDeCuentaPre = numeroDeCuentaPre;
		this.cantidadRealDeKil = cantidadRealDeKil;
		this.cantidadMinimaASurtir = cantidadMinimaASurtir;
		this.etiqueta1 = etiqueta1;
		this.etiqueta2 = etiqueta2;
		this.etiqueta3 = etiqueta3;
		this.etiqueta4 = etiqueta4;
		this.etiqueta5 = etiqueta5;
		this.etiqueta6 = etiqueta6;
		this.etiqueta7 = etiqueta7;
		this.etiqueta8 = etiqueta8;
		this.etiqueta9 = etiqueta9;
		this.etiqueta10 = etiqueta10;
		this.etiqueta11 = etiqueta11;
		this.etiqueta12 = etiqueta12;
		this.etiqueta13 = etiqueta13;
	}

	@Column(name = "aduana", length = 10)
	public String getAduana() {
		return this.aduana;
	}

	@Column(name = "cant_embarcada", length = 5)
	public String getCantEmbarcada() {
		return this.cantEmbarcada;
	}

	@Column(name = "cant_empaque", length = 5)
	public String getCantEmpaque() {
		return this.cantEmpaque;
	}

	@Column(name = "cantidad", nullable = false, length = 10)
	public String getCantidad() {
		return this.cantidad;
	}

	@Column(name = "cantidad_gratis_de_m", length = 5)
	public String getCantidadGratisDeM() {
		return this.cantidadGratisDeM;
	}

	@Column(name = "cantidad_minima_a_surtir", length = 10)
	public String getCantidadMinimaASurtir() {
		return this.cantidadMinimaASurtir;
	}

	@Column(name = "cantidad_real_de_kil", length = 10)
	public String getCantidadRealDeKil() {
		return this.cantidadRealDeKil;
	}

	@Column(name = "costo_total_precio", nullable = false, length = 20)
	public String getCostoTotalPrecio() {
		return this.costoTotalPrecio;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	@Column(name = "descripcion2", length = 100)
	public String getDescripcion2() {
		return this.descripcion2;
	}

	@Column(name = "dun_14", length = 14)
	public String getDun14() {
		return this.dun14;
	}

	@Column(name = "ean_o_upc", nullable = false, length = 15)
	public String getEanOUpc() {
		return this.eanOUpc;
	}

	@Column(name = "etiqueta_1", length = 100)
	public String getEtiqueta1() {
		return this.etiqueta1;
	}

	@Column(name = "etiqueta_10", length = 100)
	public String getEtiqueta10() {
		return this.etiqueta10;
	}

	@Column(name = "etiqueta_11", length = 100)
	public String getEtiqueta11() {
		return this.etiqueta11;
	}

	@Column(name = "etiqueta_12", length = 100)
	public String getEtiqueta12() {
		return this.etiqueta12;
	}

	@Column(name = "etiqueta_13", length = 100)
	public String getEtiqueta13() {
		return this.etiqueta13;
	}

	@Column(name = "etiqueta_2", length = 100)
	public String getEtiqueta2() {
		return this.etiqueta2;
	}

	@Column(name = "etiqueta_3", length = 100)
	public String getEtiqueta3() {
		return this.etiqueta3;
	}

	@Column(name = "etiqueta_4", length = 100)
	public String getEtiqueta4() {
		return this.etiqueta4;
	}

	@Column(name = "etiqueta_5", length = 100)
	public String getEtiqueta5() {
		return this.etiqueta5;
	}

	@Column(name = "etiqueta_6", length = 100)
	public String getEtiqueta6() {
		return this.etiqueta6;
	}

	@Column(name = "etiqueta_7", length = 100)
	public String getEtiqueta7() {
		return this.etiqueta7;
	}

	@Column(name = "etiqueta_8", length = 100)
	public String getEtiqueta8() {
		return this.etiqueta8;
	}

	@Column(name = "etiqueta_9", length = 100)
	public String getEtiqueta9() {
		return this.etiqueta9;
	}

	@Column(name = "fecha", length = 10)
	public String getFecha() {
		return this.fecha;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DetalleSeq")
	@SequenceGenerator(name = "DetalleSeq", sequenceName = "fedetalle_seq", allocationSize = 1)
	@Column(name = "id_fe_detalle", unique = true, nullable = false)
	public int getIdFeDetalle() {
		return this.idFeDetalle;
	}

	@Column(name = "importe_con_descuen", length = 20)
	public String getImporteConDescuen() {
		return this.importeConDescuen;
	}

	@Column(name = "monto_cedular", length = 20)
	public String getMontoCedular() {
		return this.montoCedular;
	}

	@Column(name = "monto_de_descuento_1", length = 20)
	public String getMontoDeDescuento1() {
		return this.montoDeDescuento1;
	}

	@Column(name = "monto_de_descuento_2", length = 20)
	public String getMontoDeDescuento2() {
		return this.montoDeDescuento2;
	}

	@Column(name = "monto_de_descuento_3", length = 20)
	public String getMontoDeDescuento3() {
		return this.montoDeDescuento3;
	}

	@Column(name = "monto_de_descuento_4", length = 20)
	public String getMontoDeDescuento4() {
		return this.montoDeDescuento4;
	}

	@Column(name = "monto_de_descuento_5", length = 20)
	public String getMontoDeDescuento5() {
		return this.montoDeDescuento5;
	}

	@Column(name = "monto_de_ieps", length = 20)
	public String getMontoDeIeps() {
		return this.montoDeIeps;
	}

	@Column(name = "monto_de_iva", nullable = false, length = 20)
	public String getMontoDeIva() {
		return this.montoDeIva;
	}

	@Column(name = "monto_estatal", length = 20)
	public String getMontoEstatal() {
		return this.montoEstatal;
	}

	@Column(name = "monto_exento", length = 20)
	public String getMontoExento() {
		return this.montoExento;
	}

	@Column(name = "monto_hospedaje", length = 20)
	public String getMontoHospedaje() {
		return this.montoHospedaje;
	}

	@Column(name = "monto_impuesto_de_pe", length = 20)
	public String getMontoImpuestoDePe() {
		return this.montoImpuestoDePe;
	}

	@Column(name = "monto_isr", length = 20)
	public String getMontoIsr() {
		return this.montoIsr;
	}

	@Column(name = "monto_municipal", length = 20)
	public String getMontoMunicipal() {
		return this.montoMunicipal;
	}

	@Column(name = "monto_otros_impuesto", length = 20)
	public String getMontoOtrosImpuesto() {
		return this.montoOtrosImpuesto;
	}

	@Column(name = "numero_de_cuenta_pre", length = 20)
	public String getNumeroDeCuentaPre() {
		return this.numeroDeCuentaPre;
	}

	@Column(name = "numero_interno_de_pr1", length = 8)
	public String getNumeroInternoDePr1() {
		return this.numeroInternoDePr1;
	}

	@Column(name = "numero_interno_de_pr2", length = 8)
	public String getNumeroInternoDePr2() {
		return this.numeroInternoDePr2;
	}

	@Column(name = "numero_pedimento", length = 8)
	public String getNumeroPedimento() {
		return this.numeroPedimento;
	}

	@Column(name = "ob3id", nullable = false, length = 32)
	public String getOb3id() {
		return this.ob3id;
	}

	@Column(name = "orden_de_compra", length = 3)
	public String getOrdenDeCompra() {
		return this.ordenDeCompra;
	}

	@Column(name = "pago_de_empaque", length = 10)
	public String getPagoDeEmpaque() {
		return this.pagoDeEmpaque;
	}

	@Column(name = "porcen_cedular", length = 3)
	public String getPorcenCedular() {
		return this.porcenCedular;
	}

	@Column(name = "porcen_desc_1", length = 3)
	public String getPorcenDesc1() {
		return this.porcenDesc1;
	}

	@Column(name = "porcen_descuento_2", length = 3)
	public String getPorcenDescuento2() {
		return this.porcenDescuento2;
	}

	@Column(name = "porcen_descuento_3", length = 3)
	public String getPorcenDescuento3() {
		return this.porcenDescuento3;
	}

	@Column(name = "porcen_descuento_4", length = 3)
	public String getPorcenDescuento4() {
		return this.porcenDescuento4;
	}

	@Column(name = "porcen_descuento_5", length = 3)
	public String getPorcenDescuento5() {
		return this.porcenDescuento5;
	}

	@Column(name = "porcen_estatal", length = 3)
	public String getPorcenEstatal() {
		return this.porcenEstatal;
	}

	@Column(name = "porcen_exento", length = 3)
	public String getPorcenExento() {
		return this.porcenExento;
	}

	@Column(name = "porcen_hospedaje", length = 3)
	public String getPorcenHospedaje() {
		return this.porcenHospedaje;
	}

	@Column(name = "porcen_ieps", length = 3)
	public String getPorcenIeps() {
		return this.porcenIeps;
	}

	@Column(name = "porcen_impuesto_de_petrol", length = 3)
	public String getPorcenImpuestoDePetrol() {
		return this.porcenImpuestoDePetrol;
	}

	@Column(name = "porcen_isr", length = 3)
	public String getPorcenIsr() {
		return this.porcenIsr;
	}

	@Column(name = "porcen_iva", nullable = false, length = 3)
	public String getPorcenIva() {
		return this.porcenIva;
	}

	@Column(name = "porcen_municipal", length = 3)
	public String getPorcenMunicipal() {
		return this.porcenMunicipal;
	}

	@Column(name = "porcen_otros_impuestos", length = 3)
	public String getPorcenOtrosImpuestos() {
		return this.porcenOtrosImpuestos;
	}

	@Column(name = "precio", nullable = false, length = 20)
	public String getPrecio() {
		return this.precio;
	}

	@Column(name = "precio_neto", nullable = false, length = 20)
	public String getPrecioNeto() {
		return this.precioNeto;
	}

	@Column(name = "texto_libre_1", length = 250)
	public String getTextoLibre1() {
		return textoLibre1;
	}

	@Column(name = "texto_libre_2", length = 250)
	public String getTextoLibre2() {
		return textoLibre2;
	}

	@Column(name = "tipo_de_empaque", length = 5)
	public String getTipoDeEmpaque() {
		return this.tipoDeEmpaque;
	}

	@Column(name = "tipo_descuento_1", length = 5)
	public String getTipoDescuento1() {
		return this.tipoDescuento1;
	}

	@Column(name = "tipo_descuento_2", length = 5)
	public String getTipoDescuento2() {
		return this.tipoDescuento2;
	}

	@Column(name = "tipo_descuento_3", length = 5)
	public String getTipoDescuento3() {
		return this.tipoDescuento3;
	}

	@Column(name = "tipo_descuento_4", length = 5)
	public String getTipoDescuento4() {
		return this.tipoDescuento4;
	}

	@Column(name = "tipo_descuento_5", length = 5)
	public String getTipoDescuento5() {
		return this.tipoDescuento5;
	}

	@Column(name = "unidad_de_medida", nullable = false, length = 10)
	public String getUnidadDeMedida() {
		return this.unidadDeMedida;
	}

	public void setAduana(String aduana) {
		this.aduana = aduana;
	}

	public void setCantEmbarcada(String cantEmbarcada) {
		this.cantEmbarcada = cantEmbarcada;
	}

	public void setCantEmpaque(String cantEmpaque) {
		this.cantEmpaque = cantEmpaque;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	public void setCantidadGratisDeM(String cantidadGratisDeM) {
		this.cantidadGratisDeM = cantidadGratisDeM;
	}

	public void setCantidadMinimaASurtir(String cantidadMinimaASurtir) {
		this.cantidadMinimaASurtir = cantidadMinimaASurtir;
	}

	public void setCantidadRealDeKil(String cantidadRealDeKil) {
		this.cantidadRealDeKil = cantidadRealDeKil;
	}

	public void setCostoTotalPrecio(String costoTotalPrecio) {
		this.costoTotalPrecio = costoTotalPrecio;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public void setDescripcion2(String descripcion2) {
		this.descripcion2 = descripcion2;
	}

	public void setDun14(String dun14) {
		this.dun14 = dun14;
	}

	public void setEanOUpc(String eanOUpc) {
		this.eanOUpc = eanOUpc;
	}

	public void setEtiqueta1(String etiqueta1) {
		this.etiqueta1 = etiqueta1;
	}

	public void setEtiqueta10(String etiqueta10) {
		this.etiqueta10 = etiqueta10;
	}

	public void setEtiqueta11(String etiqueta11) {
		this.etiqueta11 = etiqueta11;
	}

	public void setEtiqueta12(String etiqueta12) {
		this.etiqueta12 = etiqueta12;
	}

	public void setEtiqueta13(String etiqueta13) {
		this.etiqueta13 = etiqueta13;
	}

	public void setEtiqueta2(String etiqueta2) {
		this.etiqueta2 = etiqueta2;
	}

	public void setEtiqueta3(String etiqueta3) {
		this.etiqueta3 = etiqueta3;
	}

	public void setEtiqueta4(String etiqueta4) {
		this.etiqueta4 = etiqueta4;
	}

	public void setEtiqueta5(String etiqueta5) {
		this.etiqueta5 = etiqueta5;
	}

	public void setEtiqueta6(String etiqueta6) {
		this.etiqueta6 = etiqueta6;
	}

	public void setEtiqueta7(String etiqueta7) {
		this.etiqueta7 = etiqueta7;
	}

	public void setEtiqueta8(String etiqueta8) {
		this.etiqueta8 = etiqueta8;
	}

	public void setEtiqueta9(String etiqueta9) {
		this.etiqueta9 = etiqueta9;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public void setIdFeDetalle(int idFeDetalle) {
		this.idFeDetalle = idFeDetalle;
	}

	public void setImporteConDescuen(String importeConDescuen) {
		this.importeConDescuen = importeConDescuen;
	}

	public void setMontoCedular(String montoCedular) {
		this.montoCedular = montoCedular;
	}

	public void setMontoDeDescuento1(String montoDeDescuento1) {
		this.montoDeDescuento1 = montoDeDescuento1;
	}

	public void setMontoDeDescuento2(String montoDeDescuento2) {
		this.montoDeDescuento2 = montoDeDescuento2;
	}

	public void setMontoDeDescuento3(String montoDeDescuento3) {
		this.montoDeDescuento3 = montoDeDescuento3;
	}

	public void setMontoDeDescuento4(String montoDeDescuento4) {
		this.montoDeDescuento4 = montoDeDescuento4;
	}

	public void setMontoDeDescuento5(String montoDeDescuento5) {
		this.montoDeDescuento5 = montoDeDescuento5;
	}

	public void setMontoDeIeps(String montoDeIeps) {
		this.montoDeIeps = montoDeIeps;
	}

	public void setMontoDeIva(String montoDeIva) {
		this.montoDeIva = montoDeIva;
	}

	public void setMontoEstatal(String montoEstatal) {
		this.montoEstatal = montoEstatal;
	}

	public void setMontoExento(String montoExento) {
		this.montoExento = montoExento;
	}

	public void setMontoHospedaje(String montoHospedaje) {
		this.montoHospedaje = montoHospedaje;
	}

	public void setMontoImpuestoDePe(String montoImpuestoDePe) {
		this.montoImpuestoDePe = montoImpuestoDePe;
	}

	public void setMontoIsr(String montoIsr) {
		this.montoIsr = montoIsr;
	}

	public void setMontoMunicipal(String montoMunicipal) {
		this.montoMunicipal = montoMunicipal;
	}

	public void setMontoOtrosImpuesto(String montoOtrosImpuesto) {
		this.montoOtrosImpuesto = montoOtrosImpuesto;
	}

	public void setNumeroDeCuentaPre(String numeroDeCuentaPre) {
		this.numeroDeCuentaPre = numeroDeCuentaPre;
	}

	public void setNumeroInternoDePr1(String numeroInternoDePr1) {
		this.numeroInternoDePr1 = numeroInternoDePr1;
	}

	public void setNumeroInternoDePr2(String numeroInternoDePr2) {
		this.numeroInternoDePr2 = numeroInternoDePr2;
	}

	public void setNumeroPedimento(String numeroPedimento) {
		this.numeroPedimento = numeroPedimento;
	}

	public void setOb3id(String ob3id) {
		this.ob3id = ob3id;
	}

	public void setOrdenDeCompra(String ordenDeCompra) {
		this.ordenDeCompra = ordenDeCompra;
	}

	public void setPagoDeEmpaque(String pagoDeEmpaque) {
		this.pagoDeEmpaque = pagoDeEmpaque;
	}

	public void setPorcenCedular(String porcenCedular) {
		this.porcenCedular = porcenCedular;
	}

	public void setPorcenDesc1(String porcenDesc1) {
		this.porcenDesc1 = porcenDesc1;
	}

	public void setPorcenDescuento2(String porcenDescuento2) {
		this.porcenDescuento2 = porcenDescuento2;
	}

	public void setPorcenDescuento3(String porcenDescuento3) {
		this.porcenDescuento3 = porcenDescuento3;
	}

	public void setPorcenDescuento4(String porcenDescuento4) {
		this.porcenDescuento4 = porcenDescuento4;
	}

	public void setPorcenDescuento5(String porcenDescuento5) {
		this.porcenDescuento5 = porcenDescuento5;
	}

	public void setPorcenEstatal(String porcenEstatal) {
		this.porcenEstatal = porcenEstatal;
	}

	public void setPorcenExento(String porcenExento) {
		this.porcenExento = porcenExento;
	}

	public void setPorcenHospedaje(String porcenHospedaje) {
		this.porcenHospedaje = porcenHospedaje;
	}

	public void setPorcenIeps(String porcenIeps) {
		this.porcenIeps = porcenIeps;
	}

	public void setPorcenImpuestoDePetrol(String porcenImpuestoDePetrol) {
		this.porcenImpuestoDePetrol = porcenImpuestoDePetrol;
	}

	public void setPorcenIsr(String porcenIsr) {
		this.porcenIsr = porcenIsr;
	}

	public void setPorcenIva(String porcenIva) {
		this.porcenIva = porcenIva;
	}

	public void setPorcenMunicipal(String porcenMunicipal) {
		this.porcenMunicipal = porcenMunicipal;
	}

	public void setPorcenOtrosImpuestos(String porcenOtrosImpuestos) {
		this.porcenOtrosImpuestos = porcenOtrosImpuestos;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	public void setPrecioNeto(String precioNeto) {
		this.precioNeto = precioNeto;
	}

	/**
	 * @param textoLibre1
	 *            the textoLibre1 to set
	 */
	public void setTextoLibre1(String textoLibre1) {
		this.textoLibre1 = textoLibre1;
	}

	/**
	 * @param textoLibre2
	 *            the textoLibre2 to set
	 */
	public void setTextoLibre2(String textoLibre2) {
		this.textoLibre2 = textoLibre2;
	}

	public void setTipoDeEmpaque(String tipoDeEmpaque) {
		this.tipoDeEmpaque = tipoDeEmpaque;
	}

	public void setTipoDescuento1(String tipoDescuento1) {
		this.tipoDescuento1 = tipoDescuento1;
	}

	public void setTipoDescuento2(String tipoDescuento2) {
		this.tipoDescuento2 = tipoDescuento2;
	}

	public void setTipoDescuento3(String tipoDescuento3) {
		this.tipoDescuento3 = tipoDescuento3;
	}

	public void setTipoDescuento4(String tipoDescuento4) {
		this.tipoDescuento4 = tipoDescuento4;
	}

	public void setTipoDescuento5(String tipoDescuento5) {
		this.tipoDescuento5 = tipoDescuento5;
	}

	public void setUnidadDeMedida(String unidadDeMedida) {
		this.unidadDeMedida = unidadDeMedida;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return (Messages.getString("FeDetalle.0") + eanOUpc + Messages.getString("FeDetalle.1") + dun14 + Messages.getString("FeDetalle.2") + descripcion + Messages.getString("FeDetalle.3") + descripcion2 + Messages.getString("FeDetalle.4") + cantidad + Messages.getString("FeDetalle.5") + unidadDeMedida + Messages.getString("FeDetalle.6") + cantEmpaque + Messages.getString("FeDetalle.7") + precio + Messages.getString("FeDetalle.8") + porcenDesc1 + Messages.getString("FeDetalle.9") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$ //$NON-NLS-9$ //$NON-NLS-10$
				+ tipoDescuento1
				+ Messages.getString("FeDetalle.10") + montoDeDescuento1 + Messages.getString("FeDetalle.11") + porcenDescuento2 + Messages.getString("FeDetalle.12") + tipoDescuento2 + Messages.getString("FeDetalle.13") + montoDeDescuento2 + Messages.getString("FeDetalle.14") + porcenDescuento3 + Messages.getString("FeDetalle.15") + tipoDescuento3 + Messages.getString("FeDetalle.16") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$
				+ montoDeDescuento3
				+ Messages.getString("FeDetalle.17") + porcenDescuento4 + Messages.getString("FeDetalle.18") + tipoDescuento4 + Messages.getString("FeDetalle.19") + montoDeDescuento4 + Messages.getString("FeDetalle.20") + porcenDescuento5 + Messages.getString("FeDetalle.21") + tipoDescuento5 + Messages.getString("FeDetalle.22") + montoDeDescuento5 + Messages.getString("FeDetalle.23") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$
				+ precioNeto
				+ Messages.getString("FeDetalle.24") + porcenIva + Messages.getString("FeDetalle.25") + porcenIeps + Messages.getString("FeDetalle.26") + cantEmbarcada + Messages.getString("FeDetalle.27") + aduana + Messages.getString("FeDetalle.28") + fecha + Messages.getString("FeDetalle.29") + numeroPedimento + Messages.getString("FeDetalle.30") + numeroInternoDePr1 + Messages.getString("FeDetalle.31") + numeroInternoDePr2 //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$
				+ Messages.getString("FeDetalle.32") + cantidadGratisDeM + Messages.getString("FeDetalle.33") + tipoDeEmpaque + Messages.getString("FeDetalle.34") + pagoDeEmpaque + Messages.getString("FeDetalle.35") + costoTotalPrecio + Messages.getString("FeDetalle.36") + importeConDescuen + Messages.getString("FeDetalle.37") + montoDeIva + Messages.getString("FeDetalle.38") + montoDeIeps + Messages.getString("FeDetalle.39") + porcenIsr + Messages.getString("FeDetalle.40") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$ //$NON-NLS-9$
				+ montoIsr
				+ Messages.getString("FeDetalle.41") + porcenImpuestoDePetrol + Messages.getString("FeDetalle.42") + montoImpuestoDePe + Messages.getString("FeDetalle.43") + porcenExento + Messages.getString("FeDetalle.44") + montoExento + Messages.getString("FeDetalle.45") + porcenEstatal + Messages.getString("FeDetalle.46") + montoEstatal + Messages.getString("FeDetalle.47") + porcenCedular + Messages.getString("FeDetalle.48") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$
				+ montoCedular
				+ Messages.getString("FeDetalle.49") + porcenMunicipal + Messages.getString("FeDetalle.50") + montoMunicipal + Messages.getString("FeDetalle.51") + porcenHospedaje + Messages.getString("FeDetalle.52") + montoHospedaje + Messages.getString("FeDetalle.53") + porcenOtrosImpuestos + Messages.getString("FeDetalle.54") + montoOtrosImpuesto + Messages.getString("FeDetalle.55") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$
				+ ordenDeCompra
				+ Messages.getString("FeDetalle.56") + numeroDeCuentaPre + Messages.getString("FeDetalle.57") + cantidadRealDeKil + Messages.getString("FeDetalle.58") + cantidadMinimaASurtir + Messages.getString("FeDetalle.59") + etiqueta1 + Messages.getString("FeDetalle.60") + etiqueta2 + Messages.getString("FeDetalle.61") + etiqueta3 + Messages.getString("FeDetalle.62") + etiqueta4 + Messages.getString("FeDetalle.63") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$
				+ etiqueta5
				+ Messages.getString("FeDetalle.64") + etiqueta6 + Messages.getString("FeDetalle.65") + etiqueta7 + Messages.getString("FeDetalle.66") + etiqueta8 + Messages.getString("FeDetalle.67") + etiqueta9 + Messages.getString("FeDetalle.68") + etiqueta10 + Messages.getString("FeDetalle.69") + etiqueta11 + Messages.getString("FeDetalle.70") + etiqueta12 + Messages.getString("FeDetalle.71") + etiqueta13 + Messages.getString("FeDetalle.72") + textoLibre1 //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$ //$NON-NLS-9$
				+ Messages.getString("FeDetalle.73") + textoLibre2 + Messages.getString("FeDetalle.74")).replaceAll(Messages.getString("FeDetalle.75"), Messages.getString("FeDetalle.76")); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$
	}

}
