package mx.redts.adendas.model;

// Generated 23-may-2014 0:38:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeDirFiscal generated by hbm2java
 */
@Entity
@Table(name = "fe_dir_fiscal", schema = "public")
public class FeDirFiscal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String ob3id;
	private String nombreEmisorVende;
	private String rfc;
	private String gln;
	private String calle;
	private String noExterior;
	private String noInterior;
	private String colonia;
	private String localidad;
	private String referencia;
	private String municipio;
	private String estado;
	private String pais;
	private String cp;
	private String regimenFiscalDelEmisor;
	private String telefono;
	private String etiqueta1;
	private String etiqueta2;
	private String etiqueta3;
	private String etiqueta4;
	private String etiqueta5;
	private String etiqueta6;
	private String etiqueta7;
	private String etiqueta8;
	private String noDeCuenta;
	private String etiqueta10;
	private String etiqueta11;

	public FeDirFiscal() {
	}

	public FeDirFiscal(String ob3id, String nombreEmisorVende, String rfc,
			String calle, String municipio, String estado, String pais,
			String cp, String regimenFiscalDelEmisor) {
		this.ob3id = ob3id;
		this.nombreEmisorVende = nombreEmisorVende;
		this.rfc = rfc;
		this.calle = calle;
		this.municipio = municipio;
		this.estado = estado;
		this.pais = pais;
		this.cp = cp;
		this.regimenFiscalDelEmisor = regimenFiscalDelEmisor;
	}

	public FeDirFiscal(String ob3id, String nombreEmisorVende, String rfc,
			String gln, String calle, String noExterior, String noInterior,
			String colonia, String localidad, String referencia,
			String municipio, String estado, String pais, String cp,
			String regimenFiscalDelEmisor, String telefono, String etiqueta1,
			String etiqueta2, String etiqueta3, String etiqueta4,
			String etiqueta5, String etiqueta6, String etiqueta7,
			String etiqueta8, String noDeCuenta, String etiqueta10) {
		this.ob3id = ob3id;
		this.nombreEmisorVende = nombreEmisorVende;
		this.rfc = rfc;
		this.gln = gln;
		this.calle = calle;
		this.noExterior = noExterior;
		this.noInterior = noInterior;
		this.colonia = colonia;
		this.localidad = localidad;
		this.referencia = referencia;
		this.municipio = municipio;
		this.estado = estado;
		this.pais = pais;
		this.cp = cp;
		this.regimenFiscalDelEmisor = regimenFiscalDelEmisor;
		this.telefono = telefono;
		this.etiqueta1 = etiqueta1;
		this.etiqueta2 = etiqueta2;
		this.etiqueta3 = etiqueta3;
		this.etiqueta4 = etiqueta4;
		this.etiqueta5 = etiqueta5;
		this.etiqueta6 = etiqueta6;
		this.etiqueta7 = etiqueta7;
		this.etiqueta8 = etiqueta8;
		this.noDeCuenta = noDeCuenta;
		this.etiqueta10 = etiqueta10;
	}

	@Column(name = "calle", nullable = false, length = 50)
	public String getCalle() {
		return this.calle;
	}

	@Column(name = "colonia", length = 30)
	public String getColonia() {
		return this.colonia;
	}

	@Column(name = "cp", nullable = false, length = 8)
	public String getCp() {
		return this.cp;
	}

	@Column(name = "estado", nullable = false, length = 30)
	public String getEstado() {
		return this.estado;
	}

	@Column(name = "etiqueta_1", length = 100)
	public String getEtiqueta1() {
		return this.etiqueta1;
	}

	@Column(name = "etiqueta_10", length = 100)
	public String getEtiqueta10() {
		return this.etiqueta10;
	}

	@Column(name = "etiqueta_11", length = 100)
	public String getEtiqueta11() {
		return this.etiqueta11;
	}

	@Column(name = "etiqueta_2", length = 100)
	public String getEtiqueta2() {
		return this.etiqueta2;
	}

	@Column(name = "etiqueta_3", length = 100)
	public String getEtiqueta3() {
		return this.etiqueta3;
	}

	@Column(name = "etiqueta_4", length = 100)
	public String getEtiqueta4() {
		return this.etiqueta4;
	}

	@Column(name = "etiqueta_5", length = 100)
	public String getEtiqueta5() {
		return this.etiqueta5;
	}

	@Column(name = "etiqueta_6", length = 100)
	public String getEtiqueta6() {
		return this.etiqueta6;
	}

	@Column(name = "etiqueta_7", length = 100)
	public String getEtiqueta7() {
		return this.etiqueta7;
	}

	@Column(name = "etiqueta_8", length = 100)
	public String getEtiqueta8() {
		return this.etiqueta8;
	}

	@Column(name = "gln", length = 20)
	public String getGln() {
		return this.gln;
	}

	@Column(name = "localidad", length = 30)
	public String getLocalidad() {
		return this.localidad;
	}

	@Column(name = "municipio", nullable = false, length = 30)
	public String getMunicipio() {
		return this.municipio;
	}

	@Column(name = "no_de_cuenta", length = 100)
	public String getNoDeCuenta() {
		return this.noDeCuenta;
	}

	@Column(name = "no_exterior", length = 5)
	public String getNoExterior() {
		return this.noExterior;
	}

	@Column(name = "no_interior", length = 5)
	public String getNoInterior() {
		return this.noInterior;
	}

	@Column(name = "nombre_emisor_vende", nullable = false, length = 100)
	public String getNombreEmisorVende() {
		return this.nombreEmisorVende;
	}

	@Id
	@Column(name = "ob3id", unique = true, nullable = false, length = 32)
	public String getOb3id() {
		return this.ob3id;
	}

	@Column(name = "pais", nullable = false, length = 30)
	public String getPais() {
		return this.pais;
	}

	@Column(name = "referencia", length = 100)
	public String getReferencia() {
		return this.referencia;
	}

	@Column(name = "regimen_fiscal_del_emisor", nullable = false, length = 16)
	public String getRegimenFiscalDelEmisor() {
		return this.regimenFiscalDelEmisor;
	}

	@Column(name = "rfc", nullable = false, length = 15)
	public String getRfc() {
		return this.rfc;
	}

	@Column(name = "telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setEtiqueta1(String etiqueta1) {
		this.etiqueta1 = etiqueta1;
	}

	public void setEtiqueta10(String etiqueta10) {
		this.etiqueta10 = etiqueta10;
	}

	public void setEtiqueta11(String etiqueta11) {
		this.etiqueta11 = etiqueta11;
	}

	public void setEtiqueta2(String etiqueta2) {
		this.etiqueta2 = etiqueta2;
	}

	public void setEtiqueta3(String etiqueta3) {
		this.etiqueta3 = etiqueta3;
	}

	public void setEtiqueta4(String etiqueta4) {
		this.etiqueta4 = etiqueta4;
	}

	public void setEtiqueta5(String etiqueta5) {
		this.etiqueta5 = etiqueta5;
	}

	public void setEtiqueta6(String etiqueta6) {
		this.etiqueta6 = etiqueta6;
	}

	public void setEtiqueta7(String etiqueta7) {
		this.etiqueta7 = etiqueta7;
	}

	public void setEtiqueta8(String etiqueta8) {
		this.etiqueta8 = etiqueta8;
	}

	public void setGln(String gln) {
		this.gln = gln;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public void setNoDeCuenta(String noDeCuenta) {
		this.noDeCuenta = noDeCuenta;
	}

	public void setNoExterior(String noExterior) {
		this.noExterior = noExterior;
	}

	public void setNoInterior(String noInterior) {
		this.noInterior = noInterior;
	}

	public void setNombreEmisorVende(String nombreEmisorVende) {
		this.nombreEmisorVende = nombreEmisorVende;
	}

	public void setOb3id(String ob3id) {
		this.ob3id = ob3id;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public void setRegimenFiscalDelEmisor(String regimenFiscalDelEmisor) {
		this.regimenFiscalDelEmisor = regimenFiscalDelEmisor;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return (Messages.getString("FeDirFiscal.0") + nombreEmisorVende + Messages.getString("FeDirFiscal.1") + rfc + Messages.getString("FeDirFiscal.2") + gln + Messages.getString("FeDirFiscal.3") + calle + Messages.getString("FeDirFiscal.4") + noExterior + Messages.getString("FeDirFiscal.5") + noInterior + Messages.getString("FeDirFiscal.6") + colonia + Messages.getString("FeDirFiscal.7") + localidad + Messages.getString("FeDirFiscal.8") + referencia + Messages.getString("FeDirFiscal.9") + municipio + Messages.getString("FeDirFiscal.10") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$ //$NON-NLS-9$ //$NON-NLS-10$ //$NON-NLS-11$
				+ estado
				+ Messages.getString("FeDirFiscal.11") + pais + Messages.getString("FeDirFiscal.12") + cp + Messages.getString("FeDirFiscal.13") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
				// IMSS
				+ Messages.getString("FeDirFiscal.14") + telefono + Messages.getString("FeDirFiscal.15") + etiqueta1 + Messages.getString("FeDirFiscal.16") + etiqueta2 + Messages.getString("FeDirFiscal.17") + etiqueta3 + Messages.getString("FeDirFiscal.18") + etiqueta4 + Messages.getString("FeDirFiscal.19") + etiqueta5 + Messages.getString("FeDirFiscal.20") + etiqueta6 + Messages.getString("FeDirFiscal.21") + etiqueta7 + Messages.getString("FeDirFiscal.22") + noDeCuenta + Messages.getString("FeDirFiscal.23") + etiqueta10 + Messages.getString("FeDirFiscal.24")) //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$ //$NON-NLS-9$ //$NON-NLS-10$ //$NON-NLS-11$
				.replaceAll(
						Messages.getString("FeDirFiscal.25"), Messages.getString("FeDirFiscal.26")); //$NON-NLS-1$ //$NON-NLS-2$
	}

}
