package mx.redts.adendas.model;

// Generated 23-may-2014 0:38:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import mx.redts.adendas.util.NumberToLetterConverter;

/**
 * FeEncabezado generated by hbm2java
 */
@Entity
@Table(name = "fe_encabezado", schema = "public")
public class FeEncabezado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String ob3id;
	private String cliid;
	private String serie;
	private String folio;
	private String noAprobacion;
	private String fechaCfd;
	private String referenciaDeDocume;
	private String fechaReferenciaDe;
	private String formaDePago;
	private String diasDePago;
	private String funcion;
	private String tipoDeDocumento;
	private String porcenDescuento1;
	private String tipoDescuento1;
	private String montoDeDescuento1;
	private String porcenDescuento2;
	private String tipoDescuento2;
	private String montoDeDescuento2;
	private String porcenDescuento3;
	private String tipoDescuento3;
	private String montoDeDescuento3;
	private String anioAprobacion;
	private String numeroInterno;
	private String areaInterna;
	private String representanteLegal;
	private String noProveedor;
	private String tasaGlobalDeIva;
	private String numeroDeTienda;
	private String frm;
	private String fechaDeFrm;
	private String lugarDeExpedicion;
	private String metodoDePago;
	private String moneda;
	private String tipoDeCambio;
	private String fechaDeEntregaAct;
	private String contactoDeCompras;
	private String departamentoDelCon;
	private String observaciones1come;
	private String observaciones2come;
	private String observaciones3come;
	private String observaciones4come;
	private String observaciones5come;
	private String noAvisoAnticipado;
	private String fechaAvisoAnticipa;
	private String importeConLetra;
	private String tipoImpresion;
	private String tipoDeEnvio;
	private String codigoIeps;
	private String etiqueta1;
	private String etiqueta2;
	private String etiqueta3;
	private String etiqueta4;
	private String etiqueta5;
	private String etiqueta6;

	public FeEncabezado() {
	}

	public FeEncabezado(String ob3id, String fechaCfd, String formaDePago,
			String funcion, String tipoDeDocumento, String tasaGlobalDeIva,
			String lugarDeExpedicion, String metodoDePago,
			String importeConLetra) {
		this.ob3id = ob3id;
		this.fechaCfd = fechaCfd;
		this.formaDePago = formaDePago;
		this.funcion = funcion;
		this.tipoDeDocumento = tipoDeDocumento;
		this.tasaGlobalDeIva = tasaGlobalDeIva;
		this.lugarDeExpedicion = lugarDeExpedicion;
		this.metodoDePago = metodoDePago;
		this.importeConLetra = importeConLetra;
	}

	public FeEncabezado(String ob3id, String serie, String folio,
			String noAprobacion, String fechaCfd, String referenciaDeDocume,
			String fechaReferenciaDe, String formaDePago, String diasDePago,
			String funcion, String tipoDeDocumento, String porcenDescuento1,
			String tipoDescuento1, String montoDeDescuento1,
			String porcenDescuento2, String tipoDescuento2,
			String montoDeDescuento2, String porcenDescuento3,
			String tipoDescuento3, String montoDeDescuento3,
			String anioAprobacion, String numeroInterno, String areaInterna,
			String representanteLegal, String noProveedor,
			String tasaGlobalDeIva, String numeroDeTienda, String frm,
			String fechaDeFrm, String lugarDeExpedicion, String metodoDePago,
			String moneda, String tipoDeCambio, String fechaDeEntregaAct,
			String contactoDeCompras, String departamentoDelCon,
			String observaciones1come, String observaciones2come,
			String observaciones3come, String observaciones4come,
			String observaciones5come, String noAvisoAnticipado,
			String fechaAvisoAnticipa, String importeConLetra,
			String tipoImpresion, String tipoDeEnvio, String codigoIeps,
			String etiqueta1, String etiqueta2, String etiqueta3,
			String etiqueta4, String etiqueta5, String etiqueta6) {
		this.ob3id = ob3id;
		this.serie = serie;
		this.folio = folio;
		this.noAprobacion = noAprobacion;
		this.fechaCfd = fechaCfd;
		this.referenciaDeDocume = referenciaDeDocume;
		this.fechaReferenciaDe = fechaReferenciaDe;
		this.formaDePago = formaDePago;
		this.diasDePago = diasDePago;
		this.funcion = funcion;
		this.tipoDeDocumento = tipoDeDocumento;
		this.porcenDescuento1 = porcenDescuento1;
		this.tipoDescuento1 = tipoDescuento1;
		this.montoDeDescuento1 = montoDeDescuento1;
		this.porcenDescuento2 = porcenDescuento2;
		this.tipoDescuento2 = tipoDescuento2;
		this.montoDeDescuento2 = montoDeDescuento2;
		this.porcenDescuento3 = porcenDescuento3;
		this.tipoDescuento3 = tipoDescuento3;
		this.montoDeDescuento3 = montoDeDescuento3;
		this.anioAprobacion = anioAprobacion;
		this.numeroInterno = numeroInterno;
		this.areaInterna = areaInterna;
		this.representanteLegal = representanteLegal;
		this.noProveedor = noProveedor;
		this.tasaGlobalDeIva = tasaGlobalDeIva;
		this.numeroDeTienda = numeroDeTienda;
		this.frm = frm;
		this.fechaDeFrm = fechaDeFrm;
		this.lugarDeExpedicion = lugarDeExpedicion;
		this.metodoDePago = metodoDePago;
		this.moneda = moneda;
		this.tipoDeCambio = tipoDeCambio;
		this.fechaDeEntregaAct = fechaDeEntregaAct;
		this.contactoDeCompras = contactoDeCompras;
		this.departamentoDelCon = departamentoDelCon;
		this.observaciones1come = observaciones1come;
		this.observaciones2come = observaciones2come;
		this.observaciones3come = observaciones3come;
		this.observaciones4come = observaciones4come;
		this.observaciones5come = observaciones5come;
		this.noAvisoAnticipado = noAvisoAnticipado;
		this.fechaAvisoAnticipa = fechaAvisoAnticipa;
		this.importeConLetra = importeConLetra;
		this.tipoImpresion = tipoImpresion;
		this.tipoDeEnvio = tipoDeEnvio;
		this.codigoIeps = codigoIeps;
		this.etiqueta1 = etiqueta1;
		this.etiqueta2 = etiqueta2;
		this.etiqueta3 = etiqueta3;
		this.etiqueta4 = etiqueta4;
		this.etiqueta5 = etiqueta5;
		this.etiqueta6 = etiqueta6;
	}

	@Column(name = "anio_aprobacion", length = 5)
	public String getAnioAprobacion() {
		return this.anioAprobacion;
	}

	@Column(name = "area_interna", length = 30)
	public String getAreaInterna() {
		return this.areaInterna;
	}

	public String getCliid() {

		System.out.println(Messages.getString("FeEncabezado.0") + cliid); //$NON-NLS-1$
		try {
			if (Messages.getString("FeEncabezado.1").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.2"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.3").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.4"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.5").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.6"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.7").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.8"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.9").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.10"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.11").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.12"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.13").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.14"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.15").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.16"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.17").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.18"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.19").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.20"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.21").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.22"); //$NON-NLS-1$
			} else if (Messages
					.getString("FeEncabezado.23").equals(cliid.trim())) { //$NON-NLS-1$
				return Messages.getString("FeEncabezado.24"); //$NON-NLS-1$
//if de Grupo Control
			}
				else if(Messages.getString("FeEncabezado.241").equals(cliid.trim())) {
				return Messages.getString("FeEncabezado.242");
//Termina else if de Grupo Control			
			} else {
				return Messages.getString("FeEncabezado.25"); //$NON-NLS-1$
			}
		} catch (NullPointerException e) {
			return Messages.getString("FeEncabezado.26"); //$NON-NLS-1$
		}
	}

	@Column(name = "codigo_ieps", length = 20)
	public String getCodigoIeps() {
		return this.codigoIeps;
	}

	@Column(name = "contacto_de_compras", length = 100)
	public String getContactoDeCompras() {
		return this.contactoDeCompras;
	}

	@Column(name = "departamento_del_con", length = 100)
	public String getDepartamentoDelCon() {
		return this.departamentoDelCon;
	}

	@Column(name = "dias_de_pago", length = 50)
	public String getDiasDePago() {
		return this.diasDePago;
	}

	@Column(name = "etiqueta_1", length = 100)
	public String getEtiqueta1() {
		return this.etiqueta1;
	}

	@Column(name = "etiqueta_2", length = 100)
	public String getEtiqueta2() {
		return this.etiqueta2;
	}

	@Column(name = "etiqueta_3", length = 100)
	public String getEtiqueta3() {
		return this.etiqueta3;
	}

	@Column(name = "etiqueta_4", length = 100)
	public String getEtiqueta4() {
		return this.etiqueta4;
	}

	@Column(name = "etiqueta_5", length = 100)
	public String getEtiqueta5() {
		return this.etiqueta5;
	}

	@Column(name = "etiqueta_6", length = 100)
	public String getEtiqueta6() {
		return this.etiqueta6;
	}

	@Column(name = "fecha_aviso_anticipa", length = 10)
	public String getFechaAvisoAnticipa() {
		return this.fechaAvisoAnticipa;
	}

	@Column(name = "fecha_cfd", nullable = false, length = 10)
	public String getFechaCfd() {
		return this.fechaCfd;
	}

	@Column(name = "fecha_de_entrega_act", length = 10)
	public String getFechaDeEntregaAct() {
		return this.fechaDeEntregaAct;
	}

	@Column(name = "fecha_de_frm", length = 10)
	public String getFechaDeFrm() {
		return this.fechaDeFrm;
	}

	@Column(name = "fecha_referencia_de", length = 10)
	public String getFechaReferenciaDe() {
		return this.fechaReferenciaDe;
	}

	@Column(name = "folio", length = 30)
	public String getFolio() {
		return this.folio;
	}

	@Column(name = "forma_de_pago", nullable = false, length = 50)
	public String getFormaDePago() {
		return this.formaDePago;
	}

	@Column(name = "frm", length = 30)
	public String getFrm() {
		return this.frm;
	}

	@Column(name = "funcion", nullable = false, length = 50)
	public String getFuncion() {
		return this.funcion;
	}

	@Column(name = "importe_con_letra", nullable = false, length = 20)
	public String getImporteConLetra() {
		return this.importeConLetra;
	}

	@Column(name = "lugar_de_expedicion", nullable = false, length = 50)
	public String getLugarDeExpedicion() {
		return this.lugarDeExpedicion;
	}

	@Column(name = "metodo_de_pago", nullable = false, length = 50)
	public String getMetodoDePago() {
		return this.metodoDePago;
	}

	@Column(name = "moneda", length = 5)
	public String getMoneda() {
		return this.moneda;
	}

	@Column(name = "monto_de_descuento1", length = 20)
	public String getMontoDeDescuento1() {
		return this.montoDeDescuento1;
	}

	@Column(name = "monto_de_descuento_2", length = 20)
	public String getMontoDeDescuento2() {
		return this.montoDeDescuento2;
	}

	@Column(name = "monto_de_descuento_3", length = 20)
	public String getMontoDeDescuento3() {
		return this.montoDeDescuento3;
	}

	@Column(name = "no_aprobacion", length = 30)
	public String getNoAprobacion() {
		return this.noAprobacion;
	}

	@Column(name = "no_aviso_anticipado", length = 20)
	public String getNoAvisoAnticipado() {
		return this.noAvisoAnticipado;
	}

	@Column(name = "no_proveedor", length = 10)
	public String getNoProveedor() {
		return this.noProveedor;
	}

	@Column(name = "numero_de_tienda", length = 10)
	public String getNumeroDeTienda() {
		return this.numeroDeTienda;
	}

	@Column(name = "numero_interno", length = 10)
	public String getNumeroInterno() {
		return this.numeroInterno;
	}

	@Id
	@Column(name = "ob3id", unique = true, nullable = false, length = 32)
	public String getOb3id() {
		return this.ob3id;
	}

	@Column(name = "observaciones_1come", length = 250)
	public String getObservaciones1come() {
		return this.observaciones1come;
	}

	@Column(name = "observaciones_2come", length = 250)
	public String getObservaciones2come() {
		return this.observaciones2come;
	}

	@Column(name = "observaciones_3come", length = 250)
	public String getObservaciones3come() {
		return this.observaciones3come;
	}

	@Column(name = "observaciones_4come", length = 250)
	public String getObservaciones4come() {
		return this.observaciones4come;
	}

	@Column(name = "observaciones_5come", length = 250)
	public String getObservaciones5come() {
		return this.observaciones5come;
	}

	@Column(name = "porcen_descuento_1", length = 20)
	public String getPorcenDescuento1() {
		return this.porcenDescuento1;
	}

	@Column(name = "porcen_descuento_2", length = 20)
	public String getPorcenDescuento2() {
		return this.porcenDescuento2;
	}

	@Column(name = "porcen_descuento_3", length = 20)
	public String getPorcenDescuento3() {
		return this.porcenDescuento3;
	}

	@Column(name = "referencia_de_docume", length = 30)
	public String getReferenciaDeDocume() {
		return this.referenciaDeDocume;
	}

	@Column(name = "representante_legal", length = 100)
	public String getRepresentanteLegal() {
		return this.representanteLegal;
	}

	@Column(name = "serie", length = 30)
	public String getSerie() {
		return this.serie;
	}

	@Column(name = "tasa_global_de_iva", nullable = false, length = 10)
	public String getTasaGlobalDeIva() {
		return this.tasaGlobalDeIva;
	}

	@Column(name = "tipo_de_cambio", length = 20)
	public String getTipoDeCambio() {
		return this.tipoDeCambio;
	}

	@Column(name = "tipo_de_documento", nullable = false, length = 50)
	public String getTipoDeDocumento() {
		return this.tipoDeDocumento;
	}

	@Column(name = "tipo_de_envio", length = 10)
	public String getTipoDeEnvio() {
		return this.tipoDeEnvio;
	}

	@Column(name = "tipo_descuento_1", length = 30)
	public String getTipoDescuento1() {
		return this.tipoDescuento1;
	}

	@Column(name = "tipo_descuento_2", length = 30)
	public String getTipoDescuento2() {
		return this.tipoDescuento2;
	}

	@Column(name = "tipo_descuento_3", length = 30)
	public String getTipoDescuento3() {
		return this.tipoDescuento3;
	}

	@Column(name = "tipo_impresion", length = 10)
	public String getTipoImpresion() {
		return this.tipoImpresion;
	}

	public void setAnioAprobacion(String anioAprobacion) {
		this.anioAprobacion = anioAprobacion;
	}

	public void setAreaInterna(String areaInterna) {
		this.areaInterna = areaInterna;
	}

	public void setCliid(String cliid) {
		this.cliid = cliid;
	}

	public void setCodigoIeps(String codigoIeps) {
		this.codigoIeps = codigoIeps;
	}

	public void setContactoDeCompras(String contactoDeCompras) {
		this.contactoDeCompras = contactoDeCompras;
	}

	public void setDepartamentoDelCon(String departamentoDelCon) {
		this.departamentoDelCon = departamentoDelCon;
	}

	public void setDiasDePago(String diasDePago) {
		this.diasDePago = diasDePago;
	}

	public void setEtiqueta1(String etiqueta1) {
		this.etiqueta1 = etiqueta1;
	}

	public void setEtiqueta2(String etiqueta2) {
		this.etiqueta2 = etiqueta2;
	}

	public void setEtiqueta3(String etiqueta3) {
		this.etiqueta3 = etiqueta3;
	}

	public void setEtiqueta4(String etiqueta4) {
		this.etiqueta4 = etiqueta4;
	}

	public void setEtiqueta5(String etiqueta5) {
		this.etiqueta5 = etiqueta5;
	}

	public void setEtiqueta6(String etiqueta6) {
		this.etiqueta6 = etiqueta6;
	}

	public void setFechaAvisoAnticipa(String fechaAvisoAnticipa) {
		this.fechaAvisoAnticipa = fechaAvisoAnticipa;
	}

	public void setFechaCfd(String fechaCfd) {
		this.fechaCfd = fechaCfd;
	}

	public void setFechaDeEntregaAct(String fechaDeEntregaAct) {
		this.fechaDeEntregaAct = fechaDeEntregaAct;
	}

	public void setFechaDeFrm(String fechaDeFrm) {
		this.fechaDeFrm = fechaDeFrm;
	}

	public void setFechaReferenciaDe(String fechaReferenciaDe) {
		this.fechaReferenciaDe = fechaReferenciaDe;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public void setFormaDePago(String formaDePago) {
		this.formaDePago = formaDePago;
	}

	public void setFrm(String frm) {
		this.frm = frm;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

	public void setImporteConLetra(String importeConLetra) {
		this.importeConLetra = importeConLetra;
	}

	public void setLugarDeExpedicion(String lugarDeExpedicion) {
		this.lugarDeExpedicion = lugarDeExpedicion;
	}

	public void setMetodoDePago(String metodoDePago) {
		this.metodoDePago = metodoDePago;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public void setMontoDeDescuento1(String montoDeDescuento1) {
		this.montoDeDescuento1 = montoDeDescuento1;
	}

	public void setMontoDeDescuento2(String montoDeDescuento2) {
		this.montoDeDescuento2 = montoDeDescuento2;
	}

	public void setMontoDeDescuento3(String montoDeDescuento3) {
		this.montoDeDescuento3 = montoDeDescuento3;
	}

	public void setNoAprobacion(String noAprobacion) {
		this.noAprobacion = noAprobacion;
	}

	public void setNoAvisoAnticipado(String noAvisoAnticipado) {
		this.noAvisoAnticipado = noAvisoAnticipado;
	}

	public void setNoProveedor(String noProveedor) {
		this.noProveedor = noProveedor;
	}

	public void setNumeroDeTienda(String numeroDeTienda) {
		this.numeroDeTienda = numeroDeTienda;
	}

	public void setNumeroInterno(String numeroInterno) {
		this.numeroInterno = numeroInterno;
	}

	public void setOb3id(String ob3id) {
		this.ob3id = ob3id;
	}

	public void setObservaciones1come(String observaciones1come) {
		this.observaciones1come = observaciones1come;
	}

	public void setObservaciones2come(String observaciones2come) {
		this.observaciones2come = observaciones2come;
	}

	public void setObservaciones3come(String observaciones3come) {
		this.observaciones3come = observaciones3come;
	}

	public void setObservaciones4come(String observaciones4come) {
		this.observaciones4come = observaciones4come;
	}

	public void setObservaciones5come(String observaciones5come) {
		this.observaciones5come = observaciones5come;
	}

	public void setPorcenDescuento1(String porcenDescuento1) {
		this.porcenDescuento1 = porcenDescuento1;
	}

	public void setPorcenDescuento2(String porcenDescuento2) {
		this.porcenDescuento2 = porcenDescuento2;
	}

	public void setPorcenDescuento3(String porcenDescuento3) {
		this.porcenDescuento3 = porcenDescuento3;
	}

	public void setReferenciaDeDocume(String referenciaDeDocume) {
		this.referenciaDeDocume = referenciaDeDocume;
	}

	public void setRepresentanteLegal(String representanteLegal) {
		this.representanteLegal = representanteLegal;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public void setTasaGlobalDeIva(String tasaGlobalDeIva) {
		this.tasaGlobalDeIva = tasaGlobalDeIva;
	}

	public void setTipoDeCambio(String tipoDeCambio) {
		this.tipoDeCambio = tipoDeCambio;
	}

	public void setTipoDeDocumento(String tipoDeDocumento) {
		this.tipoDeDocumento = tipoDeDocumento;
	}

	public void setTipoDeEnvio(String tipoDeEnvio) {
		this.tipoDeEnvio = tipoDeEnvio;
	}

	public void setTipoDescuento1(String tipoDescuento1) {
		this.tipoDescuento1 = tipoDescuento1;
	}

	public void setTipoDescuento2(String tipoDescuento2) {
		this.tipoDescuento2 = tipoDescuento2;
	}

	public void setTipoDescuento3(String tipoDescuento3) {
		this.tipoDescuento3 = tipoDescuento3;
	}

	public void setTipoImpresion(String tipoImpresion) {
		this.tipoImpresion = tipoImpresion;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return (Messages.getString("FeEncabezado.27") + serie + Messages.getString("FeEncabezado.28") + folio + Messages.getString("FeEncabezado.29") + noAprobacion + Messages.getString("FeEncabezado.30") + fechaCfd + Messages.getString("FeEncabezado.31") + referenciaDeDocume + Messages.getString("FeEncabezado.32") + fechaReferenciaDe + Messages.getString("FeEncabezado.33") + formaDePago + Messages.getString("FeEncabezado.34") + diasDePago + Messages.getString("FeEncabezado.35") + funcion + Messages.getString("FeEncabezado.36") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$ //$NON-NLS-9$ //$NON-NLS-10$
				+ tipoDeDocumento
				+ Messages.getString("FeEncabezado.37") + porcenDescuento1 + Messages.getString("FeEncabezado.38") + tipoDescuento1 + Messages.getString("FeEncabezado.39") + montoDeDescuento1 + Messages.getString("FeEncabezado.40") + porcenDescuento2 + Messages.getString("FeEncabezado.41") + tipoDescuento2 + Messages.getString("FeEncabezado.42") + montoDeDescuento2 + Messages.getString("FeEncabezado.43") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$
				+ porcenDescuento3
				+ Messages.getString("FeEncabezado.44") + tipoDescuento3 + Messages.getString("FeEncabezado.45") //$NON-NLS-1$ //$NON-NLS-2$
				+ montoDeDescuento3
				+ Messages.getString("FeEncabezado.46") //$NON-NLS-1$
				+ numeroInterno // ##21
				+ Messages.getString("FeEncabezado.47") + areaInterna + Messages.getString("FeEncabezado.48") //$NON-NLS-1$ //$NON-NLS-2$
				+ representanteLegal
				+ Messages.getString("FeEncabezado.49") //$NON-NLS-1$
				+ noProveedor // ##24
				+ Messages.getString("FeEncabezado.50") + tasaGlobalDeIva + Messages.getString("FeEncabezado.51") + numeroDeTienda + Messages.getString("FeEncabezado.52") + frm + Messages.getString("FeEncabezado.53") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$
				+ fechaDeFrm
				+ Messages.getString("FeEncabezado.54") //$NON-NLS-1$
				+ // Cuent predial
				Messages.getString("FeEncabezado.55") + metodoDePago + Messages.getString("FeEncabezado.56") + moneda + Messages.getString("FeEncabezado.57") + tipoDeCambio + Messages.getString("FeEncabezado.58") + fechaDeEntregaAct + Messages.getString("FeEncabezado.59") + contactoDeCompras + Messages.getString("FeEncabezado.60") + departamentoDelCon + Messages.getString("FeEncabezado.61") + observaciones1come + Messages.getString("FeEncabezado.62") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$ //$NON-NLS-7$ //$NON-NLS-8$
				+ observaciones2come
				+ Messages.getString("FeEncabezado.63") + observaciones3come + Messages.getString("FeEncabezado.64") + observaciones4come + Messages.getString("FeEncabezado.65") + observaciones5come + Messages.getString("FeEncabezado.66") + noAvisoAnticipado + Messages.getString("FeEncabezado.67") + fechaAvisoAnticipa + Messages.getString("FeEncabezado.68") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$
				+ NumberToLetterConverter.convertNumberToLetter(
						importeConLetra.replace("-",""), moneda)
				+ Messages.getString("FeEncabezado.69") + tipoDeEnvio + Messages.getString("FeEncabezado.70") + codigoIeps + Messages.getString("FeEncabezado.71") + etiqueta1 + Messages.getString("FeEncabezado.72") + etiqueta2 + Messages.getString("FeEncabezado.73") + etiqueta3 + Messages.getString("FeEncabezado.74") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$
				+ etiqueta4
				+ Messages.getString("FeEncabezado.75") + etiqueta5 + Messages.getString("FeEncabezado.76") + etiqueta6 + Messages.getString("FeEncabezado.77") + lugarDeExpedicion + Messages.getString("FeEncabezado.78")).replaceAll(Messages.getString("FeEncabezado.79"), Messages.getString("FeEncabezado.80")); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$
	}

}
