package mx.redts.adendas.model;

// Generated 15-jul-2014 23:09:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.security.core.GrantedAuthority;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "public")
public class Role implements GrantedAuthority {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7359459891687275955L;
	private String username;
	private String autoridad;

	public Role() {
	}

	public Role(String username, String autoridad) {
		super();
		this.username = username;
		this.autoridad = autoridad;
	}

	@Column(name = "authority", nullable = false, length = 80)
	public String getAuthority() {
		return this.autoridad.trim();
	}

	@Id
	@Column(name = "username", nullable = false)
	// @JoinColumn(name = "username", nullable = false, insertable = false,
	// updatable = false)
	public String getUsername() {
		return this.username;
	}

	public void setAuthority(String autoridad) {
		this.autoridad = autoridad;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	// @Override
	// public String toString() {
	// return autoridad.trim();
	// }

}
