package mx.redts.adendas.model;

// Generated 22-may-2014 23:59:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FeDetalleId generated by hbm2java
 */
@Embeddable
public class FeDetalleId implements java.io.Serializable {

	private String ob3id;
	private String eanOUpc;
	private String dun14;
	private String descripcion;
	private String descripcion2;
	private String cantidad;
	private String unidadDeMedida;
	private String cantEmpaque;
	private String precio;
	private String porcenDesc1;
	private String tipoDescuento1;
	private String montoDeDescuento1;
	private String porcenDescuento2;
	private String tipoDescuento2;
	private String montoDeDescuento2;
	private String porcenDescuento3;
	private String tipoDescuento3;
	private String montoDeDescuento3;
	private String porcenDescuento4;
	private String tipoDescuento4;
	private String montoDeDescuento4;
	private String porcenDescuento5;
	private String tipoDescuento5;
	private String montoDeDescuento5;
	private String precioNeto;
	private String porcenIva;
	private String porcenIeps;
	private String cantEmbarcada;
	private String aduana;
	private String fecha;
	private String numeroPedimento;
	private String numeroInternoDePr1;
	private String numeroInternoDePr2;
	private String cantidadGratisDeM;
	private String tipoDeEmpaque;
	private String pagoDeEmpaque;
	private String costoTotalPrecio;
	private String importeConDescuen;
	private String montoDeIva;
	private String montoDeIeps;
	private String porcenIsr;
	private String montoIsr;
	private String porcenImpuestoDePetrol;
	private String montoImpuestoDePe;
	private String porcenExento;
	private String montoExento;
	private String porcenEstatal;
	private String montoEstatal;
	private String porcenCedular;
	private String montoCedular;
	private String porcenMunicipal;
	private String montoMunicipal;
	private String porcenHospedaje;
	private String montoHospedaje;
	private String porcenOtrosImpuestos;
	private String montoOtrosImpuesto;
	private String ordenDeCompra;
	private String numeroDeCuentaPre;
	private String cantidadRealDeKil;
	private String cantidadMinimaASurtir;
	private String etiqueta1;
	private String etiqueta2;
	private String etiqueta3;
	private String etiqueta4;
	private String etiqueta5;
	private String etiqueta6;
	private String etiqueta7;
	private String etiqueta8;
	private String etiqueta9;
	private String etiqueta10;
	private String etiqueta11;
	private String etiqueta12;
	private String etiqueta13;

	public FeDetalleId() {
	}

	public FeDetalleId(String ob3id, String eanOUpc, String descripcion,
			String cantidad, String unidadDeMedida, String precio,
			String precioNeto, String porcenIva, String costoTotalPrecio,
			String montoDeIva) {
		this.ob3id = ob3id;
		this.eanOUpc = eanOUpc;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.unidadDeMedida = unidadDeMedida;
		this.precio = precio;
		this.precioNeto = precioNeto;
		this.porcenIva = porcenIva;
		this.costoTotalPrecio = costoTotalPrecio;
		this.montoDeIva = montoDeIva;
	}

	public FeDetalleId(String ob3id, String eanOUpc, String dun14,
			String descripcion, String descripcion2, String cantidad,
			String unidadDeMedida, String cantEmpaque, String precio,
			String porcenDesc1, String tipoDescuento1,
			String montoDeDescuento1, String porcenDescuento2,
			String tipoDescuento2, String montoDeDescuento2,
			String porcenDescuento3, String tipoDescuento3,
			String montoDeDescuento3, String porcenDescuento4,
			String tipoDescuento4, String montoDeDescuento4,
			String porcenDescuento5, String tipoDescuento5,
			String montoDeDescuento5, String precioNeto, String porcenIva,
			String porcenIeps, String cantEmbarcada, String aduana,
			String fecha, String numeroPedimento, String numeroInternoDePr1,
			String numeroInternoDePr2, String cantidadGratisDeM,
			String tipoDeEmpaque, String pagoDeEmpaque,
			String costoTotalPrecio, String importeConDescuen,
			String montoDeIva, String montoDeIeps, String porcenIsr,
			String montoIsr, String porcenImpuestoDePetrol,
			String montoImpuestoDePe, String porcenExento, String montoExento,
			String porcenEstatal, String montoEstatal, String porcenCedular,
			String montoCedular, String porcenMunicipal, String montoMunicipal,
			String porcenHospedaje, String montoHospedaje,
			String porcenOtrosImpuestos, String montoOtrosImpuesto,
			String ordenDeCompra, String numeroDeCuentaPre,
			String cantidadRealDeKil, String cantidadMinimaASurtir,
			String etiqueta1, String etiqueta2, String etiqueta3,
			String etiqueta4, String etiqueta5, String etiqueta6,
			String etiqueta7, String etiqueta8, String etiqueta9,
			String etiqueta10, String etiqueta11, String etiqueta12,
			String etiqueta13) {
		this.ob3id = ob3id;
		this.eanOUpc = eanOUpc;
		this.dun14 = dun14;
		this.descripcion = descripcion;
		this.descripcion2 = descripcion2;
		this.cantidad = cantidad;
		this.unidadDeMedida = unidadDeMedida;
		this.cantEmpaque = cantEmpaque;
		this.precio = precio;
		this.porcenDesc1 = porcenDesc1;
		this.tipoDescuento1 = tipoDescuento1;
		this.montoDeDescuento1 = montoDeDescuento1;
		this.porcenDescuento2 = porcenDescuento2;
		this.tipoDescuento2 = tipoDescuento2;
		this.montoDeDescuento2 = montoDeDescuento2;
		this.porcenDescuento3 = porcenDescuento3;
		this.tipoDescuento3 = tipoDescuento3;
		this.montoDeDescuento3 = montoDeDescuento3;
		this.porcenDescuento4 = porcenDescuento4;
		this.tipoDescuento4 = tipoDescuento4;
		this.montoDeDescuento4 = montoDeDescuento4;
		this.porcenDescuento5 = porcenDescuento5;
		this.tipoDescuento5 = tipoDescuento5;
		this.montoDeDescuento5 = montoDeDescuento5;
		this.precioNeto = precioNeto;
		this.porcenIva = porcenIva;
		this.porcenIeps = porcenIeps;
		this.cantEmbarcada = cantEmbarcada;
		this.aduana = aduana;
		this.fecha = fecha;
		this.numeroPedimento = numeroPedimento;
		this.numeroInternoDePr1 = numeroInternoDePr1;
		this.numeroInternoDePr2 = numeroInternoDePr2;
		this.cantidadGratisDeM = cantidadGratisDeM;
		this.tipoDeEmpaque = tipoDeEmpaque;
		this.pagoDeEmpaque = pagoDeEmpaque;
		this.costoTotalPrecio = costoTotalPrecio;
		this.importeConDescuen = importeConDescuen;
		this.montoDeIva = montoDeIva;
		this.montoDeIeps = montoDeIeps;
		this.porcenIsr = porcenIsr;
		this.montoIsr = montoIsr;
		this.porcenImpuestoDePetrol = porcenImpuestoDePetrol;
		this.montoImpuestoDePe = montoImpuestoDePe;
		this.porcenExento = porcenExento;
		this.montoExento = montoExento;
		this.porcenEstatal = porcenEstatal;
		this.montoEstatal = montoEstatal;
		this.porcenCedular = porcenCedular;
		this.montoCedular = montoCedular;
		this.porcenMunicipal = porcenMunicipal;
		this.montoMunicipal = montoMunicipal;
		this.porcenHospedaje = porcenHospedaje;
		this.montoHospedaje = montoHospedaje;
		this.porcenOtrosImpuestos = porcenOtrosImpuestos;
		this.montoOtrosImpuesto = montoOtrosImpuesto;
		this.ordenDeCompra = ordenDeCompra;
		this.numeroDeCuentaPre = numeroDeCuentaPre;
		this.cantidadRealDeKil = cantidadRealDeKil;
		this.cantidadMinimaASurtir = cantidadMinimaASurtir;
		this.etiqueta1 = etiqueta1;
		this.etiqueta2 = etiqueta2;
		this.etiqueta3 = etiqueta3;
		this.etiqueta4 = etiqueta4;
		this.etiqueta5 = etiqueta5;
		this.etiqueta6 = etiqueta6;
		this.etiqueta7 = etiqueta7;
		this.etiqueta8 = etiqueta8;
		this.etiqueta9 = etiqueta9;
		this.etiqueta10 = etiqueta10;
		this.etiqueta11 = etiqueta11;
		this.etiqueta12 = etiqueta12;
		this.etiqueta13 = etiqueta13;
	}

	@Column(name = "ob3id", nullable = false, length = 32)
	public String getOb3id() {
		return this.ob3id;
	}

	public void setOb3id(String ob3id) {
		this.ob3id = ob3id;
	}

	@Column(name = "ean_o_upc", nullable = false, length = 15)
	public String getEanOUpc() {
		return this.eanOUpc;
	}

	public void setEanOUpc(String eanOUpc) {
		this.eanOUpc = eanOUpc;
	}

	@Column(name = "dun_14", length = 14)
	public String getDun14() {
		return this.dun14;
	}

	public void setDun14(String dun14) {
		this.dun14 = dun14;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "descripcion2", length = 100)
	public String getDescripcion2() {
		return this.descripcion2;
	}

	public void setDescripcion2(String descripcion2) {
		this.descripcion2 = descripcion2;
	}

	@Column(name = "cantidad", nullable = false, length = 10)
	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "unidad_de_medida", nullable = false, length = 10)
	public String getUnidadDeMedida() {
		return this.unidadDeMedida;
	}

	public void setUnidadDeMedida(String unidadDeMedida) {
		this.unidadDeMedida = unidadDeMedida;
	}

	@Column(name = "cant_empaque", length = 5)
	public String getCantEmpaque() {
		return this.cantEmpaque;
	}

	public void setCantEmpaque(String cantEmpaque) {
		this.cantEmpaque = cantEmpaque;
	}

	@Column(name = "precio", nullable = false, length = 20)
	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	@Column(name = "porcen_desc_1", length = 3)
	public String getPorcenDesc1() {
		return this.porcenDesc1;
	}

	public void setPorcenDesc1(String porcenDesc1) {
		this.porcenDesc1 = porcenDesc1;
	}

	@Column(name = "tipo_descuento_1", length = 5)
	public String getTipoDescuento1() {
		return this.tipoDescuento1;
	}

	public void setTipoDescuento1(String tipoDescuento1) {
		this.tipoDescuento1 = tipoDescuento1;
	}

	@Column(name = "monto_de_descuento_1", length = 20)
	public String getMontoDeDescuento1() {
		return this.montoDeDescuento1;
	}

	public void setMontoDeDescuento1(String montoDeDescuento1) {
		this.montoDeDescuento1 = montoDeDescuento1;
	}

	@Column(name = "porcen_descuento_2", length = 3)
	public String getPorcenDescuento2() {
		return this.porcenDescuento2;
	}

	public void setPorcenDescuento2(String porcenDescuento2) {
		this.porcenDescuento2 = porcenDescuento2;
	}

	@Column(name = "tipo_descuento_2", length = 5)
	public String getTipoDescuento2() {
		return this.tipoDescuento2;
	}

	public void setTipoDescuento2(String tipoDescuento2) {
		this.tipoDescuento2 = tipoDescuento2;
	}

	@Column(name = "monto_de_descuento_2", length = 20)
	public String getMontoDeDescuento2() {
		return this.montoDeDescuento2;
	}

	public void setMontoDeDescuento2(String montoDeDescuento2) {
		this.montoDeDescuento2 = montoDeDescuento2;
	}

	@Column(name = "porcen_descuento_3", length = 3)
	public String getPorcenDescuento3() {
		return this.porcenDescuento3;
	}

	public void setPorcenDescuento3(String porcenDescuento3) {
		this.porcenDescuento3 = porcenDescuento3;
	}

	@Column(name = "tipo_descuento_3", length = 5)
	public String getTipoDescuento3() {
		return this.tipoDescuento3;
	}

	public void setTipoDescuento3(String tipoDescuento3) {
		this.tipoDescuento3 = tipoDescuento3;
	}

	@Column(name = "monto_de_descuento_3", length = 20)
	public String getMontoDeDescuento3() {
		return this.montoDeDescuento3;
	}

	public void setMontoDeDescuento3(String montoDeDescuento3) {
		this.montoDeDescuento3 = montoDeDescuento3;
	}

	@Column(name = "porcen_descuento_4", length = 3)
	public String getPorcenDescuento4() {
		return this.porcenDescuento4;
	}

	public void setPorcenDescuento4(String porcenDescuento4) {
		this.porcenDescuento4 = porcenDescuento4;
	}

	@Column(name = "tipo_descuento_4", length = 5)
	public String getTipoDescuento4() {
		return this.tipoDescuento4;
	}

	public void setTipoDescuento4(String tipoDescuento4) {
		this.tipoDescuento4 = tipoDescuento4;
	}

	@Column(name = "monto_de_descuento_4", length = 20)
	public String getMontoDeDescuento4() {
		return this.montoDeDescuento4;
	}

	public void setMontoDeDescuento4(String montoDeDescuento4) {
		this.montoDeDescuento4 = montoDeDescuento4;
	}

	@Column(name = "porcen_descuento_5", length = 3)
	public String getPorcenDescuento5() {
		return this.porcenDescuento5;
	}

	public void setPorcenDescuento5(String porcenDescuento5) {
		this.porcenDescuento5 = porcenDescuento5;
	}

	@Column(name = "tipo_descuento_5", length = 5)
	public String getTipoDescuento5() {
		return this.tipoDescuento5;
	}

	public void setTipoDescuento5(String tipoDescuento5) {
		this.tipoDescuento5 = tipoDescuento5;
	}

	@Column(name = "monto_de_descuento_5", length = 20)
	public String getMontoDeDescuento5() {
		return this.montoDeDescuento5;
	}

	public void setMontoDeDescuento5(String montoDeDescuento5) {
		this.montoDeDescuento5 = montoDeDescuento5;
	}

	@Column(name = "precio_neto", nullable = false, length = 20)
	public String getPrecioNeto() {
		return this.precioNeto;
	}

	public void setPrecioNeto(String precioNeto) {
		this.precioNeto = precioNeto;
	}

	@Column(name = "porcen_iva", nullable = false, length = 3)
	public String getPorcenIva() {
		return this.porcenIva;
	}

	public void setPorcenIva(String porcenIva) {
		this.porcenIva = porcenIva;
	}

	@Column(name = "porcen_ieps", length = 3)
	public String getPorcenIeps() {
		return this.porcenIeps;
	}

	public void setPorcenIeps(String porcenIeps) {
		this.porcenIeps = porcenIeps;
	}

	@Column(name = "cant_embarcada", length = 5)
	public String getCantEmbarcada() {
		return this.cantEmbarcada;
	}

	public void setCantEmbarcada(String cantEmbarcada) {
		this.cantEmbarcada = cantEmbarcada;
	}

	@Column(name = "aduana", length = 10)
	public String getAduana() {
		return this.aduana;
	}

	public void setAduana(String aduana) {
		this.aduana = aduana;
	}

	@Column(name = "fecha", length = 10)
	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	@Column(name = "numero_pedimento", length = 8)
	public String getNumeroPedimento() {
		return this.numeroPedimento;
	}

	public void setNumeroPedimento(String numeroPedimento) {
		this.numeroPedimento = numeroPedimento;
	}

	@Column(name = "numero_interno_de_pr1", length = 8)
	public String getNumeroInternoDePr1() {
		return this.numeroInternoDePr1;
	}

	public void setNumeroInternoDePr1(String numeroInternoDePr1) {
		this.numeroInternoDePr1 = numeroInternoDePr1;
	}

	@Column(name = "numero_interno_de_pr2", length = 8)
	public String getNumeroInternoDePr2() {
		return this.numeroInternoDePr2;
	}

	public void setNumeroInternoDePr2(String numeroInternoDePr2) {
		this.numeroInternoDePr2 = numeroInternoDePr2;
	}

	@Column(name = "cantidad_gratis_de_m", length = 5)
	public String getCantidadGratisDeM() {
		return this.cantidadGratisDeM;
	}

	public void setCantidadGratisDeM(String cantidadGratisDeM) {
		this.cantidadGratisDeM = cantidadGratisDeM;
	}

	@Column(name = "tipo_de_empaque", length = 5)
	public String getTipoDeEmpaque() {
		return this.tipoDeEmpaque;
	}

	public void setTipoDeEmpaque(String tipoDeEmpaque) {
		this.tipoDeEmpaque = tipoDeEmpaque;
	}

	@Column(name = "pago_de_empaque", length = 10)
	public String getPagoDeEmpaque() {
		return this.pagoDeEmpaque;
	}

	public void setPagoDeEmpaque(String pagoDeEmpaque) {
		this.pagoDeEmpaque = pagoDeEmpaque;
	}

	@Column(name = "costo_total_precio", nullable = false, length = 20)
	public String getCostoTotalPrecio() {
		return this.costoTotalPrecio;
	}

	public void setCostoTotalPrecio(String costoTotalPrecio) {
		this.costoTotalPrecio = costoTotalPrecio;
	}

	@Column(name = "importe_con_descuen", length = 20)
	public String getImporteConDescuen() {
		return this.importeConDescuen;
	}

	public void setImporteConDescuen(String importeConDescuen) {
		this.importeConDescuen = importeConDescuen;
	}

	@Column(name = "monto_de_iva", nullable = false, length = 20)
	public String getMontoDeIva() {
		return this.montoDeIva;
	}

	public void setMontoDeIva(String montoDeIva) {
		this.montoDeIva = montoDeIva;
	}

	@Column(name = "monto_de_ieps", length = 20)
	public String getMontoDeIeps() {
		return this.montoDeIeps;
	}

	public void setMontoDeIeps(String montoDeIeps) {
		this.montoDeIeps = montoDeIeps;
	}

	@Column(name = "porcen_isr", length = 3)
	public String getPorcenIsr() {
		return this.porcenIsr;
	}

	public void setPorcenIsr(String porcenIsr) {
		this.porcenIsr = porcenIsr;
	}

	@Column(name = "monto_isr", length = 20)
	public String getMontoIsr() {
		return this.montoIsr;
	}

	public void setMontoIsr(String montoIsr) {
		this.montoIsr = montoIsr;
	}

	@Column(name = "porcen_impuesto_de_petrol", length = 3)
	public String getPorcenImpuestoDePetrol() {
		return this.porcenImpuestoDePetrol;
	}

	public void setPorcenImpuestoDePetrol(String porcenImpuestoDePetrol) {
		this.porcenImpuestoDePetrol = porcenImpuestoDePetrol;
	}

	@Column(name = "monto_impuesto_de_pe", length = 20)
	public String getMontoImpuestoDePe() {
		return this.montoImpuestoDePe;
	}

	public void setMontoImpuestoDePe(String montoImpuestoDePe) {
		this.montoImpuestoDePe = montoImpuestoDePe;
	}

	@Column(name = "porcen_exento", length = 3)
	public String getPorcenExento() {
		return this.porcenExento;
	}

	public void setPorcenExento(String porcenExento) {
		this.porcenExento = porcenExento;
	}

	@Column(name = "monto_exento", length = 20)
	public String getMontoExento() {
		return this.montoExento;
	}

	public void setMontoExento(String montoExento) {
		this.montoExento = montoExento;
	}

	@Column(name = "porcen_estatal", length = 3)
	public String getPorcenEstatal() {
		return this.porcenEstatal;
	}

	public void setPorcenEstatal(String porcenEstatal) {
		this.porcenEstatal = porcenEstatal;
	}

	@Column(name = "monto_estatal", length = 20)
	public String getMontoEstatal() {
		return this.montoEstatal;
	}

	public void setMontoEstatal(String montoEstatal) {
		this.montoEstatal = montoEstatal;
	}

	@Column(name = "porcen_cedular", length = 3)
	public String getPorcenCedular() {
		return this.porcenCedular;
	}

	public void setPorcenCedular(String porcenCedular) {
		this.porcenCedular = porcenCedular;
	}

	@Column(name = "monto_cedular", length = 20)
	public String getMontoCedular() {
		return this.montoCedular;
	}

	public void setMontoCedular(String montoCedular) {
		this.montoCedular = montoCedular;
	}

	@Column(name = "porcen_municipal", length = 3)
	public String getPorcenMunicipal() {
		return this.porcenMunicipal;
	}

	public void setPorcenMunicipal(String porcenMunicipal) {
		this.porcenMunicipal = porcenMunicipal;
	}

	@Column(name = "monto_municipal", length = 20)
	public String getMontoMunicipal() {
		return this.montoMunicipal;
	}

	public void setMontoMunicipal(String montoMunicipal) {
		this.montoMunicipal = montoMunicipal;
	}

	@Column(name = "porcen_hospedaje", length = 3)
	public String getPorcenHospedaje() {
		return this.porcenHospedaje;
	}

	public void setPorcenHospedaje(String porcenHospedaje) {
		this.porcenHospedaje = porcenHospedaje;
	}

	@Column(name = "monto_hospedaje", length = 20)
	public String getMontoHospedaje() {
		return this.montoHospedaje;
	}

	public void setMontoHospedaje(String montoHospedaje) {
		this.montoHospedaje = montoHospedaje;
	}

	@Column(name = "porcen_otros_impuestos", length = 3)
	public String getPorcenOtrosImpuestos() {
		return this.porcenOtrosImpuestos;
	}

	public void setPorcenOtrosImpuestos(String porcenOtrosImpuestos) {
		this.porcenOtrosImpuestos = porcenOtrosImpuestos;
	}

	@Column(name = "monto_otros_impuesto", length = 20)
	public String getMontoOtrosImpuesto() {
		return this.montoOtrosImpuesto;
	}

	public void setMontoOtrosImpuesto(String montoOtrosImpuesto) {
		this.montoOtrosImpuesto = montoOtrosImpuesto;
	}

	@Column(name = "orden_de_compra", length = 3)
	public String getOrdenDeCompra() {
		return this.ordenDeCompra;
	}

	public void setOrdenDeCompra(String ordenDeCompra) {
		this.ordenDeCompra = ordenDeCompra;
	}

	@Column(name = "numero_de_cuenta_pre", length = 20)
	public String getNumeroDeCuentaPre() {
		return this.numeroDeCuentaPre;
	}

	public void setNumeroDeCuentaPre(String numeroDeCuentaPre) {
		this.numeroDeCuentaPre = numeroDeCuentaPre;
	}

	@Column(name = "cantidad_real_de_kil", length = 10)
	public String getCantidadRealDeKil() {
		return this.cantidadRealDeKil;
	}

	public void setCantidadRealDeKil(String cantidadRealDeKil) {
		this.cantidadRealDeKil = cantidadRealDeKil;
	}

	@Column(name = "cantidad_minima_a_surtir", length = 10)
	public String getCantidadMinimaASurtir() {
		return this.cantidadMinimaASurtir;
	}

	public void setCantidadMinimaASurtir(String cantidadMinimaASurtir) {
		this.cantidadMinimaASurtir = cantidadMinimaASurtir;
	}

	@Column(name = "etiqueta_1", length = 100)
	public String getEtiqueta1() {
		return this.etiqueta1;
	}

	public void setEtiqueta1(String etiqueta1) {
		this.etiqueta1 = etiqueta1;
	}

	@Column(name = "etiqueta_2", length = 100)
	public String getEtiqueta2() {
		return this.etiqueta2;
	}

	public void setEtiqueta2(String etiqueta2) {
		this.etiqueta2 = etiqueta2;
	}

	@Column(name = "etiqueta_3", length = 100)
	public String getEtiqueta3() {
		return this.etiqueta3;
	}

	public void setEtiqueta3(String etiqueta3) {
		this.etiqueta3 = etiqueta3;
	}

	@Column(name = "etiqueta_4", length = 100)
	public String getEtiqueta4() {
		return this.etiqueta4;
	}

	public void setEtiqueta4(String etiqueta4) {
		this.etiqueta4 = etiqueta4;
	}

	@Column(name = "etiqueta_5", length = 100)
	public String getEtiqueta5() {
		return this.etiqueta5;
	}

	public void setEtiqueta5(String etiqueta5) {
		this.etiqueta5 = etiqueta5;
	}

	@Column(name = "etiqueta_6", length = 100)
	public String getEtiqueta6() {
		return this.etiqueta6;
	}

	public void setEtiqueta6(String etiqueta6) {
		this.etiqueta6 = etiqueta6;
	}

	@Column(name = "etiqueta_7", length = 100)
	public String getEtiqueta7() {
		return this.etiqueta7;
	}

	public void setEtiqueta7(String etiqueta7) {
		this.etiqueta7 = etiqueta7;
	}

	@Column(name = "etiqueta_8", length = 100)
	public String getEtiqueta8() {
		return this.etiqueta8;
	}

	public void setEtiqueta8(String etiqueta8) {
		this.etiqueta8 = etiqueta8;
	}

	@Column(name = "etiqueta_9", length = 100)
	public String getEtiqueta9() {
		return this.etiqueta9;
	}

	public void setEtiqueta9(String etiqueta9) {
		this.etiqueta9 = etiqueta9;
	}

	@Column(name = "etiqueta_10", length = 100)
	public String getEtiqueta10() {
		return this.etiqueta10;
	}

	public void setEtiqueta10(String etiqueta10) {
		this.etiqueta10 = etiqueta10;
	}

	@Column(name = "etiqueta_11", length = 100)
	public String getEtiqueta11() {
		return this.etiqueta11;
	}

	public void setEtiqueta11(String etiqueta11) {
		this.etiqueta11 = etiqueta11;
	}

	@Column(name = "etiqueta_12", length = 100)
	public String getEtiqueta12() {
		return this.etiqueta12;
	}

	public void setEtiqueta12(String etiqueta12) {
		this.etiqueta12 = etiqueta12;
	}

	@Column(name = "etiqueta_13", length = 100)
	public String getEtiqueta13() {
		return this.etiqueta13;
	}

	public void setEtiqueta13(String etiqueta13) {
		this.etiqueta13 = etiqueta13;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FeDetalleId))
			return false;
		FeDetalleId castOther = (FeDetalleId) other;

		return ((this.getOb3id() == castOther.getOb3id()) || (this.getOb3id() != null
				&& castOther.getOb3id() != null && this.getOb3id().equals(
				castOther.getOb3id())))
				&& ((this.getEanOUpc() == castOther.getEanOUpc()) || (this
						.getEanOUpc() != null && castOther.getEanOUpc() != null && this
						.getEanOUpc().equals(castOther.getEanOUpc())))
				&& ((this.getDun14() == castOther.getDun14()) || (this
						.getDun14() != null && castOther.getDun14() != null && this
						.getDun14().equals(castOther.getDun14())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getDescripcion2() == castOther.getDescripcion2()) || (this
						.getDescripcion2() != null
						&& castOther.getDescripcion2() != null && this
						.getDescripcion2().equals(castOther.getDescripcion2())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this
						.getCantidad() != null
						&& castOther.getCantidad() != null && this
						.getCantidad().equals(castOther.getCantidad())))
				&& ((this.getUnidadDeMedida() == castOther.getUnidadDeMedida()) || (this
						.getUnidadDeMedida() != null
						&& castOther.getUnidadDeMedida() != null && this
						.getUnidadDeMedida().equals(
								castOther.getUnidadDeMedida())))
				&& ((this.getCantEmpaque() == castOther.getCantEmpaque()) || (this
						.getCantEmpaque() != null
						&& castOther.getCantEmpaque() != null && this
						.getCantEmpaque().equals(castOther.getCantEmpaque())))
				&& ((this.getPrecio() == castOther.getPrecio()) || (this
						.getPrecio() != null && castOther.getPrecio() != null && this
						.getPrecio().equals(castOther.getPrecio())))
				&& ((this.getPorcenDesc1() == castOther.getPorcenDesc1()) || (this
						.getPorcenDesc1() != null
						&& castOther.getPorcenDesc1() != null && this
						.getPorcenDesc1().equals(castOther.getPorcenDesc1())))
				&& ((this.getTipoDescuento1() == castOther.getTipoDescuento1()) || (this
						.getTipoDescuento1() != null
						&& castOther.getTipoDescuento1() != null && this
						.getTipoDescuento1().equals(
								castOther.getTipoDescuento1())))
				&& ((this.getMontoDeDescuento1() == castOther
						.getMontoDeDescuento1()) || (this
						.getMontoDeDescuento1() != null
						&& castOther.getMontoDeDescuento1() != null && this
						.getMontoDeDescuento1().equals(
								castOther.getMontoDeDescuento1())))
				&& ((this.getPorcenDescuento2() == castOther
						.getPorcenDescuento2()) || (this.getPorcenDescuento2() != null
						&& castOther.getPorcenDescuento2() != null && this
						.getPorcenDescuento2().equals(
								castOther.getPorcenDescuento2())))
				&& ((this.getTipoDescuento2() == castOther.getTipoDescuento2()) || (this
						.getTipoDescuento2() != null
						&& castOther.getTipoDescuento2() != null && this
						.getTipoDescuento2().equals(
								castOther.getTipoDescuento2())))
				&& ((this.getMontoDeDescuento2() == castOther
						.getMontoDeDescuento2()) || (this
						.getMontoDeDescuento2() != null
						&& castOther.getMontoDeDescuento2() != null && this
						.getMontoDeDescuento2().equals(
								castOther.getMontoDeDescuento2())))
				&& ((this.getPorcenDescuento3() == castOther
						.getPorcenDescuento3()) || (this.getPorcenDescuento3() != null
						&& castOther.getPorcenDescuento3() != null && this
						.getPorcenDescuento3().equals(
								castOther.getPorcenDescuento3())))
				&& ((this.getTipoDescuento3() == castOther.getTipoDescuento3()) || (this
						.getTipoDescuento3() != null
						&& castOther.getTipoDescuento3() != null && this
						.getTipoDescuento3().equals(
								castOther.getTipoDescuento3())))
				&& ((this.getMontoDeDescuento3() == castOther
						.getMontoDeDescuento3()) || (this
						.getMontoDeDescuento3() != null
						&& castOther.getMontoDeDescuento3() != null && this
						.getMontoDeDescuento3().equals(
								castOther.getMontoDeDescuento3())))
				&& ((this.getPorcenDescuento4() == castOther
						.getPorcenDescuento4()) || (this.getPorcenDescuento4() != null
						&& castOther.getPorcenDescuento4() != null && this
						.getPorcenDescuento4().equals(
								castOther.getPorcenDescuento4())))
				&& ((this.getTipoDescuento4() == castOther.getTipoDescuento4()) || (this
						.getTipoDescuento4() != null
						&& castOther.getTipoDescuento4() != null && this
						.getTipoDescuento4().equals(
								castOther.getTipoDescuento4())))
				&& ((this.getMontoDeDescuento4() == castOther
						.getMontoDeDescuento4()) || (this
						.getMontoDeDescuento4() != null
						&& castOther.getMontoDeDescuento4() != null && this
						.getMontoDeDescuento4().equals(
								castOther.getMontoDeDescuento4())))
				&& ((this.getPorcenDescuento5() == castOther
						.getPorcenDescuento5()) || (this.getPorcenDescuento5() != null
						&& castOther.getPorcenDescuento5() != null && this
						.getPorcenDescuento5().equals(
								castOther.getPorcenDescuento5())))
				&& ((this.getTipoDescuento5() == castOther.getTipoDescuento5()) || (this
						.getTipoDescuento5() != null
						&& castOther.getTipoDescuento5() != null && this
						.getTipoDescuento5().equals(
								castOther.getTipoDescuento5())))
				&& ((this.getMontoDeDescuento5() == castOther
						.getMontoDeDescuento5()) || (this
						.getMontoDeDescuento5() != null
						&& castOther.getMontoDeDescuento5() != null && this
						.getMontoDeDescuento5().equals(
								castOther.getMontoDeDescuento5())))
				&& ((this.getPrecioNeto() == castOther.getPrecioNeto()) || (this
						.getPrecioNeto() != null
						&& castOther.getPrecioNeto() != null && this
						.getPrecioNeto().equals(castOther.getPrecioNeto())))
				&& ((this.getPorcenIva() == castOther.getPorcenIva()) || (this
						.getPorcenIva() != null
						&& castOther.getPorcenIva() != null && this
						.getPorcenIva().equals(castOther.getPorcenIva())))
				&& ((this.getPorcenIeps() == castOther.getPorcenIeps()) || (this
						.getPorcenIeps() != null
						&& castOther.getPorcenIeps() != null && this
						.getPorcenIeps().equals(castOther.getPorcenIeps())))
				&& ((this.getCantEmbarcada() == castOther.getCantEmbarcada()) || (this
						.getCantEmbarcada() != null
						&& castOther.getCantEmbarcada() != null && this
						.getCantEmbarcada()
						.equals(castOther.getCantEmbarcada())))
				&& ((this.getAduana() == castOther.getAduana()) || (this
						.getAduana() != null && castOther.getAduana() != null && this
						.getAduana().equals(castOther.getAduana())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getNumeroPedimento() == castOther
						.getNumeroPedimento()) || (this.getNumeroPedimento() != null
						&& castOther.getNumeroPedimento() != null && this
						.getNumeroPedimento().equals(
								castOther.getNumeroPedimento())))
				&& ((this.getNumeroInternoDePr1() == castOther
						.getNumeroInternoDePr1()) || (this
						.getNumeroInternoDePr1() != null
						&& castOther.getNumeroInternoDePr1() != null && this
						.getNumeroInternoDePr1().equals(
								castOther.getNumeroInternoDePr1())))
				&& ((this.getNumeroInternoDePr2() == castOther
						.getNumeroInternoDePr2()) || (this
						.getNumeroInternoDePr2() != null
						&& castOther.getNumeroInternoDePr2() != null && this
						.getNumeroInternoDePr2().equals(
								castOther.getNumeroInternoDePr2())))
				&& ((this.getCantidadGratisDeM() == castOther
						.getCantidadGratisDeM()) || (this
						.getCantidadGratisDeM() != null
						&& castOther.getCantidadGratisDeM() != null && this
						.getCantidadGratisDeM().equals(
								castOther.getCantidadGratisDeM())))
				&& ((this.getTipoDeEmpaque() == castOther.getTipoDeEmpaque()) || (this
						.getTipoDeEmpaque() != null
						&& castOther.getTipoDeEmpaque() != null && this
						.getTipoDeEmpaque()
						.equals(castOther.getTipoDeEmpaque())))
				&& ((this.getPagoDeEmpaque() == castOther.getPagoDeEmpaque()) || (this
						.getPagoDeEmpaque() != null
						&& castOther.getPagoDeEmpaque() != null && this
						.getPagoDeEmpaque()
						.equals(castOther.getPagoDeEmpaque())))
				&& ((this.getCostoTotalPrecio() == castOther
						.getCostoTotalPrecio()) || (this.getCostoTotalPrecio() != null
						&& castOther.getCostoTotalPrecio() != null && this
						.getCostoTotalPrecio().equals(
								castOther.getCostoTotalPrecio())))
				&& ((this.getImporteConDescuen() == castOther
						.getImporteConDescuen()) || (this
						.getImporteConDescuen() != null
						&& castOther.getImporteConDescuen() != null && this
						.getImporteConDescuen().equals(
								castOther.getImporteConDescuen())))
				&& ((this.getMontoDeIva() == castOther.getMontoDeIva()) || (this
						.getMontoDeIva() != null
						&& castOther.getMontoDeIva() != null && this
						.getMontoDeIva().equals(castOther.getMontoDeIva())))
				&& ((this.getMontoDeIeps() == castOther.getMontoDeIeps()) || (this
						.getMontoDeIeps() != null
						&& castOther.getMontoDeIeps() != null && this
						.getMontoDeIeps().equals(castOther.getMontoDeIeps())))
				&& ((this.getPorcenIsr() == castOther.getPorcenIsr()) || (this
						.getPorcenIsr() != null
						&& castOther.getPorcenIsr() != null && this
						.getPorcenIsr().equals(castOther.getPorcenIsr())))
				&& ((this.getMontoIsr() == castOther.getMontoIsr()) || (this
						.getMontoIsr() != null
						&& castOther.getMontoIsr() != null && this
						.getMontoIsr().equals(castOther.getMontoIsr())))
				&& ((this.getPorcenImpuestoDePetrol() == castOther
						.getPorcenImpuestoDePetrol()) || (this
						.getPorcenImpuestoDePetrol() != null
						&& castOther.getPorcenImpuestoDePetrol() != null && this
						.getPorcenImpuestoDePetrol().equals(
								castOther.getPorcenImpuestoDePetrol())))
				&& ((this.getMontoImpuestoDePe() == castOther
						.getMontoImpuestoDePe()) || (this
						.getMontoImpuestoDePe() != null
						&& castOther.getMontoImpuestoDePe() != null && this
						.getMontoImpuestoDePe().equals(
								castOther.getMontoImpuestoDePe())))
				&& ((this.getPorcenExento() == castOther.getPorcenExento()) || (this
						.getPorcenExento() != null
						&& castOther.getPorcenExento() != null && this
						.getPorcenExento().equals(castOther.getPorcenExento())))
				&& ((this.getMontoExento() == castOther.getMontoExento()) || (this
						.getMontoExento() != null
						&& castOther.getMontoExento() != null && this
						.getMontoExento().equals(castOther.getMontoExento())))
				&& ((this.getPorcenEstatal() == castOther.getPorcenEstatal()) || (this
						.getPorcenEstatal() != null
						&& castOther.getPorcenEstatal() != null && this
						.getPorcenEstatal()
						.equals(castOther.getPorcenEstatal())))
				&& ((this.getMontoEstatal() == castOther.getMontoEstatal()) || (this
						.getMontoEstatal() != null
						&& castOther.getMontoEstatal() != null && this
						.getMontoEstatal().equals(castOther.getMontoEstatal())))
				&& ((this.getPorcenCedular() == castOther.getPorcenCedular()) || (this
						.getPorcenCedular() != null
						&& castOther.getPorcenCedular() != null && this
						.getPorcenCedular()
						.equals(castOther.getPorcenCedular())))
				&& ((this.getMontoCedular() == castOther.getMontoCedular()) || (this
						.getMontoCedular() != null
						&& castOther.getMontoCedular() != null && this
						.getMontoCedular().equals(castOther.getMontoCedular())))
				&& ((this.getPorcenMunicipal() == castOther
						.getPorcenMunicipal()) || (this.getPorcenMunicipal() != null
						&& castOther.getPorcenMunicipal() != null && this
						.getPorcenMunicipal().equals(
								castOther.getPorcenMunicipal())))
				&& ((this.getMontoMunicipal() == castOther.getMontoMunicipal()) || (this
						.getMontoMunicipal() != null
						&& castOther.getMontoMunicipal() != null && this
						.getMontoMunicipal().equals(
								castOther.getMontoMunicipal())))
				&& ((this.getPorcenHospedaje() == castOther
						.getPorcenHospedaje()) || (this.getPorcenHospedaje() != null
						&& castOther.getPorcenHospedaje() != null && this
						.getPorcenHospedaje().equals(
								castOther.getPorcenHospedaje())))
				&& ((this.getMontoHospedaje() == castOther.getMontoHospedaje()) || (this
						.getMontoHospedaje() != null
						&& castOther.getMontoHospedaje() != null && this
						.getMontoHospedaje().equals(
								castOther.getMontoHospedaje())))
				&& ((this.getPorcenOtrosImpuestos() == castOther
						.getPorcenOtrosImpuestos()) || (this
						.getPorcenOtrosImpuestos() != null
						&& castOther.getPorcenOtrosImpuestos() != null && this
						.getPorcenOtrosImpuestos().equals(
								castOther.getPorcenOtrosImpuestos())))
				&& ((this.getMontoOtrosImpuesto() == castOther
						.getMontoOtrosImpuesto()) || (this
						.getMontoOtrosImpuesto() != null
						&& castOther.getMontoOtrosImpuesto() != null && this
						.getMontoOtrosImpuesto().equals(
								castOther.getMontoOtrosImpuesto())))
				&& ((this.getOrdenDeCompra() == castOther.getOrdenDeCompra()) || (this
						.getOrdenDeCompra() != null
						&& castOther.getOrdenDeCompra() != null && this
						.getOrdenDeCompra()
						.equals(castOther.getOrdenDeCompra())))
				&& ((this.getNumeroDeCuentaPre() == castOther
						.getNumeroDeCuentaPre()) || (this
						.getNumeroDeCuentaPre() != null
						&& castOther.getNumeroDeCuentaPre() != null && this
						.getNumeroDeCuentaPre().equals(
								castOther.getNumeroDeCuentaPre())))
				&& ((this.getCantidadRealDeKil() == castOther
						.getCantidadRealDeKil()) || (this
						.getCantidadRealDeKil() != null
						&& castOther.getCantidadRealDeKil() != null && this
						.getCantidadRealDeKil().equals(
								castOther.getCantidadRealDeKil())))
				&& ((this.getCantidadMinimaASurtir() == castOther
						.getCantidadMinimaASurtir()) || (this
						.getCantidadMinimaASurtir() != null
						&& castOther.getCantidadMinimaASurtir() != null && this
						.getCantidadMinimaASurtir().equals(
								castOther.getCantidadMinimaASurtir())))
				&& ((this.getEtiqueta1() == castOther.getEtiqueta1()) || (this
						.getEtiqueta1() != null
						&& castOther.getEtiqueta1() != null && this
						.getEtiqueta1().equals(castOther.getEtiqueta1())))
				&& ((this.getEtiqueta2() == castOther.getEtiqueta2()) || (this
						.getEtiqueta2() != null
						&& castOther.getEtiqueta2() != null && this
						.getEtiqueta2().equals(castOther.getEtiqueta2())))
				&& ((this.getEtiqueta3() == castOther.getEtiqueta3()) || (this
						.getEtiqueta3() != null
						&& castOther.getEtiqueta3() != null && this
						.getEtiqueta3().equals(castOther.getEtiqueta3())))
				&& ((this.getEtiqueta4() == castOther.getEtiqueta4()) || (this
						.getEtiqueta4() != null
						&& castOther.getEtiqueta4() != null && this
						.getEtiqueta4().equals(castOther.getEtiqueta4())))
				&& ((this.getEtiqueta5() == castOther.getEtiqueta5()) || (this
						.getEtiqueta5() != null
						&& castOther.getEtiqueta5() != null && this
						.getEtiqueta5().equals(castOther.getEtiqueta5())))
				&& ((this.getEtiqueta6() == castOther.getEtiqueta6()) || (this
						.getEtiqueta6() != null
						&& castOther.getEtiqueta6() != null && this
						.getEtiqueta6().equals(castOther.getEtiqueta6())))
				&& ((this.getEtiqueta7() == castOther.getEtiqueta7()) || (this
						.getEtiqueta7() != null
						&& castOther.getEtiqueta7() != null && this
						.getEtiqueta7().equals(castOther.getEtiqueta7())))
				&& ((this.getEtiqueta8() == castOther.getEtiqueta8()) || (this
						.getEtiqueta8() != null
						&& castOther.getEtiqueta8() != null && this
						.getEtiqueta8().equals(castOther.getEtiqueta8())))
				&& ((this.getEtiqueta9() == castOther.getEtiqueta9()) || (this
						.getEtiqueta9() != null
						&& castOther.getEtiqueta9() != null && this
						.getEtiqueta9().equals(castOther.getEtiqueta9())))
				&& ((this.getEtiqueta10() == castOther.getEtiqueta10()) || (this
						.getEtiqueta10() != null
						&& castOther.getEtiqueta10() != null && this
						.getEtiqueta10().equals(castOther.getEtiqueta10())))
				&& ((this.getEtiqueta11() == castOther.getEtiqueta11()) || (this
						.getEtiqueta11() != null
						&& castOther.getEtiqueta11() != null && this
						.getEtiqueta11().equals(castOther.getEtiqueta11())))
				&& ((this.getEtiqueta12() == castOther.getEtiqueta12()) || (this
						.getEtiqueta12() != null
						&& castOther.getEtiqueta12() != null && this
						.getEtiqueta12().equals(castOther.getEtiqueta12())))
				&& ((this.getEtiqueta13() == castOther.getEtiqueta13()) || (this
						.getEtiqueta13() != null
						&& castOther.getEtiqueta13() != null && this
						.getEtiqueta13().equals(castOther.getEtiqueta13())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOb3id() == null ? 0 : this.getOb3id().hashCode());
		result = 37 * result
				+ (getEanOUpc() == null ? 0 : this.getEanOUpc().hashCode());
		result = 37 * result
				+ (getDun14() == null ? 0 : this.getDun14().hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		result = 37
				* result
				+ (getDescripcion2() == null ? 0 : this.getDescripcion2()
						.hashCode());
		result = 37 * result
				+ (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		result = 37
				* result
				+ (getUnidadDeMedida() == null ? 0 : this.getUnidadDeMedida()
						.hashCode());
		result = 37
				* result
				+ (getCantEmpaque() == null ? 0 : this.getCantEmpaque()
						.hashCode());
		result = 37 * result
				+ (getPrecio() == null ? 0 : this.getPrecio().hashCode());
		result = 37
				* result
				+ (getPorcenDesc1() == null ? 0 : this.getPorcenDesc1()
						.hashCode());
		result = 37
				* result
				+ (getTipoDescuento1() == null ? 0 : this.getTipoDescuento1()
						.hashCode());
		result = 37
				* result
				+ (getMontoDeDescuento1() == null ? 0 : this
						.getMontoDeDescuento1().hashCode());
		result = 37
				* result
				+ (getPorcenDescuento2() == null ? 0 : this
						.getPorcenDescuento2().hashCode());
		result = 37
				* result
				+ (getTipoDescuento2() == null ? 0 : this.getTipoDescuento2()
						.hashCode());
		result = 37
				* result
				+ (getMontoDeDescuento2() == null ? 0 : this
						.getMontoDeDescuento2().hashCode());
		result = 37
				* result
				+ (getPorcenDescuento3() == null ? 0 : this
						.getPorcenDescuento3().hashCode());
		result = 37
				* result
				+ (getTipoDescuento3() == null ? 0 : this.getTipoDescuento3()
						.hashCode());
		result = 37
				* result
				+ (getMontoDeDescuento3() == null ? 0 : this
						.getMontoDeDescuento3().hashCode());
		result = 37
				* result
				+ (getPorcenDescuento4() == null ? 0 : this
						.getPorcenDescuento4().hashCode());
		result = 37
				* result
				+ (getTipoDescuento4() == null ? 0 : this.getTipoDescuento4()
						.hashCode());
		result = 37
				* result
				+ (getMontoDeDescuento4() == null ? 0 : this
						.getMontoDeDescuento4().hashCode());
		result = 37
				* result
				+ (getPorcenDescuento5() == null ? 0 : this
						.getPorcenDescuento5().hashCode());
		result = 37
				* result
				+ (getTipoDescuento5() == null ? 0 : this.getTipoDescuento5()
						.hashCode());
		result = 37
				* result
				+ (getMontoDeDescuento5() == null ? 0 : this
						.getMontoDeDescuento5().hashCode());
		result = 37
				* result
				+ (getPrecioNeto() == null ? 0 : this.getPrecioNeto()
						.hashCode());
		result = 37 * result
				+ (getPorcenIva() == null ? 0 : this.getPorcenIva().hashCode());
		result = 37
				* result
				+ (getPorcenIeps() == null ? 0 : this.getPorcenIeps()
						.hashCode());
		result = 37
				* result
				+ (getCantEmbarcada() == null ? 0 : this.getCantEmbarcada()
						.hashCode());
		result = 37 * result
				+ (getAduana() == null ? 0 : this.getAduana().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37
				* result
				+ (getNumeroPedimento() == null ? 0 : this.getNumeroPedimento()
						.hashCode());
		result = 37
				* result
				+ (getNumeroInternoDePr1() == null ? 0 : this
						.getNumeroInternoDePr1().hashCode());
		result = 37
				* result
				+ (getNumeroInternoDePr2() == null ? 0 : this
						.getNumeroInternoDePr2().hashCode());
		result = 37
				* result
				+ (getCantidadGratisDeM() == null ? 0 : this
						.getCantidadGratisDeM().hashCode());
		result = 37
				* result
				+ (getTipoDeEmpaque() == null ? 0 : this.getTipoDeEmpaque()
						.hashCode());
		result = 37
				* result
				+ (getPagoDeEmpaque() == null ? 0 : this.getPagoDeEmpaque()
						.hashCode());
		result = 37
				* result
				+ (getCostoTotalPrecio() == null ? 0 : this
						.getCostoTotalPrecio().hashCode());
		result = 37
				* result
				+ (getImporteConDescuen() == null ? 0 : this
						.getImporteConDescuen().hashCode());
		result = 37
				* result
				+ (getMontoDeIva() == null ? 0 : this.getMontoDeIva()
						.hashCode());
		result = 37
				* result
				+ (getMontoDeIeps() == null ? 0 : this.getMontoDeIeps()
						.hashCode());
		result = 37 * result
				+ (getPorcenIsr() == null ? 0 : this.getPorcenIsr().hashCode());
		result = 37 * result
				+ (getMontoIsr() == null ? 0 : this.getMontoIsr().hashCode());
		result = 37
				* result
				+ (getPorcenImpuestoDePetrol() == null ? 0 : this
						.getPorcenImpuestoDePetrol().hashCode());
		result = 37
				* result
				+ (getMontoImpuestoDePe() == null ? 0 : this
						.getMontoImpuestoDePe().hashCode());
		result = 37
				* result
				+ (getPorcenExento() == null ? 0 : this.getPorcenExento()
						.hashCode());
		result = 37
				* result
				+ (getMontoExento() == null ? 0 : this.getMontoExento()
						.hashCode());
		result = 37
				* result
				+ (getPorcenEstatal() == null ? 0 : this.getPorcenEstatal()
						.hashCode());
		result = 37
				* result
				+ (getMontoEstatal() == null ? 0 : this.getMontoEstatal()
						.hashCode());
		result = 37
				* result
				+ (getPorcenCedular() == null ? 0 : this.getPorcenCedular()
						.hashCode());
		result = 37
				* result
				+ (getMontoCedular() == null ? 0 : this.getMontoCedular()
						.hashCode());
		result = 37
				* result
				+ (getPorcenMunicipal() == null ? 0 : this.getPorcenMunicipal()
						.hashCode());
		result = 37
				* result
				+ (getMontoMunicipal() == null ? 0 : this.getMontoMunicipal()
						.hashCode());
		result = 37
				* result
				+ (getPorcenHospedaje() == null ? 0 : this.getPorcenHospedaje()
						.hashCode());
		result = 37
				* result
				+ (getMontoHospedaje() == null ? 0 : this.getMontoHospedaje()
						.hashCode());
		result = 37
				* result
				+ (getPorcenOtrosImpuestos() == null ? 0 : this
						.getPorcenOtrosImpuestos().hashCode());
		result = 37
				* result
				+ (getMontoOtrosImpuesto() == null ? 0 : this
						.getMontoOtrosImpuesto().hashCode());
		result = 37
				* result
				+ (getOrdenDeCompra() == null ? 0 : this.getOrdenDeCompra()
						.hashCode());
		result = 37
				* result
				+ (getNumeroDeCuentaPre() == null ? 0 : this
						.getNumeroDeCuentaPre().hashCode());
		result = 37
				* result
				+ (getCantidadRealDeKil() == null ? 0 : this
						.getCantidadRealDeKil().hashCode());
		result = 37
				* result
				+ (getCantidadMinimaASurtir() == null ? 0 : this
						.getCantidadMinimaASurtir().hashCode());
		result = 37 * result
				+ (getEtiqueta1() == null ? 0 : this.getEtiqueta1().hashCode());
		result = 37 * result
				+ (getEtiqueta2() == null ? 0 : this.getEtiqueta2().hashCode());
		result = 37 * result
				+ (getEtiqueta3() == null ? 0 : this.getEtiqueta3().hashCode());
		result = 37 * result
				+ (getEtiqueta4() == null ? 0 : this.getEtiqueta4().hashCode());
		result = 37 * result
				+ (getEtiqueta5() == null ? 0 : this.getEtiqueta5().hashCode());
		result = 37 * result
				+ (getEtiqueta6() == null ? 0 : this.getEtiqueta6().hashCode());
		result = 37 * result
				+ (getEtiqueta7() == null ? 0 : this.getEtiqueta7().hashCode());
		result = 37 * result
				+ (getEtiqueta8() == null ? 0 : this.getEtiqueta8().hashCode());
		result = 37 * result
				+ (getEtiqueta9() == null ? 0 : this.getEtiqueta9().hashCode());
		result = 37
				* result
				+ (getEtiqueta10() == null ? 0 : this.getEtiqueta10()
						.hashCode());
		result = 37
				* result
				+ (getEtiqueta11() == null ? 0 : this.getEtiqueta11()
						.hashCode());
		result = 37
				* result
				+ (getEtiqueta12() == null ? 0 : this.getEtiqueta12()
						.hashCode());
		result = 37
				* result
				+ (getEtiqueta13() == null ? 0 : this.getEtiqueta13()
						.hashCode());
		return result;
	}

}
