package mx.redts.adendas.model;

// Generated 22-may-2014 23:59:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FeDetalle generated by hbm2java
 */
@Entity
@Table(name = "fe_detalle", schema = "public")
public class FeDetalle implements java.io.Serializable {

	private FeDetalleId id;

	public FeDetalle() {
	}

	public FeDetalle(FeDetalleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ob3id", column = @Column(name = "ob3id", nullable = false, length = 32)),
			@AttributeOverride(name = "eanOUpc", column = @Column(name = "ean_o_upc", nullable = false, length = 15)),
			@AttributeOverride(name = "dun14", column = @Column(name = "dun_14", length = 14)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", nullable = false, length = 100)),
			@AttributeOverride(name = "descripcion2", column = @Column(name = "descripcion2", length = 100)),
			@AttributeOverride(name = "cantidad", column = @Column(name = "cantidad", nullable = false, length = 10)),
			@AttributeOverride(name = "unidadDeMedida", column = @Column(name = "unidad_de_medida", nullable = false, length = 10)),
			@AttributeOverride(name = "cantEmpaque", column = @Column(name = "cant_empaque", length = 5)),
			@AttributeOverride(name = "precio", column = @Column(name = "precio", nullable = false, length = 20)),
			@AttributeOverride(name = "porcenDesc1", column = @Column(name = "porcen_desc_1", length = 3)),
			@AttributeOverride(name = "tipoDescuento1", column = @Column(name = "tipo_descuento_1", length = 5)),
			@AttributeOverride(name = "montoDeDescuento1", column = @Column(name = "monto_de_descuento_1", length = 20)),
			@AttributeOverride(name = "porcenDescuento2", column = @Column(name = "porcen_descuento_2", length = 3)),
			@AttributeOverride(name = "tipoDescuento2", column = @Column(name = "tipo_descuento_2", length = 5)),
			@AttributeOverride(name = "montoDeDescuento2", column = @Column(name = "monto_de_descuento_2", length = 20)),
			@AttributeOverride(name = "porcenDescuento3", column = @Column(name = "porcen_descuento_3", length = 3)),
			@AttributeOverride(name = "tipoDescuento3", column = @Column(name = "tipo_descuento_3", length = 5)),
			@AttributeOverride(name = "montoDeDescuento3", column = @Column(name = "monto_de_descuento_3", length = 20)),
			@AttributeOverride(name = "porcenDescuento4", column = @Column(name = "porcen_descuento_4", length = 3)),
			@AttributeOverride(name = "tipoDescuento4", column = @Column(name = "tipo_descuento_4", length = 5)),
			@AttributeOverride(name = "montoDeDescuento4", column = @Column(name = "monto_de_descuento_4", length = 20)),
			@AttributeOverride(name = "porcenDescuento5", column = @Column(name = "porcen_descuento_5", length = 3)),
			@AttributeOverride(name = "tipoDescuento5", column = @Column(name = "tipo_descuento_5", length = 5)),
			@AttributeOverride(name = "montoDeDescuento5", column = @Column(name = "monto_de_descuento_5", length = 20)),
			@AttributeOverride(name = "precioNeto", column = @Column(name = "precio_neto", nullable = false, length = 20)),
			@AttributeOverride(name = "porcenIva", column = @Column(name = "porcen_iva", nullable = false, length = 3)),
			@AttributeOverride(name = "porcenIeps", column = @Column(name = "porcen_ieps", length = 3)),
			@AttributeOverride(name = "cantEmbarcada", column = @Column(name = "cant_embarcada", length = 5)),
			@AttributeOverride(name = "aduana", column = @Column(name = "aduana", length = 10)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 10)),
			@AttributeOverride(name = "numeroPedimento", column = @Column(name = "numero_pedimento", length = 8)),
			@AttributeOverride(name = "numeroInternoDePr1", column = @Column(name = "numero_interno_de_pr1", length = 8)),
			@AttributeOverride(name = "numeroInternoDePr2", column = @Column(name = "numero_interno_de_pr2", length = 8)),
			@AttributeOverride(name = "cantidadGratisDeM", column = @Column(name = "cantidad_gratis_de_m", length = 5)),
			@AttributeOverride(name = "tipoDeEmpaque", column = @Column(name = "tipo_de_empaque", length = 5)),
			@AttributeOverride(name = "pagoDeEmpaque", column = @Column(name = "pago_de_empaque", length = 10)),
			@AttributeOverride(name = "costoTotalPrecio", column = @Column(name = "costo_total_precio", nullable = false, length = 20)),
			@AttributeOverride(name = "importeConDescuen", column = @Column(name = "importe_con_descuen", length = 20)),
			@AttributeOverride(name = "montoDeIva", column = @Column(name = "monto_de_iva", nullable = false, length = 20)),
			@AttributeOverride(name = "montoDeIeps", column = @Column(name = "monto_de_ieps", length = 20)),
			@AttributeOverride(name = "porcenIsr", column = @Column(name = "porcen_isr", length = 3)),
			@AttributeOverride(name = "montoIsr", column = @Column(name = "monto_isr", length = 20)),
			@AttributeOverride(name = "porcenImpuestoDePetrol", column = @Column(name = "porcen_impuesto_de_petrol", length = 3)),
			@AttributeOverride(name = "montoImpuestoDePe", column = @Column(name = "monto_impuesto_de_pe", length = 20)),
			@AttributeOverride(name = "porcenExento", column = @Column(name = "porcen_exento", length = 3)),
			@AttributeOverride(name = "montoExento", column = @Column(name = "monto_exento", length = 20)),
			@AttributeOverride(name = "porcenEstatal", column = @Column(name = "porcen_estatal", length = 3)),
			@AttributeOverride(name = "montoEstatal", column = @Column(name = "monto_estatal", length = 20)),
			@AttributeOverride(name = "porcenCedular", column = @Column(name = "porcen_cedular", length = 3)),
			@AttributeOverride(name = "montoCedular", column = @Column(name = "monto_cedular", length = 20)),
			@AttributeOverride(name = "porcenMunicipal", column = @Column(name = "porcen_municipal", length = 3)),
			@AttributeOverride(name = "montoMunicipal", column = @Column(name = "monto_municipal", length = 20)),
			@AttributeOverride(name = "porcenHospedaje", column = @Column(name = "porcen_hospedaje", length = 3)),
			@AttributeOverride(name = "montoHospedaje", column = @Column(name = "monto_hospedaje", length = 20)),
			@AttributeOverride(name = "porcenOtrosImpuestos", column = @Column(name = "porcen_otros_impuestos", length = 3)),
			@AttributeOverride(name = "montoOtrosImpuesto", column = @Column(name = "monto_otros_impuesto", length = 20)),
			@AttributeOverride(name = "ordenDeCompra", column = @Column(name = "orden_de_compra", length = 3)),
			@AttributeOverride(name = "numeroDeCuentaPre", column = @Column(name = "numero_de_cuenta_pre", length = 20)),
			@AttributeOverride(name = "cantidadRealDeKil", column = @Column(name = "cantidad_real_de_kil", length = 10)),
			@AttributeOverride(name = "cantidadMinimaASurtir", column = @Column(name = "cantidad_minima_a_surtir", length = 10)),
			@AttributeOverride(name = "etiqueta1", column = @Column(name = "etiqueta_1", length = 100)),
			@AttributeOverride(name = "etiqueta2", column = @Column(name = "etiqueta_2", length = 100)),
			@AttributeOverride(name = "etiqueta3", column = @Column(name = "etiqueta_3", length = 100)),
			@AttributeOverride(name = "etiqueta4", column = @Column(name = "etiqueta_4", length = 100)),
			@AttributeOverride(name = "etiqueta5", column = @Column(name = "etiqueta_5", length = 100)),
			@AttributeOverride(name = "etiqueta6", column = @Column(name = "etiqueta_6", length = 100)),
			@AttributeOverride(name = "etiqueta7", column = @Column(name = "etiqueta_7", length = 100)),
			@AttributeOverride(name = "etiqueta8", column = @Column(name = "etiqueta_8", length = 100)),
			@AttributeOverride(name = "etiqueta9", column = @Column(name = "etiqueta_9", length = 100)),
			@AttributeOverride(name = "etiqueta10", column = @Column(name = "etiqueta_10", length = 100)),
			@AttributeOverride(name = "etiqueta11", column = @Column(name = "etiqueta_11", length = 100)),
			@AttributeOverride(name = "etiqueta12", column = @Column(name = "etiqueta_12", length = 100)),
			@AttributeOverride(name = "etiqueta13", column = @Column(name = "etiqueta_13", length = 100)) })
	public FeDetalleId getId() {
		return this.id;
	}

	public void setId(FeDetalleId id) {
		this.id = id;
	}

}
