package mx.redts.adendas.model;

// Generated 22-may-2014 23:59:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeEncabezado generated by hbm2java
 */
@Entity
@Table(name = "fe_encabezado", schema = "public")
public class FeEncabezado implements java.io.Serializable {

	private String ob3id;
	private String serie;
	private String folio;
	private String noAprobacion;
	private String fechaCfd;
	private String referenciaDeDocume;
	private String fechaReferenciaDe;
	private String formaDePago;
	private String diasDePago;
	private String funcion;
	private String tipoDeDocumento;
	private String porcenDescuento1;
	private String tipoDescuento1;
	private String montoDeDescuento1;
	private String porcenDescuento2;
	private String tipoDescuento2;
	private String montoDeDescuento2;
	private String porcenDescuento3;
	private String tipoDescuento3;
	private String montoDeDescuento3;
	private String anioAprobacion;
	private String numeroInterno;
	private String areaInterna;
	private String representanteLegal;
	private String noProveedor;
	private String tasaGlobalDeIva;
	private String numeroDeTienda;
	private String frm;
	private String fechaDeFrm;
	private String lugarDeExpedicion;
	private String metodoDePago;
	private String moneda;
	private String tipoDeCambio;
	private String fechaDeEntregaAct;
	private String contactoDeCompras;
	private String departamentoDelCon;
	private String observaciones1come;
	private String observaciones2come;
	private String observaciones3come;
	private String observaciones4come;
	private String observaciones5come;
	private String noAvisoAnticipado;
	private String fechaAvisoAnticipa;
	private String importeConLetra;
	private String tipoImpresion;
	private String tipoDeEnvio;
	private String codigoIeps;
	private String etiqueta1;
	private String etiqueta2;
	private String etiqueta3;
	private String etiqueta4;
	private String etiqueta5;
	private String etiqueta6;

	public FeEncabezado() {
	}

	public FeEncabezado(String ob3id, String fechaCfd, String formaDePago,
			String funcion, String tipoDeDocumento, String tasaGlobalDeIva,
			String lugarDeExpedicion, String metodoDePago,
			String importeConLetra) {
		this.ob3id = ob3id;
		this.fechaCfd = fechaCfd;
		this.formaDePago = formaDePago;
		this.funcion = funcion;
		this.tipoDeDocumento = tipoDeDocumento;
		this.tasaGlobalDeIva = tasaGlobalDeIva;
		this.lugarDeExpedicion = lugarDeExpedicion;
		this.metodoDePago = metodoDePago;
		this.importeConLetra = importeConLetra;
	}

	public FeEncabezado(String ob3id, String serie, String folio,
			String noAprobacion, String fechaCfd, String referenciaDeDocume,
			String fechaReferenciaDe, String formaDePago, String diasDePago,
			String funcion, String tipoDeDocumento, String porcenDescuento1,
			String tipoDescuento1, String montoDeDescuento1,
			String porcenDescuento2, String tipoDescuento2,
			String montoDeDescuento2, String porcenDescuento3,
			String tipoDescuento3, String montoDeDescuento3,
			String anioAprobacion, String numeroInterno, String areaInterna,
			String representanteLegal, String noProveedor,
			String tasaGlobalDeIva, String numeroDeTienda, String frm,
			String fechaDeFrm, String lugarDeExpedicion, String metodoDePago,
			String moneda, String tipoDeCambio, String fechaDeEntregaAct,
			String contactoDeCompras, String departamentoDelCon,
			String observaciones1come, String observaciones2come,
			String observaciones3come, String observaciones4come,
			String observaciones5come, String noAvisoAnticipado,
			String fechaAvisoAnticipa, String importeConLetra,
			String tipoImpresion, String tipoDeEnvio, String codigoIeps,
			String etiqueta1, String etiqueta2, String etiqueta3,
			String etiqueta4, String etiqueta5, String etiqueta6) {
		this.ob3id = ob3id;
		this.serie = serie;
		this.folio = folio;
		this.noAprobacion = noAprobacion;
		this.fechaCfd = fechaCfd;
		this.referenciaDeDocume = referenciaDeDocume;
		this.fechaReferenciaDe = fechaReferenciaDe;
		this.formaDePago = formaDePago;
		this.diasDePago = diasDePago;
		this.funcion = funcion;
		this.tipoDeDocumento = tipoDeDocumento;
		this.porcenDescuento1 = porcenDescuento1;
		this.tipoDescuento1 = tipoDescuento1;
		this.montoDeDescuento1 = montoDeDescuento1;
		this.porcenDescuento2 = porcenDescuento2;
		this.tipoDescuento2 = tipoDescuento2;
		this.montoDeDescuento2 = montoDeDescuento2;
		this.porcenDescuento3 = porcenDescuento3;
		this.tipoDescuento3 = tipoDescuento3;
		this.montoDeDescuento3 = montoDeDescuento3;
		this.anioAprobacion = anioAprobacion;
		this.numeroInterno = numeroInterno;
		this.areaInterna = areaInterna;
		this.representanteLegal = representanteLegal;
		this.noProveedor = noProveedor;
		this.tasaGlobalDeIva = tasaGlobalDeIva;
		this.numeroDeTienda = numeroDeTienda;
		this.frm = frm;
		this.fechaDeFrm = fechaDeFrm;
		this.lugarDeExpedicion = lugarDeExpedicion;
		this.metodoDePago = metodoDePago;
		this.moneda = moneda;
		this.tipoDeCambio = tipoDeCambio;
		this.fechaDeEntregaAct = fechaDeEntregaAct;
		this.contactoDeCompras = contactoDeCompras;
		this.departamentoDelCon = departamentoDelCon;
		this.observaciones1come = observaciones1come;
		this.observaciones2come = observaciones2come;
		this.observaciones3come = observaciones3come;
		this.observaciones4come = observaciones4come;
		this.observaciones5come = observaciones5come;
		this.noAvisoAnticipado = noAvisoAnticipado;
		this.fechaAvisoAnticipa = fechaAvisoAnticipa;
		this.importeConLetra = importeConLetra;
		this.tipoImpresion = tipoImpresion;
		this.tipoDeEnvio = tipoDeEnvio;
		this.codigoIeps = codigoIeps;
		this.etiqueta1 = etiqueta1;
		this.etiqueta2 = etiqueta2;
		this.etiqueta3 = etiqueta3;
		this.etiqueta4 = etiqueta4;
		this.etiqueta5 = etiqueta5;
		this.etiqueta6 = etiqueta6;
	}

	@Id
	@Column(name = "ob3id", unique = true, nullable = false, length = 32)
	public String getOb3id() {
		return this.ob3id;
	}

	public void setOb3id(String ob3id) {
		this.ob3id = ob3id;
	}

	@Column(name = "serie", length = 30)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "folio", length = 30)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	@Column(name = "no_aprobacion", length = 30)
	public String getNoAprobacion() {
		return this.noAprobacion;
	}

	public void setNoAprobacion(String noAprobacion) {
		this.noAprobacion = noAprobacion;
	}

	@Column(name = "fecha_cfd", nullable = false, length = 10)
	public String getFechaCfd() {
		return this.fechaCfd;
	}

	public void setFechaCfd(String fechaCfd) {
		this.fechaCfd = fechaCfd;
	}

	@Column(name = "referencia_de_docume", length = 30)
	public String getReferenciaDeDocume() {
		return this.referenciaDeDocume;
	}

	public void setReferenciaDeDocume(String referenciaDeDocume) {
		this.referenciaDeDocume = referenciaDeDocume;
	}

	@Column(name = "fecha_referencia_de", length = 10)
	public String getFechaReferenciaDe() {
		return this.fechaReferenciaDe;
	}

	public void setFechaReferenciaDe(String fechaReferenciaDe) {
		this.fechaReferenciaDe = fechaReferenciaDe;
	}

	@Column(name = "forma_de_pago", nullable = false, length = 50)
	public String getFormaDePago() {
		return this.formaDePago;
	}

	public void setFormaDePago(String formaDePago) {
		this.formaDePago = formaDePago;
	}

	@Column(name = "dias_de_pago", length = 50)
	public String getDiasDePago() {
		return this.diasDePago;
	}

	public void setDiasDePago(String diasDePago) {
		this.diasDePago = diasDePago;
	}

	@Column(name = "funcion", nullable = false, length = 50)
	public String getFuncion() {
		return this.funcion;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

	@Column(name = "tipo_de_documento", nullable = false, length = 50)
	public String getTipoDeDocumento() {
		return this.tipoDeDocumento;
	}

	public void setTipoDeDocumento(String tipoDeDocumento) {
		this.tipoDeDocumento = tipoDeDocumento;
	}

	@Column(name = "porcen_descuento_1", length = 20)
	public String getPorcenDescuento1() {
		return this.porcenDescuento1;
	}

	public void setPorcenDescuento1(String porcenDescuento1) {
		this.porcenDescuento1 = porcenDescuento1;
	}

	@Column(name = "tipo_descuento_1", length = 30)
	public String getTipoDescuento1() {
		return this.tipoDescuento1;
	}

	public void setTipoDescuento1(String tipoDescuento1) {
		this.tipoDescuento1 = tipoDescuento1;
	}

	@Column(name = "monto_de_descuento1", length = 20)
	public String getMontoDeDescuento1() {
		return this.montoDeDescuento1;
	}

	public void setMontoDeDescuento1(String montoDeDescuento1) {
		this.montoDeDescuento1 = montoDeDescuento1;
	}

	@Column(name = "porcen_descuento_2", length = 20)
	public String getPorcenDescuento2() {
		return this.porcenDescuento2;
	}

	public void setPorcenDescuento2(String porcenDescuento2) {
		this.porcenDescuento2 = porcenDescuento2;
	}

	@Column(name = "tipo_descuento_2", length = 30)
	public String getTipoDescuento2() {
		return this.tipoDescuento2;
	}

	public void setTipoDescuento2(String tipoDescuento2) {
		this.tipoDescuento2 = tipoDescuento2;
	}

	@Column(name = "monto_de_descuento_2", length = 20)
	public String getMontoDeDescuento2() {
		return this.montoDeDescuento2;
	}

	public void setMontoDeDescuento2(String montoDeDescuento2) {
		this.montoDeDescuento2 = montoDeDescuento2;
	}

	@Column(name = "porcen_descuento_3", length = 20)
	public String getPorcenDescuento3() {
		return this.porcenDescuento3;
	}

	public void setPorcenDescuento3(String porcenDescuento3) {
		this.porcenDescuento3 = porcenDescuento3;
	}

	@Column(name = "tipo_descuento_3", length = 30)
	public String getTipoDescuento3() {
		return this.tipoDescuento3;
	}

	public void setTipoDescuento3(String tipoDescuento3) {
		this.tipoDescuento3 = tipoDescuento3;
	}

	@Column(name = "monto_de_descuento_3", length = 20)
	public String getMontoDeDescuento3() {
		return this.montoDeDescuento3;
	}

	public void setMontoDeDescuento3(String montoDeDescuento3) {
		this.montoDeDescuento3 = montoDeDescuento3;
	}

	@Column(name = "anio_aprobacion", length = 5)
	public String getAnioAprobacion() {
		return this.anioAprobacion;
	}

	public void setAnioAprobacion(String anioAprobacion) {
		this.anioAprobacion = anioAprobacion;
	}

	@Column(name = "numero_interno", length = 10)
	public String getNumeroInterno() {
		return this.numeroInterno;
	}

	public void setNumeroInterno(String numeroInterno) {
		this.numeroInterno = numeroInterno;
	}

	@Column(name = "area_interna", length = 30)
	public String getAreaInterna() {
		return this.areaInterna;
	}

	public void setAreaInterna(String areaInterna) {
		this.areaInterna = areaInterna;
	}

	@Column(name = "representante_legal", length = 100)
	public String getRepresentanteLegal() {
		return this.representanteLegal;
	}

	public void setRepresentanteLegal(String representanteLegal) {
		this.representanteLegal = representanteLegal;
	}

	@Column(name = "no_proveedor", length = 10)
	public String getNoProveedor() {
		return this.noProveedor;
	}

	public void setNoProveedor(String noProveedor) {
		this.noProveedor = noProveedor;
	}

	@Column(name = "tasa_global_de_iva", nullable = false, length = 10)
	public String getTasaGlobalDeIva() {
		return this.tasaGlobalDeIva;
	}

	public void setTasaGlobalDeIva(String tasaGlobalDeIva) {
		this.tasaGlobalDeIva = tasaGlobalDeIva;
	}

	@Column(name = "numero_de_tienda", length = 10)
	public String getNumeroDeTienda() {
		return this.numeroDeTienda;
	}

	public void setNumeroDeTienda(String numeroDeTienda) {
		this.numeroDeTienda = numeroDeTienda;
	}

	@Column(name = "frm", length = 30)
	public String getFrm() {
		return this.frm;
	}

	public void setFrm(String frm) {
		this.frm = frm;
	}

	@Column(name = "fecha_de_frm", length = 10)
	public String getFechaDeFrm() {
		return this.fechaDeFrm;
	}

	public void setFechaDeFrm(String fechaDeFrm) {
		this.fechaDeFrm = fechaDeFrm;
	}

	@Column(name = "lugar_de_expedicion", nullable = false, length = 50)
	public String getLugarDeExpedicion() {
		return this.lugarDeExpedicion;
	}

	public void setLugarDeExpedicion(String lugarDeExpedicion) {
		this.lugarDeExpedicion = lugarDeExpedicion;
	}

	@Column(name = "metodo_de_pago", nullable = false, length = 50)
	public String getMetodoDePago() {
		return this.metodoDePago;
	}

	public void setMetodoDePago(String metodoDePago) {
		this.metodoDePago = metodoDePago;
	}

	@Column(name = "moneda", length = 5)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "tipo_de_cambio", length = 20)
	public String getTipoDeCambio() {
		return this.tipoDeCambio;
	}

	public void setTipoDeCambio(String tipoDeCambio) {
		this.tipoDeCambio = tipoDeCambio;
	}

	@Column(name = "fecha_de_entrega_act", length = 10)
	public String getFechaDeEntregaAct() {
		return this.fechaDeEntregaAct;
	}

	public void setFechaDeEntregaAct(String fechaDeEntregaAct) {
		this.fechaDeEntregaAct = fechaDeEntregaAct;
	}

	@Column(name = "contacto_de_compras", length = 100)
	public String getContactoDeCompras() {
		return this.contactoDeCompras;
	}

	public void setContactoDeCompras(String contactoDeCompras) {
		this.contactoDeCompras = contactoDeCompras;
	}

	@Column(name = "departamento_del_con", length = 100)
	public String getDepartamentoDelCon() {
		return this.departamentoDelCon;
	}

	public void setDepartamentoDelCon(String departamentoDelCon) {
		this.departamentoDelCon = departamentoDelCon;
	}

	@Column(name = "observaciones_1come", length = 250)
	public String getObservaciones1come() {
		return this.observaciones1come;
	}

	public void setObservaciones1come(String observaciones1come) {
		this.observaciones1come = observaciones1come;
	}

	@Column(name = "observaciones_2come", length = 250)
	public String getObservaciones2come() {
		return this.observaciones2come;
	}

	public void setObservaciones2come(String observaciones2come) {
		this.observaciones2come = observaciones2come;
	}

	@Column(name = "observaciones_3come", length = 250)
	public String getObservaciones3come() {
		return this.observaciones3come;
	}

	public void setObservaciones3come(String observaciones3come) {
		this.observaciones3come = observaciones3come;
	}

	@Column(name = "observaciones_4come", length = 250)
	public String getObservaciones4come() {
		return this.observaciones4come;
	}

	public void setObservaciones4come(String observaciones4come) {
		this.observaciones4come = observaciones4come;
	}

	@Column(name = "observaciones_5come", length = 250)
	public String getObservaciones5come() {
		return this.observaciones5come;
	}

	public void setObservaciones5come(String observaciones5come) {
		this.observaciones5come = observaciones5come;
	}

	@Column(name = "no_aviso_anticipado", length = 20)
	public String getNoAvisoAnticipado() {
		return this.noAvisoAnticipado;
	}

	public void setNoAvisoAnticipado(String noAvisoAnticipado) {
		this.noAvisoAnticipado = noAvisoAnticipado;
	}

	@Column(name = "fecha_aviso_anticipa", length = 10)
	public String getFechaAvisoAnticipa() {
		return this.fechaAvisoAnticipa;
	}

	public void setFechaAvisoAnticipa(String fechaAvisoAnticipa) {
		this.fechaAvisoAnticipa = fechaAvisoAnticipa;
	}

	@Column(name = "importe_con_letra", nullable = false, length = 20)
	public String getImporteConLetra() {
		return this.importeConLetra;
	}

	public void setImporteConLetra(String importeConLetra) {
		this.importeConLetra = importeConLetra;
	}

	@Column(name = "tipo_impresion", length = 10)
	public String getTipoImpresion() {
		return this.tipoImpresion;
	}

	public void setTipoImpresion(String tipoImpresion) {
		this.tipoImpresion = tipoImpresion;
	}

	@Column(name = "tipo_de_envio", length = 10)
	public String getTipoDeEnvio() {
		return this.tipoDeEnvio;
	}

	public void setTipoDeEnvio(String tipoDeEnvio) {
		this.tipoDeEnvio = tipoDeEnvio;
	}

	@Column(name = "codigo_ieps", length = 20)
	public String getCodigoIeps() {
		return this.codigoIeps;
	}

	public void setCodigoIeps(String codigoIeps) {
		this.codigoIeps = codigoIeps;
	}

	@Column(name = "etiqueta_1", length = 100)
	public String getEtiqueta1() {
		return this.etiqueta1;
	}

	public void setEtiqueta1(String etiqueta1) {
		this.etiqueta1 = etiqueta1;
	}

	@Column(name = "etiqueta_2", length = 100)
	public String getEtiqueta2() {
		return this.etiqueta2;
	}

	public void setEtiqueta2(String etiqueta2) {
		this.etiqueta2 = etiqueta2;
	}

	@Column(name = "etiqueta_3", length = 100)
	public String getEtiqueta3() {
		return this.etiqueta3;
	}

	public void setEtiqueta3(String etiqueta3) {
		this.etiqueta3 = etiqueta3;
	}

	@Column(name = "etiqueta_4", length = 100)
	public String getEtiqueta4() {
		return this.etiqueta4;
	}

	public void setEtiqueta4(String etiqueta4) {
		this.etiqueta4 = etiqueta4;
	}

	@Column(name = "etiqueta_5", length = 100)
	public String getEtiqueta5() {
		return this.etiqueta5;
	}

	public void setEtiqueta5(String etiqueta5) {
		this.etiqueta5 = etiqueta5;
	}

	@Column(name = "etiqueta_6", length = 100)
	public String getEtiqueta6() {
		return this.etiqueta6;
	}

	public void setEtiqueta6(String etiqueta6) {
		this.etiqueta6 = etiqueta6;
	}

}
