package mx.redts.adendas.model;

// Generated 22-may-2014 23:59:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeExpedidoEn generated by hbm2java
 */
@Entity
@Table(name = "fe_expedido_en", schema = "public")
public class FeExpedidoEn implements java.io.Serializable {

	private String ob3id;
	private String nombreReceptor;
	private String rfc;
	private String gln;
	private String calle;
	private String noExterior;
	private String noInterior;
	private String colonia;
	private String localidad;
	private String referencia;
	private String municipio;
	private String estado;
	private String pais;
	private String cp;
	private String imss;
	private String telefono;
	private String etiqueta1;
	private String etiqueta2;
	private String etiqueta3;
	private String etiqueta4;
	private String etiqueta5;
	private String etiqueta6;
	private String etiqueta7;
	private String etiqueta8;
	private String etiqueta9;
	private String etiqueta10;

	public FeExpedidoEn() {
	}

	public FeExpedidoEn(String ob3id) {
		this.ob3id = ob3id;
	}

	public FeExpedidoEn(String ob3id, String nombreReceptor, String rfc,
			String gln, String calle, String noExterior, String noInterior,
			String colonia, String localidad, String referencia,
			String municipio, String estado, String pais, String cp,
			String imss, String telefono, String etiqueta1, String etiqueta2,
			String etiqueta3, String etiqueta4, String etiqueta5,
			String etiqueta6, String etiqueta7, String etiqueta8,
			String etiqueta9, String etiqueta10) {
		this.ob3id = ob3id;
		this.nombreReceptor = nombreReceptor;
		this.rfc = rfc;
		this.gln = gln;
		this.calle = calle;
		this.noExterior = noExterior;
		this.noInterior = noInterior;
		this.colonia = colonia;
		this.localidad = localidad;
		this.referencia = referencia;
		this.municipio = municipio;
		this.estado = estado;
		this.pais = pais;
		this.cp = cp;
		this.imss = imss;
		this.telefono = telefono;
		this.etiqueta1 = etiqueta1;
		this.etiqueta2 = etiqueta2;
		this.etiqueta3 = etiqueta3;
		this.etiqueta4 = etiqueta4;
		this.etiqueta5 = etiqueta5;
		this.etiqueta6 = etiqueta6;
		this.etiqueta7 = etiqueta7;
		this.etiqueta8 = etiqueta8;
		this.etiqueta9 = etiqueta9;
		this.etiqueta10 = etiqueta10;
	}

	@Id
	@Column(name = "ob3id", unique = true, nullable = false, length = 32)
	public String getOb3id() {
		return this.ob3id;
	}

	public void setOb3id(String ob3id) {
		this.ob3id = ob3id;
	}

	@Column(name = "nombre_receptor", length = 100)
	public String getNombreReceptor() {
		return this.nombreReceptor;
	}

	public void setNombreReceptor(String nombreReceptor) {
		this.nombreReceptor = nombreReceptor;
	}

	@Column(name = "rfc", length = 15)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "gln", length = 20)
	public String getGln() {
		return this.gln;
	}

	public void setGln(String gln) {
		this.gln = gln;
	}

	@Column(name = "calle", length = 50)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "no_exterior", length = 5)
	public String getNoExterior() {
		return this.noExterior;
	}

	public void setNoExterior(String noExterior) {
		this.noExterior = noExterior;
	}

	@Column(name = "no_interior", length = 5)
	public String getNoInterior() {
		return this.noInterior;
	}

	public void setNoInterior(String noInterior) {
		this.noInterior = noInterior;
	}

	@Column(name = "colonia", length = 30)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "localidad", length = 30)
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "referencia", length = 100)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "municipio", length = 30)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@Column(name = "estado", length = 30)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "pais", length = 30)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "cp", length = 8)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "imss", length = 16)
	public String getImss() {
		return this.imss;
	}

	public void setImss(String imss) {
		this.imss = imss;
	}

	@Column(name = "telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "etiqueta_1", length = 100)
	public String getEtiqueta1() {
		return this.etiqueta1;
	}

	public void setEtiqueta1(String etiqueta1) {
		this.etiqueta1 = etiqueta1;
	}

	@Column(name = "etiqueta_2", length = 100)
	public String getEtiqueta2() {
		return this.etiqueta2;
	}

	public void setEtiqueta2(String etiqueta2) {
		this.etiqueta2 = etiqueta2;
	}

	@Column(name = "etiqueta_3", length = 100)
	public String getEtiqueta3() {
		return this.etiqueta3;
	}

	public void setEtiqueta3(String etiqueta3) {
		this.etiqueta3 = etiqueta3;
	}

	@Column(name = "etiqueta_4", length = 100)
	public String getEtiqueta4() {
		return this.etiqueta4;
	}

	public void setEtiqueta4(String etiqueta4) {
		this.etiqueta4 = etiqueta4;
	}

	@Column(name = "etiqueta_5", length = 100)
	public String getEtiqueta5() {
		return this.etiqueta5;
	}

	public void setEtiqueta5(String etiqueta5) {
		this.etiqueta5 = etiqueta5;
	}

	@Column(name = "etiqueta_6", length = 100)
	public String getEtiqueta6() {
		return this.etiqueta6;
	}

	public void setEtiqueta6(String etiqueta6) {
		this.etiqueta6 = etiqueta6;
	}

	@Column(name = "etiqueta_7", length = 100)
	public String getEtiqueta7() {
		return this.etiqueta7;
	}

	public void setEtiqueta7(String etiqueta7) {
		this.etiqueta7 = etiqueta7;
	}

	@Column(name = "etiqueta_8", length = 100)
	public String getEtiqueta8() {
		return this.etiqueta8;
	}

	public void setEtiqueta8(String etiqueta8) {
		this.etiqueta8 = etiqueta8;
	}

	@Column(name = "etiqueta_9", length = 100)
	public String getEtiqueta9() {
		return this.etiqueta9;
	}

	public void setEtiqueta9(String etiqueta9) {
		this.etiqueta9 = etiqueta9;
	}

	@Column(name = "etiqueta_10", length = 100)
	public String getEtiqueta10() {
		return this.etiqueta10;
	}

	public void setEtiqueta10(String etiqueta10) {
		this.etiqueta10 = etiqueta10;
	}

}
