package mx.redts.adendas.model;

// Generated 22-may-2014 23:59:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeSumario generated by hbm2java
 */
@Entity
@Table(name = "fe_sumario", schema = "public")
public class FeSumario implements java.io.Serializable {

	private String ob3id;
	private String subtotal;
	private String montoDescuento1;
	private String montoDescuento2;
	private String montoDescuento3;
	private String montoDescuento4;
	private String montoDescuento5;
	private String iva;
	private String ieps;
	private String total;
	private String subtotal2;
	private String totalDeArticulosF;
	private String porcenIva;
	private String porcenIeps;
	private String porcenIsr;
	private String montoIsr;
	private String porcenImpuestoDePetrol;
	private String montoImpuestoDePe;
	private String porcenExento;
	private String montoExento;
	private String porcenEstatal;
	private String montoEstatal;
	private String porcenCedular;
	private String montoCedular;
	private String porcenMunicipal;
	private String montoMunicipal;
	private String porcenHospedaje;
	private String montoHospedaje;
	private String porcenOtrosImpuestos;
	private String montoOtrosImpuesto;
	private String numeroDePartidas;
	private String porcenIvaRetenido;
	private String montoDeIvaRetenid;
	private String porcenIsrRetenido;
	private String montoDeIsrRetenid;
	private String montoTotalDeDescu;
	private String subtotal3;
	private String subtotal4;
	private String etiqueta1;
	private String etiqueta2;

	public FeSumario() {
	}

	public FeSumario(String ob3id, String subtotal, String iva, String total,
			String porcenIva, String subtotal3) {
		this.ob3id = ob3id;
		this.subtotal = subtotal;
		this.iva = iva;
		this.total = total;
		this.porcenIva = porcenIva;
		this.subtotal3 = subtotal3;
	}

	public FeSumario(String ob3id, String subtotal, String montoDescuento1,
			String montoDescuento2, String montoDescuento3,
			String montoDescuento4, String montoDescuento5, String iva,
			String ieps, String total, String subtotal2,
			String totalDeArticulosF, String porcenIva, String porcenIeps,
			String porcenIsr, String montoIsr, String porcenImpuestoDePetrol,
			String montoImpuestoDePe, String porcenExento, String montoExento,
			String porcenEstatal, String montoEstatal, String porcenCedular,
			String montoCedular, String porcenMunicipal, String montoMunicipal,
			String porcenHospedaje, String montoHospedaje,
			String porcenOtrosImpuestos, String montoOtrosImpuesto,
			String numeroDePartidas, String porcenIvaRetenido,
			String montoDeIvaRetenid, String porcenIsrRetenido,
			String montoDeIsrRetenid, String montoTotalDeDescu,
			String subtotal3, String subtotal4, String etiqueta1,
			String etiqueta2) {
		this.ob3id = ob3id;
		this.subtotal = subtotal;
		this.montoDescuento1 = montoDescuento1;
		this.montoDescuento2 = montoDescuento2;
		this.montoDescuento3 = montoDescuento3;
		this.montoDescuento4 = montoDescuento4;
		this.montoDescuento5 = montoDescuento5;
		this.iva = iva;
		this.ieps = ieps;
		this.total = total;
		this.subtotal2 = subtotal2;
		this.totalDeArticulosF = totalDeArticulosF;
		this.porcenIva = porcenIva;
		this.porcenIeps = porcenIeps;
		this.porcenIsr = porcenIsr;
		this.montoIsr = montoIsr;
		this.porcenImpuestoDePetrol = porcenImpuestoDePetrol;
		this.montoImpuestoDePe = montoImpuestoDePe;
		this.porcenExento = porcenExento;
		this.montoExento = montoExento;
		this.porcenEstatal = porcenEstatal;
		this.montoEstatal = montoEstatal;
		this.porcenCedular = porcenCedular;
		this.montoCedular = montoCedular;
		this.porcenMunicipal = porcenMunicipal;
		this.montoMunicipal = montoMunicipal;
		this.porcenHospedaje = porcenHospedaje;
		this.montoHospedaje = montoHospedaje;
		this.porcenOtrosImpuestos = porcenOtrosImpuestos;
		this.montoOtrosImpuesto = montoOtrosImpuesto;
		this.numeroDePartidas = numeroDePartidas;
		this.porcenIvaRetenido = porcenIvaRetenido;
		this.montoDeIvaRetenid = montoDeIvaRetenid;
		this.porcenIsrRetenido = porcenIsrRetenido;
		this.montoDeIsrRetenid = montoDeIsrRetenid;
		this.montoTotalDeDescu = montoTotalDeDescu;
		this.subtotal3 = subtotal3;
		this.subtotal4 = subtotal4;
		this.etiqueta1 = etiqueta1;
		this.etiqueta2 = etiqueta2;
	}

	@Id
	@Column(name = "ob3id", unique = true, nullable = false, length = 32)
	public String getOb3id() {
		return this.ob3id;
	}

	public void setOb3id(String ob3id) {
		this.ob3id = ob3id;
	}

	@Column(name = "subtotal", nullable = false, length = 20)
	public String getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(String subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "monto_descuento_1", length = 20)
	public String getMontoDescuento1() {
		return this.montoDescuento1;
	}

	public void setMontoDescuento1(String montoDescuento1) {
		this.montoDescuento1 = montoDescuento1;
	}

	@Column(name = "monto_descuento_2", length = 20)
	public String getMontoDescuento2() {
		return this.montoDescuento2;
	}

	public void setMontoDescuento2(String montoDescuento2) {
		this.montoDescuento2 = montoDescuento2;
	}

	@Column(name = "monto_descuento_3", length = 20)
	public String getMontoDescuento3() {
		return this.montoDescuento3;
	}

	public void setMontoDescuento3(String montoDescuento3) {
		this.montoDescuento3 = montoDescuento3;
	}

	@Column(name = "monto_descuento_4", length = 20)
	public String getMontoDescuento4() {
		return this.montoDescuento4;
	}

	public void setMontoDescuento4(String montoDescuento4) {
		this.montoDescuento4 = montoDescuento4;
	}

	@Column(name = "monto_descuento_5", length = 20)
	public String getMontoDescuento5() {
		return this.montoDescuento5;
	}

	public void setMontoDescuento5(String montoDescuento5) {
		this.montoDescuento5 = montoDescuento5;
	}

	@Column(name = "iva", nullable = false, length = 20)
	public String getIva() {
		return this.iva;
	}

	public void setIva(String iva) {
		this.iva = iva;
	}

	@Column(name = "ieps", length = 20)
	public String getIeps() {
		return this.ieps;
	}

	public void setIeps(String ieps) {
		this.ieps = ieps;
	}

	@Column(name = "total", nullable = false, length = 20)
	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	@Column(name = "subtotal_2", length = 20)
	public String getSubtotal2() {
		return this.subtotal2;
	}

	public void setSubtotal2(String subtotal2) {
		this.subtotal2 = subtotal2;
	}

	@Column(name = "total_de_articulos_f", length = 10)
	public String getTotalDeArticulosF() {
		return this.totalDeArticulosF;
	}

	public void setTotalDeArticulosF(String totalDeArticulosF) {
		this.totalDeArticulosF = totalDeArticulosF;
	}

	@Column(name = "porcen_iva", nullable = false, length = 3)
	public String getPorcenIva() {
		return this.porcenIva;
	}

	public void setPorcenIva(String porcenIva) {
		this.porcenIva = porcenIva;
	}

	@Column(name = "porcen_ieps", length = 3)
	public String getPorcenIeps() {
		return this.porcenIeps;
	}

	public void setPorcenIeps(String porcenIeps) {
		this.porcenIeps = porcenIeps;
	}

	@Column(name = "porcen_isr", length = 3)
	public String getPorcenIsr() {
		return this.porcenIsr;
	}

	public void setPorcenIsr(String porcenIsr) {
		this.porcenIsr = porcenIsr;
	}

	@Column(name = "monto_isr", length = 20)
	public String getMontoIsr() {
		return this.montoIsr;
	}

	public void setMontoIsr(String montoIsr) {
		this.montoIsr = montoIsr;
	}

	@Column(name = "porcen_impuesto_de_petrol", length = 3)
	public String getPorcenImpuestoDePetrol() {
		return this.porcenImpuestoDePetrol;
	}

	public void setPorcenImpuestoDePetrol(String porcenImpuestoDePetrol) {
		this.porcenImpuestoDePetrol = porcenImpuestoDePetrol;
	}

	@Column(name = "monto_impuesto_de_pe", length = 20)
	public String getMontoImpuestoDePe() {
		return this.montoImpuestoDePe;
	}

	public void setMontoImpuestoDePe(String montoImpuestoDePe) {
		this.montoImpuestoDePe = montoImpuestoDePe;
	}

	@Column(name = "porcen_exento", length = 3)
	public String getPorcenExento() {
		return this.porcenExento;
	}

	public void setPorcenExento(String porcenExento) {
		this.porcenExento = porcenExento;
	}

	@Column(name = "monto_exento", length = 20)
	public String getMontoExento() {
		return this.montoExento;
	}

	public void setMontoExento(String montoExento) {
		this.montoExento = montoExento;
	}

	@Column(name = "porcen_estatal", length = 3)
	public String getPorcenEstatal() {
		return this.porcenEstatal;
	}

	public void setPorcenEstatal(String porcenEstatal) {
		this.porcenEstatal = porcenEstatal;
	}

	@Column(name = "monto_estatal", length = 20)
	public String getMontoEstatal() {
		return this.montoEstatal;
	}

	public void setMontoEstatal(String montoEstatal) {
		this.montoEstatal = montoEstatal;
	}

	@Column(name = "porcen_cedular", length = 3)
	public String getPorcenCedular() {
		return this.porcenCedular;
	}

	public void setPorcenCedular(String porcenCedular) {
		this.porcenCedular = porcenCedular;
	}

	@Column(name = "monto_cedular", length = 20)
	public String getMontoCedular() {
		return this.montoCedular;
	}

	public void setMontoCedular(String montoCedular) {
		this.montoCedular = montoCedular;
	}

	@Column(name = "porcen_municipal", length = 3)
	public String getPorcenMunicipal() {
		return this.porcenMunicipal;
	}

	public void setPorcenMunicipal(String porcenMunicipal) {
		this.porcenMunicipal = porcenMunicipal;
	}

	@Column(name = "monto_municipal", length = 20)
	public String getMontoMunicipal() {
		return this.montoMunicipal;
	}

	public void setMontoMunicipal(String montoMunicipal) {
		this.montoMunicipal = montoMunicipal;
	}

	@Column(name = "porcen_hospedaje", length = 3)
	public String getPorcenHospedaje() {
		return this.porcenHospedaje;
	}

	public void setPorcenHospedaje(String porcenHospedaje) {
		this.porcenHospedaje = porcenHospedaje;
	}

	@Column(name = "monto_hospedaje", length = 20)
	public String getMontoHospedaje() {
		return this.montoHospedaje;
	}

	public void setMontoHospedaje(String montoHospedaje) {
		this.montoHospedaje = montoHospedaje;
	}

	@Column(name = "porcen_otros_impuestos", length = 3)
	public String getPorcenOtrosImpuestos() {
		return this.porcenOtrosImpuestos;
	}

	public void setPorcenOtrosImpuestos(String porcenOtrosImpuestos) {
		this.porcenOtrosImpuestos = porcenOtrosImpuestos;
	}

	@Column(name = "monto_otros_impuesto", length = 20)
	public String getMontoOtrosImpuesto() {
		return this.montoOtrosImpuesto;
	}

	public void setMontoOtrosImpuesto(String montoOtrosImpuesto) {
		this.montoOtrosImpuesto = montoOtrosImpuesto;
	}

	@Column(name = "numero_de_partidas", length = 3)
	public String getNumeroDePartidas() {
		return this.numeroDePartidas;
	}

	public void setNumeroDePartidas(String numeroDePartidas) {
		this.numeroDePartidas = numeroDePartidas;
	}

	@Column(name = "porcen_iva_retenido", length = 20)
	public String getPorcenIvaRetenido() {
		return this.porcenIvaRetenido;
	}

	public void setPorcenIvaRetenido(String porcenIvaRetenido) {
		this.porcenIvaRetenido = porcenIvaRetenido;
	}

	@Column(name = "monto_de_iva_retenid", length = 3)
	public String getMontoDeIvaRetenid() {
		return this.montoDeIvaRetenid;
	}

	public void setMontoDeIvaRetenid(String montoDeIvaRetenid) {
		this.montoDeIvaRetenid = montoDeIvaRetenid;
	}

	@Column(name = "porcen_isr_retenido", length = 20)
	public String getPorcenIsrRetenido() {
		return this.porcenIsrRetenido;
	}

	public void setPorcenIsrRetenido(String porcenIsrRetenido) {
		this.porcenIsrRetenido = porcenIsrRetenido;
	}

	@Column(name = "monto_de_isr_retenid", length = 3)
	public String getMontoDeIsrRetenid() {
		return this.montoDeIsrRetenid;
	}

	public void setMontoDeIsrRetenid(String montoDeIsrRetenid) {
		this.montoDeIsrRetenid = montoDeIsrRetenid;
	}

	@Column(name = "monto_total_de_descu", length = 20)
	public String getMontoTotalDeDescu() {
		return this.montoTotalDeDescu;
	}

	public void setMontoTotalDeDescu(String montoTotalDeDescu) {
		this.montoTotalDeDescu = montoTotalDeDescu;
	}

	@Column(name = "subtotal_3", nullable = false, length = 20)
	public String getSubtotal3() {
		return this.subtotal3;
	}

	public void setSubtotal3(String subtotal3) {
		this.subtotal3 = subtotal3;
	}

	@Column(name = "subtotal_4", length = 20)
	public String getSubtotal4() {
		return this.subtotal4;
	}

	public void setSubtotal4(String subtotal4) {
		this.subtotal4 = subtotal4;
	}

	@Column(name = "etiqueta_1", length = 100)
	public String getEtiqueta1() {
		return this.etiqueta1;
	}

	public void setEtiqueta1(String etiqueta1) {
		this.etiqueta1 = etiqueta1;
	}

	@Column(name = "etiqueta_2", length = 100)
	public String getEtiqueta2() {
		return this.etiqueta2;
	}

	public void setEtiqueta2(String etiqueta2) {
		this.etiqueta2 = etiqueta2;
	}

}
