package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AdOrg generated by hbm2java
 */
@Entity
@Table(name = "ad_org", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ad_client_id", "value" }))
public class AdOrg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String adOrgId;
	private CCurrency CCurrency;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String value;
	private String name;
	private String description;
	private char issummary;
	private String adOrgtypeId;
	private char isperiodcontrolallowed;
	private String CCalendarId;
	private char isready;
	private String socialName;
	private String CAcctschemaId;
	private Set<CLocation> CLocations = new HashSet<CLocation>(0);
	private Set<CRegion> CRegions = new HashSet<CRegion>(0);
	private AdOrginfo adOrginfo;
	private Set<CBpartner> CBpartnersForAdOrgId = new HashSet<CBpartner>(0);
	private Set<CDoctype> CDoctypes = new HashSet<CDoctype>(0);
	private Set<CUom> CUoms = new HashSet<CUom>(0);
	private Set<CPaymentterm> CPaymentterms = new HashSet<CPaymentterm>(0);
	private Set<CInvoiceline> CInvoicelines = new HashSet<CInvoiceline>(0);
	private Set<CCurrency> CCurrencies = new HashSet<CCurrency>(0);
	private Set<CInvoice> CInvoicesForAdOrgtrxId = new HashSet<CInvoice>(0);
	private Set<MProduct> MProducts = new HashSet<MProduct>(0);
	private Set<CBpartnerLocation> CBpartnerLocations = new HashSet<CBpartnerLocation>(
			0);
	private Set<CBpartner> CBpartnersForAdForcedOrgId = new HashSet<CBpartner>(
			0);
	private Set<FinPaymentmethod> finPaymentmethods = new HashSet<FinPaymentmethod>(
			0);
	private Set<CCountry> CCountries = new HashSet<CCountry>(0);
	private Set<CInvoicetax> CInvoicetaxes = new HashSet<CInvoicetax>(0);
	private Set<CTax> CTaxes = new HashSet<CTax>(0);
	private Set<COrder> COrdersForAdOrgtrxId = new HashSet<COrder>(0);
	private Set<COrder> COrdersForAdOrgId = new HashSet<COrder>(0);
	private Set<CInvoice> CInvoicesForAdOrgId = new HashSet<CInvoice>(0);

	public AdOrg() {
	}

	public AdOrg(String adOrgId, CCurrency CCurrency, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String value, String name, String description,
			char issummary, String adOrgtypeId, char isperiodcontrolallowed,
			String CCalendarId, char isready, String socialName,
			String CAcctschemaId, Set<CLocation> CLocations,
			Set<CRegion> CRegions, AdOrginfo adOrginfo,
			Set<CBpartner> CBpartnersForAdOrgId, Set<CDoctype> CDoctypes,
			Set<CUom> CUoms, Set<CPaymentterm> CPaymentterms,
			Set<CInvoiceline> CInvoicelines, Set<CCurrency> CCurrencies,
			Set<CInvoice> CInvoicesForAdOrgtrxId, Set<MProduct> MProducts,
			Set<CBpartnerLocation> CBpartnerLocations,
			Set<CBpartner> CBpartnersForAdForcedOrgId,
			Set<FinPaymentmethod> finPaymentmethods, Set<CCountry> CCountries,
			Set<CInvoicetax> CInvoicetaxes, Set<CTax> CTaxes,
			Set<COrder> COrdersForAdOrgtrxId, Set<COrder> COrdersForAdOrgId,
			Set<CInvoice> CInvoicesForAdOrgId) {
		this.adOrgId = adOrgId;
		this.CCurrency = CCurrency;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.value = value;
		this.name = name;
		this.description = description;
		this.issummary = issummary;
		this.adOrgtypeId = adOrgtypeId;
		this.isperiodcontrolallowed = isperiodcontrolallowed;
		this.CCalendarId = CCalendarId;
		this.isready = isready;
		this.socialName = socialName;
		this.CAcctschemaId = CAcctschemaId;
		this.CLocations = CLocations;
		this.CRegions = CRegions;
		this.adOrginfo = adOrginfo;
		this.CBpartnersForAdOrgId = CBpartnersForAdOrgId;
		this.CDoctypes = CDoctypes;
		this.CUoms = CUoms;
		this.CPaymentterms = CPaymentterms;
		this.CInvoicelines = CInvoicelines;
		this.CCurrencies = CCurrencies;
		this.CInvoicesForAdOrgtrxId = CInvoicesForAdOrgtrxId;
		this.MProducts = MProducts;
		this.CBpartnerLocations = CBpartnerLocations;
		this.CBpartnersForAdForcedOrgId = CBpartnersForAdForcedOrgId;
		this.finPaymentmethods = finPaymentmethods;
		this.CCountries = CCountries;
		this.CInvoicetaxes = CInvoicetaxes;
		this.CTaxes = CTaxes;
		this.COrdersForAdOrgtrxId = COrdersForAdOrgtrxId;
		this.COrdersForAdOrgId = COrdersForAdOrgId;
		this.CInvoicesForAdOrgId = CInvoicesForAdOrgId;
	}

	public AdOrg(String adOrgId, String adClientId, char isactive,
			Date created, String createdby, Date updated, String updatedby,
			String value, String name, char issummary, String adOrgtypeId,
			char isperiodcontrolallowed, char isready) {
		this.adOrgId = adOrgId;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.value = value;
		this.name = name;
		this.issummary = issummary;
		this.adOrgtypeId = adOrgtypeId;
		this.isperiodcontrolallowed = isperiodcontrolallowed;
		this.isready = isready;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@Id
	@Column(name = "ad_org_id", unique = true, nullable = false, length = 32)
	public String getAdOrgId() {
		return this.adOrgId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public AdOrginfo getAdOrginfo() {
		return this.adOrginfo;
	}

	@Column(name = "ad_orgtype_id", nullable = false, length = 32)
	public String getAdOrgtypeId() {
		return this.adOrgtypeId;
	}

	@Column(name = "c_acctschema_id", length = 32)
	public String getCAcctschemaId() {
		return this.CAcctschemaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CBpartnerLocation> getCBpartnerLocations() {
		return this.CBpartnerLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrgByAdForcedOrgId")
	public Set<CBpartner> getCBpartnersForAdForcedOrgId() {
		return this.CBpartnersForAdForcedOrgId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrgByAdOrgId")
	public Set<CBpartner> getCBpartnersForAdOrgId() {
		return this.CBpartnersForAdOrgId;
	}

	@Column(name = "c_calendar_id", length = 32)
	public String getCCalendarId() {
		return this.CCalendarId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CCountry> getCCountries() {
		return this.CCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CCurrency> getCCurrencies() {
		return this.CCurrencies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_currency_id")
	public CCurrency getCCurrency() {
		return this.CCurrency;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CDoctype> getCDoctypes() {
		return this.CDoctypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CInvoiceline> getCInvoicelines() {
		return this.CInvoicelines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrgByAdOrgId")
	public Set<CInvoice> getCInvoicesForAdOrgId() {
		return this.CInvoicesForAdOrgId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrgByAdOrgtrxId")
	public Set<CInvoice> getCInvoicesForAdOrgtrxId() {
		return this.CInvoicesForAdOrgtrxId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CInvoicetax> getCInvoicetaxes() {
		return this.CInvoicetaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CLocation> getCLocations() {
		return this.CLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrgByAdOrgId")
	public Set<COrder> getCOrdersForAdOrgId() {
		return this.COrdersForAdOrgId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrgByAdOrgtrxId")
	public Set<COrder> getCOrdersForAdOrgtrxId() {
		return this.COrdersForAdOrgtrxId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CPaymentterm> getCPaymentterms() {
		return this.CPaymentterms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CRegion> getCRegions() {
		return this.CRegions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CTax> getCTaxes() {
		return this.CTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<CUom> getCUoms() {
		return this.CUoms;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<FinPaymentmethod> getFinPaymentmethods() {
		return this.finPaymentmethods;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isperiodcontrolallowed", nullable = false, length = 1)
	public char getIsperiodcontrolallowed() {
		return this.isperiodcontrolallowed;
	}

	@Column(name = "isready", nullable = false, length = 1)
	public char getIsready() {
		return this.isready;
	}

	@Column(name = "issummary", nullable = false, length = 1)
	public char getIssummary() {
		return this.issummary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adOrg")
	public Set<MProduct> getMProducts() {
		return this.MProducts;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "social_name", length = 60)
	public String getSocialName() {
		return this.socialName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "value", nullable = false, length = 40)
	public String getValue() {
		return this.value;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrgId(String adOrgId) {
		this.adOrgId = adOrgId;
	}

	public void setAdOrginfo(AdOrginfo adOrginfo) {
		this.adOrginfo = adOrginfo;
	}

	public void setAdOrgtypeId(String adOrgtypeId) {
		this.adOrgtypeId = adOrgtypeId;
	}

	public void setCAcctschemaId(String CAcctschemaId) {
		this.CAcctschemaId = CAcctschemaId;
	}

	public void setCBpartnerLocations(Set<CBpartnerLocation> CBpartnerLocations) {
		this.CBpartnerLocations = CBpartnerLocations;
	}

	public void setCBpartnersForAdForcedOrgId(
			Set<CBpartner> CBpartnersForAdForcedOrgId) {
		this.CBpartnersForAdForcedOrgId = CBpartnersForAdForcedOrgId;
	}

	public void setCBpartnersForAdOrgId(Set<CBpartner> CBpartnersForAdOrgId) {
		this.CBpartnersForAdOrgId = CBpartnersForAdOrgId;
	}

	public void setCCalendarId(String CCalendarId) {
		this.CCalendarId = CCalendarId;
	}

	public void setCCountries(Set<CCountry> CCountries) {
		this.CCountries = CCountries;
	}

	public void setCCurrencies(Set<CCurrency> CCurrencies) {
		this.CCurrencies = CCurrencies;
	}

	public void setCCurrency(CCurrency CCurrency) {
		this.CCurrency = CCurrency;
	}

	public void setCDoctypes(Set<CDoctype> CDoctypes) {
		this.CDoctypes = CDoctypes;
	}

	public void setCInvoicelines(Set<CInvoiceline> CInvoicelines) {
		this.CInvoicelines = CInvoicelines;
	}

	public void setCInvoicesForAdOrgId(Set<CInvoice> CInvoicesForAdOrgId) {
		this.CInvoicesForAdOrgId = CInvoicesForAdOrgId;
	}

	public void setCInvoicesForAdOrgtrxId(Set<CInvoice> CInvoicesForAdOrgtrxId) {
		this.CInvoicesForAdOrgtrxId = CInvoicesForAdOrgtrxId;
	}

	public void setCInvoicetaxes(Set<CInvoicetax> CInvoicetaxes) {
		this.CInvoicetaxes = CInvoicetaxes;
	}

	public void setCLocations(Set<CLocation> CLocations) {
		this.CLocations = CLocations;
	}

	public void setCOrdersForAdOrgId(Set<COrder> COrdersForAdOrgId) {
		this.COrdersForAdOrgId = COrdersForAdOrgId;
	}

	public void setCOrdersForAdOrgtrxId(Set<COrder> COrdersForAdOrgtrxId) {
		this.COrdersForAdOrgtrxId = COrdersForAdOrgtrxId;
	}

	public void setCPaymentterms(Set<CPaymentterm> CPaymentterms) {
		this.CPaymentterms = CPaymentterms;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCRegions(Set<CRegion> CRegions) {
		this.CRegions = CRegions;
	}

	public void setCTaxes(Set<CTax> CTaxes) {
		this.CTaxes = CTaxes;
	}

	public void setCUoms(Set<CUom> CUoms) {
		this.CUoms = CUoms;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setFinPaymentmethods(Set<FinPaymentmethod> finPaymentmethods) {
		this.finPaymentmethods = finPaymentmethods;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsperiodcontrolallowed(char isperiodcontrolallowed) {
		this.isperiodcontrolallowed = isperiodcontrolallowed;
	}

	public void setIsready(char isready) {
		this.isready = isready;
	}

	public void setIssummary(char issummary) {
		this.issummary = issummary;
	}

	public void setMProducts(Set<MProduct> MProducts) {
		this.MProducts = MProducts;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setSocialName(String socialName) {
		this.socialName = socialName;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
