package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AdOrginfo generated by hbm2java
 */
@Entity
@Table(name = "ad_orginfo", schema = "public")
public class AdOrginfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String adOrgId;
	private AdOrg adOrg;
	private CTax CTax;
	private CBpartner CBpartner;
	private CLocation CLocation;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String duns;
	private String taxid;
	private char istaxundeductable;
	private String logo;
	private Character referenceOrder;
	private String yourCompanyDocumentImage;
	private BigDecimal automaticWriteoffAmt;
	private String adUserId;
	private String emAprmPaymentDesc;

	public AdOrginfo() {
	}

	public AdOrginfo(AdOrg adOrg, CTax CTax, CBpartner CBpartner,
			CLocation CLocation, String adClientId, char isactive,
			Date created, String createdby, Date updated, String updatedby,
			String duns, String taxid, char istaxundeductable, String logo,
			Character referenceOrder, String yourCompanyDocumentImage,
			BigDecimal automaticWriteoffAmt, String adUserId,
			String emAprmPaymentDesc) {
		this.adOrg = adOrg;
		this.CTax = CTax;
		this.CBpartner = CBpartner;
		this.CLocation = CLocation;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.duns = duns;
		this.taxid = taxid;
		this.istaxundeductable = istaxundeductable;
		this.logo = logo;
		this.referenceOrder = referenceOrder;
		this.yourCompanyDocumentImage = yourCompanyDocumentImage;
		this.automaticWriteoffAmt = automaticWriteoffAmt;
		this.adUserId = adUserId;
		this.emAprmPaymentDesc = emAprmPaymentDesc;
	}

	public AdOrginfo(AdOrg adOrg, String adClientId, char isactive,
			Date created, String createdby, Date updated, String updatedby,
			String duns, String taxid, char istaxundeductable,
			String emAprmPaymentDesc) {
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.duns = duns;
		this.taxid = taxid;
		this.istaxundeductable = istaxundeductable;
		this.emAprmPaymentDesc = emAprmPaymentDesc;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "adOrg"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ad_org_id", unique = true, nullable = false, length = 32)
	public String getAdOrgId() {
		return this.adOrgId;
	}

	@Column(name = "ad_user_id", length = 32)
	public String getAdUserId() {
		return this.adUserId;
	}

	@Column(name = "automatic_writeoff_amt", precision = 131089, scale = 0)
	public BigDecimal getAutomaticWriteoffAmt() {
		return this.automaticWriteoffAmt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_bpartner_id")
	public CBpartner getCBpartner() {
		return this.CBpartner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_location_id")
	public CLocation getCLocation() {
		return this.CLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_tax_id")
	public CTax getCTax() {
		return this.CTax;
	}

	@Column(name = "duns", nullable = false, length = 11)
	public String getDuns() {
		return this.duns;
	}

	@Column(name = "em_aprm_payment_desc", nullable = false, length = 60)
	public String getEmAprmPaymentDesc() {
		return this.emAprmPaymentDesc;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "istaxundeductable", nullable = false, length = 1)
	public char getIstaxundeductable() {
		return this.istaxundeductable;
	}

	@Column(name = "logo", length = 200)
	public String getLogo() {
		return this.logo;
	}

	@Column(name = "reference_order", length = 1)
	public Character getReferenceOrder() {
		return this.referenceOrder;
	}

	@Column(name = "taxid", nullable = false, length = 20)
	public String getTaxid() {
		return this.taxid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "your_company_document_image", length = 32)
	public String getYourCompanyDocumentImage() {
		return this.yourCompanyDocumentImage;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setAdOrgId(String adOrgId) {
		this.adOrgId = adOrgId;
	}

	public void setAdUserId(String adUserId) {
		this.adUserId = adUserId;
	}

	public void setAutomaticWriteoffAmt(BigDecimal automaticWriteoffAmt) {
		this.automaticWriteoffAmt = automaticWriteoffAmt;
	}

	public void setCBpartner(CBpartner CBpartner) {
		this.CBpartner = CBpartner;
	}

	public void setCLocation(CLocation CLocation) {
		this.CLocation = CLocation;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCTax(CTax CTax) {
		this.CTax = CTax;
	}

	public void setDuns(String duns) {
		this.duns = duns;
	}

	public void setEmAprmPaymentDesc(String emAprmPaymentDesc) {
		this.emAprmPaymentDesc = emAprmPaymentDesc;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIstaxundeductable(char istaxundeductable) {
		this.istaxundeductable = istaxundeductable;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public void setReferenceOrder(Character referenceOrder) {
		this.referenceOrder = referenceOrder;
	}

	public void setTaxid(String taxid) {
		this.taxid = taxid;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setYourCompanyDocumentImage(String yourCompanyDocumentImage) {
		this.yourCompanyDocumentImage = yourCompanyDocumentImage;
	}

}
