package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CBpartner generated by hbm2java
 */
@Entity
@Table(name = "c_bpartner", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ad_client_id", "value" }))
public class CBpartner implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CBpartnerId;
	private FinPaymentmethod finPaymentmethodByFinPaymentmethodId;
	private CBpartner CBpartnerByBpartnerParentId;
	private CBpartner CBpartnerBySalesrepId;
	private AdOrg adOrgByAdOrgId;
	private CPaymentterm CPaymenttermByPoPaymenttermId;
	private FinPaymentmethod finPaymentmethodByPoPaymentmethodId;
	private AdOrg adOrgByAdForcedOrgId;
	private CPaymentterm CPaymenttermByCPaymenttermId;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String value;
	private String name;
	private String name2;
	private String description;
	private char issummary;
	private String CBpGroupId;
	private char isonetime;
	private char isprospect;
	private char isvendor;
	private char iscustomer;
	private char isemployee;
	private char issalesrep;
	private String referenceno;
	private String duns;
	private String url;
	private String adLanguage;
	private String taxid;
	private Character istaxexempt;
	private String CInvoicescheduleId;
	private Character rating;
	private Long salesvolume;
	private Long numberemployees;
	private String naics;
	private Date firstsale;
	private BigDecimal acqusitioncost;
	private BigDecimal potentiallifetimevalue;
	private BigDecimal actuallifetimevalue;
	private Long shareofcustomer;
	private String paymentrule;
	private BigDecimal soCreditlimit;
	private BigDecimal soCreditused;
	private String MPricelistId;
	private Character isdiscountprinted;
	private String soDescription;
	private String poreference;
	private String paymentrulepo;
	private String poPricelistId;
	private Long documentcopies;
	private String CGreetingId;
	private String invoicerule;
	private String deliveryrule;
	private String deliveryviarule;
	private String socreditstatus;
	private char showpriceinorder;
	private String invoicegrouping;
	private Long fixmonthday;
	private Long fixmonthday2;
	private Long fixmonthday3;
	private Character isworker;
	private String upc;
	private String CSalaryCategoryId;
	private String invoicePrintformat;
	private Long lastDays;
	private String poBankaccountId;
	private String poBpTaxcategoryId;
	private Long poFixmonthday;
	private Long poFixmonthday2;
	private Long poFixmonthday3;
	private String soBankaccountId;
	private String soBpTaxcategoryId;
	private String fiscalcode;
	private String isofiscalcode;
	private String poCIncotermsId;
	private String soCIncotermsId;
	private String finFinancialAccountId;
	private String poFinancialAccountId;
	private Set<CBpartner> CBpartnersForBpartnerParentId = new HashSet<CBpartner>(
			0);
	private Set<CInvoice> CInvoices = new HashSet<CInvoice>(0);
	private Set<CBpartner> CBpartnersForSalesrepId = new HashSet<CBpartner>(0);
	private Set<COrder> COrdersForCBpartnerId = new HashSet<COrder>(0);
	private Set<MProduct> MProducts = new HashSet<MProduct>(0);
	private Set<CBpartnerLocation> CBpartnerLocations = new HashSet<CBpartnerLocation>(
			0);
	private Set<AdOrginfo> adOrginfos = new HashSet<AdOrginfo>(0);
	private Set<COrder> COrdersForDropshipBpartnerId = new HashSet<COrder>(0);

	public CBpartner() {
	}

	public CBpartner(String CBpartnerId, AdOrg adOrgByAdOrgId,
			String adClientId, char isactive, Date created, String createdby,
			Date updated, String updatedby, String value, String name,
			char issummary, String CBpGroupId, char isonetime, char isprospect,
			char isvendor, char iscustomer, char isemployee, char issalesrep,
			char showpriceinorder) {
		this.CBpartnerId = CBpartnerId;
		this.adOrgByAdOrgId = adOrgByAdOrgId;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.value = value;
		this.name = name;
		this.issummary = issummary;
		this.CBpGroupId = CBpGroupId;
		this.isonetime = isonetime;
		this.isprospect = isprospect;
		this.isvendor = isvendor;
		this.iscustomer = iscustomer;
		this.isemployee = isemployee;
		this.issalesrep = issalesrep;
		this.showpriceinorder = showpriceinorder;
	}

	public CBpartner(String CBpartnerId,
			FinPaymentmethod finPaymentmethodByFinPaymentmethodId,
			CBpartner CBpartnerByBpartnerParentId,
			CBpartner CBpartnerBySalesrepId, AdOrg adOrgByAdOrgId,
			CPaymentterm CPaymenttermByPoPaymenttermId,
			FinPaymentmethod finPaymentmethodByPoPaymentmethodId,
			AdOrg adOrgByAdForcedOrgId,
			CPaymentterm CPaymenttermByCPaymenttermId, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String value, String name, String name2,
			String description, char issummary, String CBpGroupId,
			char isonetime, char isprospect, char isvendor, char iscustomer,
			char isemployee, char issalesrep, String referenceno, String duns,
			String url, String adLanguage, String taxid, Character istaxexempt,
			String CInvoicescheduleId, Character rating, Long salesvolume,
			Long numberemployees, String naics, Date firstsale,
			BigDecimal acqusitioncost, BigDecimal potentiallifetimevalue,
			BigDecimal actuallifetimevalue, Long shareofcustomer,
			String paymentrule, BigDecimal soCreditlimit,
			BigDecimal soCreditused, String MPricelistId,
			Character isdiscountprinted, String soDescription,
			String poreference, String paymentrulepo, String poPricelistId,
			Long documentcopies, String CGreetingId, String invoicerule,
			String deliveryrule, String deliveryviarule, String socreditstatus,
			char showpriceinorder, String invoicegrouping, Long fixmonthday,
			Long fixmonthday2, Long fixmonthday3, Character isworker,
			String upc, String CSalaryCategoryId, String invoicePrintformat,
			Long lastDays, String poBankaccountId, String poBpTaxcategoryId,
			Long poFixmonthday, Long poFixmonthday2, Long poFixmonthday3,
			String soBankaccountId, String soBpTaxcategoryId,
			String fiscalcode, String isofiscalcode, String poCIncotermsId,
			String soCIncotermsId, String finFinancialAccountId,
			String poFinancialAccountId,
			Set<CBpartner> CBpartnersForBpartnerParentId,
			Set<CInvoice> CInvoices, Set<CBpartner> CBpartnersForSalesrepId,
			Set<COrder> COrdersForCBpartnerId, Set<MProduct> MProducts,
			Set<CBpartnerLocation> CBpartnerLocations,
			Set<AdOrginfo> adOrginfos, Set<COrder> COrdersForDropshipBpartnerId) {
		this.CBpartnerId = CBpartnerId;
		this.finPaymentmethodByFinPaymentmethodId = finPaymentmethodByFinPaymentmethodId;
		this.CBpartnerByBpartnerParentId = CBpartnerByBpartnerParentId;
		this.CBpartnerBySalesrepId = CBpartnerBySalesrepId;
		this.adOrgByAdOrgId = adOrgByAdOrgId;
		this.CPaymenttermByPoPaymenttermId = CPaymenttermByPoPaymenttermId;
		this.finPaymentmethodByPoPaymentmethodId = finPaymentmethodByPoPaymentmethodId;
		this.adOrgByAdForcedOrgId = adOrgByAdForcedOrgId;
		this.CPaymenttermByCPaymenttermId = CPaymenttermByCPaymenttermId;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.value = value;
		this.name = name;
		this.name2 = name2;
		this.description = description;
		this.issummary = issummary;
		this.CBpGroupId = CBpGroupId;
		this.isonetime = isonetime;
		this.isprospect = isprospect;
		this.isvendor = isvendor;
		this.iscustomer = iscustomer;
		this.isemployee = isemployee;
		this.issalesrep = issalesrep;
		this.referenceno = referenceno;
		this.duns = duns;
		this.url = url;
		this.adLanguage = adLanguage;
		this.taxid = taxid;
		this.istaxexempt = istaxexempt;
		this.CInvoicescheduleId = CInvoicescheduleId;
		this.rating = rating;
		this.salesvolume = salesvolume;
		this.numberemployees = numberemployees;
		this.naics = naics;
		this.firstsale = firstsale;
		this.acqusitioncost = acqusitioncost;
		this.potentiallifetimevalue = potentiallifetimevalue;
		this.actuallifetimevalue = actuallifetimevalue;
		this.shareofcustomer = shareofcustomer;
		this.paymentrule = paymentrule;
		this.soCreditlimit = soCreditlimit;
		this.soCreditused = soCreditused;
		this.MPricelistId = MPricelistId;
		this.isdiscountprinted = isdiscountprinted;
		this.soDescription = soDescription;
		this.poreference = poreference;
		this.paymentrulepo = paymentrulepo;
		this.poPricelistId = poPricelistId;
		this.documentcopies = documentcopies;
		this.CGreetingId = CGreetingId;
		this.invoicerule = invoicerule;
		this.deliveryrule = deliveryrule;
		this.deliveryviarule = deliveryviarule;
		this.socreditstatus = socreditstatus;
		this.showpriceinorder = showpriceinorder;
		this.invoicegrouping = invoicegrouping;
		this.fixmonthday = fixmonthday;
		this.fixmonthday2 = fixmonthday2;
		this.fixmonthday3 = fixmonthday3;
		this.isworker = isworker;
		this.upc = upc;
		this.CSalaryCategoryId = CSalaryCategoryId;
		this.invoicePrintformat = invoicePrintformat;
		this.lastDays = lastDays;
		this.poBankaccountId = poBankaccountId;
		this.poBpTaxcategoryId = poBpTaxcategoryId;
		this.poFixmonthday = poFixmonthday;
		this.poFixmonthday2 = poFixmonthday2;
		this.poFixmonthday3 = poFixmonthday3;
		this.soBankaccountId = soBankaccountId;
		this.soBpTaxcategoryId = soBpTaxcategoryId;
		this.fiscalcode = fiscalcode;
		this.isofiscalcode = isofiscalcode;
		this.poCIncotermsId = poCIncotermsId;
		this.soCIncotermsId = soCIncotermsId;
		this.finFinancialAccountId = finFinancialAccountId;
		this.poFinancialAccountId = poFinancialAccountId;
		this.CBpartnersForBpartnerParentId = CBpartnersForBpartnerParentId;
		this.CInvoices = CInvoices;
		this.CBpartnersForSalesrepId = CBpartnersForSalesrepId;
		this.COrdersForCBpartnerId = COrdersForCBpartnerId;
		this.MProducts = MProducts;
		this.CBpartnerLocations = CBpartnerLocations;
		this.adOrginfos = adOrginfos;
		this.COrdersForDropshipBpartnerId = COrdersForDropshipBpartnerId;
	}

	@Column(name = "acqusitioncost", precision = 131089, scale = 0)
	public BigDecimal getAcqusitioncost() {
		return this.acqusitioncost;
	}

	@Column(name = "actuallifetimevalue", precision = 131089, scale = 0)
	public BigDecimal getActuallifetimevalue() {
		return this.actuallifetimevalue;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@Column(name = "ad_language", length = 6)
	public String getAdLanguage() {
		return this.adLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_forced_org_id")
	public AdOrg getAdOrgByAdForcedOrgId() {
		return this.adOrgByAdForcedOrgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrgByAdOrgId() {
		return this.adOrgByAdOrgId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartner")
	public Set<AdOrginfo> getAdOrginfos() {
		return this.adOrginfos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bpartner_parent_id")
	public CBpartner getCBpartnerByBpartnerParentId() {
		return this.CBpartnerByBpartnerParentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salesrep_id")
	public CBpartner getCBpartnerBySalesrepId() {
		return this.CBpartnerBySalesrepId;
	}

	@Id
	@Column(name = "c_bpartner_id", unique = true, nullable = false, length = 32)
	public String getCBpartnerId() {
		return this.CBpartnerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartner")
	public Set<CBpartnerLocation> getCBpartnerLocations() {
		return this.CBpartnerLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerByBpartnerParentId")
	public Set<CBpartner> getCBpartnersForBpartnerParentId() {
		return this.CBpartnersForBpartnerParentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerBySalesrepId")
	public Set<CBpartner> getCBpartnersForSalesrepId() {
		return this.CBpartnersForSalesrepId;
	}

	@Column(name = "c_bp_group_id", nullable = false, length = 32)
	public String getCBpGroupId() {
		return this.CBpGroupId;
	}

	@Column(name = "c_greeting_id", length = 32)
	public String getCGreetingId() {
		return this.CGreetingId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartner")
	public Set<CInvoice> getCInvoices() {
		return this.CInvoices;
	}

	@Column(name = "c_invoiceschedule_id", length = 32)
	public String getCInvoicescheduleId() {
		return this.CInvoicescheduleId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerByCBpartnerId")
	public Set<COrder> getCOrdersForCBpartnerId() {
		return this.COrdersForCBpartnerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerByDropshipBpartnerId")
	public Set<COrder> getCOrdersForDropshipBpartnerId() {
		return this.COrdersForDropshipBpartnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_paymentterm_id")
	public CPaymentterm getCPaymenttermByCPaymenttermId() {
		return this.CPaymenttermByCPaymenttermId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_paymentterm_id")
	public CPaymentterm getCPaymenttermByPoPaymenttermId() {
		return this.CPaymenttermByPoPaymenttermId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Column(name = "c_salary_category_id", length = 32)
	public String getCSalaryCategoryId() {
		return this.CSalaryCategoryId;
	}

	@Column(name = "deliveryrule", length = 60)
	public String getDeliveryrule() {
		return this.deliveryrule;
	}

	@Column(name = "deliveryviarule", length = 60)
	public String getDeliveryviarule() {
		return this.deliveryviarule;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@Column(name = "documentcopies", precision = 10, scale = 0)
	public Long getDocumentcopies() {
		return this.documentcopies;
	}

	@Column(name = "duns", length = 11)
	public String getDuns() {
		return this.duns;
	}

	@Column(name = "fin_financial_account_id", length = 32)
	public String getFinFinancialAccountId() {
		return this.finFinancialAccountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fin_paymentmethod_id")
	public FinPaymentmethod getFinPaymentmethodByFinPaymentmethodId() {
		return this.finPaymentmethodByFinPaymentmethodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_paymentmethod_id")
	public FinPaymentmethod getFinPaymentmethodByPoPaymentmethodId() {
		return this.finPaymentmethodByPoPaymentmethodId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "firstsale", length = 29)
	public Date getFirstsale() {
		return this.firstsale;
	}

	@Column(name = "fiscalcode", length = 16)
	public String getFiscalcode() {
		return this.fiscalcode;
	}

	@Column(name = "fixmonthday", precision = 10, scale = 0)
	public Long getFixmonthday() {
		return this.fixmonthday;
	}

	@Column(name = "fixmonthday2", precision = 10, scale = 0)
	public Long getFixmonthday2() {
		return this.fixmonthday2;
	}

	@Column(name = "fixmonthday3", precision = 10, scale = 0)
	public Long getFixmonthday3() {
		return this.fixmonthday3;
	}

	@Column(name = "invoicegrouping", length = 60)
	public String getInvoicegrouping() {
		return this.invoicegrouping;
	}

	@Column(name = "invoice_printformat", length = 60)
	public String getInvoicePrintformat() {
		return this.invoicePrintformat;
	}

	@Column(name = "invoicerule", length = 60)
	public String getInvoicerule() {
		return this.invoicerule;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "iscustomer", nullable = false, length = 1)
	public char getIscustomer() {
		return this.iscustomer;
	}

	@Column(name = "isdiscountprinted", length = 1)
	public Character getIsdiscountprinted() {
		return this.isdiscountprinted;
	}

	@Column(name = "isemployee", nullable = false, length = 1)
	public char getIsemployee() {
		return this.isemployee;
	}

	@Column(name = "isofiscalcode", length = 2)
	public String getIsofiscalcode() {
		return this.isofiscalcode;
	}

	@Column(name = "isonetime", nullable = false, length = 1)
	public char getIsonetime() {
		return this.isonetime;
	}

	@Column(name = "isprospect", nullable = false, length = 1)
	public char getIsprospect() {
		return this.isprospect;
	}

	@Column(name = "issalesrep", nullable = false, length = 1)
	public char getIssalesrep() {
		return this.issalesrep;
	}

	@Column(name = "issummary", nullable = false, length = 1)
	public char getIssummary() {
		return this.issummary;
	}

	@Column(name = "istaxexempt", length = 1)
	public Character getIstaxexempt() {
		return this.istaxexempt;
	}

	@Column(name = "isvendor", nullable = false, length = 1)
	public char getIsvendor() {
		return this.isvendor;
	}

	@Column(name = "isworker", length = 1)
	public Character getIsworker() {
		return this.isworker;
	}

	@Column(name = "last_days", precision = 10, scale = 0)
	public Long getLastDays() {
		return this.lastDays;
	}

	@Column(name = "m_pricelist_id", length = 32)
	public String getMPricelistId() {
		return this.MPricelistId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartner")
	public Set<MProduct> getMProducts() {
		return this.MProducts;
	}

	@Column(name = "naics", length = 6)
	public String getNaics() {
		return this.naics;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "name2", length = 60)
	public String getName2() {
		return this.name2;
	}

	@Column(name = "numberemployees", precision = 10, scale = 0)
	public Long getNumberemployees() {
		return this.numberemployees;
	}

	@Column(name = "paymentrule", length = 60)
	public String getPaymentrule() {
		return this.paymentrule;
	}

	@Column(name = "paymentrulepo", length = 60)
	public String getPaymentrulepo() {
		return this.paymentrulepo;
	}

	@Column(name = "po_bankaccount_id", length = 32)
	public String getPoBankaccountId() {
		return this.poBankaccountId;
	}

	@Column(name = "po_bp_taxcategory_id", length = 32)
	public String getPoBpTaxcategoryId() {
		return this.poBpTaxcategoryId;
	}

	@Column(name = "po_c_incoterms_id", length = 32)
	public String getPoCIncotermsId() {
		return this.poCIncotermsId;
	}

	@Column(name = "po_financial_account_id", length = 32)
	public String getPoFinancialAccountId() {
		return this.poFinancialAccountId;
	}

	@Column(name = "po_fixmonthday", precision = 10, scale = 0)
	public Long getPoFixmonthday() {
		return this.poFixmonthday;
	}

	@Column(name = "po_fixmonthday2", precision = 10, scale = 0)
	public Long getPoFixmonthday2() {
		return this.poFixmonthday2;
	}

	@Column(name = "po_fixmonthday3", precision = 10, scale = 0)
	public Long getPoFixmonthday3() {
		return this.poFixmonthday3;
	}

	@Column(name = "po_pricelist_id", length = 32)
	public String getPoPricelistId() {
		return this.poPricelistId;
	}

	@Column(name = "poreference", length = 20)
	public String getPoreference() {
		return this.poreference;
	}

	@Column(name = "potentiallifetimevalue", precision = 131089, scale = 0)
	public BigDecimal getPotentiallifetimevalue() {
		return this.potentiallifetimevalue;
	}

	@Column(name = "rating", length = 1)
	public Character getRating() {
		return this.rating;
	}

	@Column(name = "referenceno", length = 40)
	public String getReferenceno() {
		return this.referenceno;
	}

	@Column(name = "salesvolume", precision = 10, scale = 0)
	public Long getSalesvolume() {
		return this.salesvolume;
	}

	@Column(name = "shareofcustomer", precision = 10, scale = 0)
	public Long getShareofcustomer() {
		return this.shareofcustomer;
	}

	@Column(name = "showpriceinorder", nullable = false, length = 1)
	public char getShowpriceinorder() {
		return this.showpriceinorder;
	}

	@Column(name = "so_bankaccount_id", length = 32)
	public String getSoBankaccountId() {
		return this.soBankaccountId;
	}

	@Column(name = "so_bp_taxcategory_id", length = 32)
	public String getSoBpTaxcategoryId() {
		return this.soBpTaxcategoryId;
	}

	@Column(name = "so_c_incoterms_id", length = 32)
	public String getSoCIncotermsId() {
		return this.soCIncotermsId;
	}

	@Column(name = "so_creditlimit", precision = 131089, scale = 0)
	public BigDecimal getSoCreditlimit() {
		return this.soCreditlimit;
	}

	@Column(name = "socreditstatus", length = 60)
	public String getSocreditstatus() {
		return this.socreditstatus;
	}

	@Column(name = "so_creditused", precision = 131089, scale = 0)
	public BigDecimal getSoCreditused() {
		return this.soCreditused;
	}

	@Column(name = "so_description")
	public String getSoDescription() {
		return this.soDescription;
	}

	@Column(name = "taxid", length = 20)
	public String getTaxid() {
		return this.taxid;
	}

	@Column(name = "upc", length = 30)
	public String getUpc() {
		return this.upc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "url", length = 120)
	public String getUrl() {
		return this.url;
	}

	@Column(name = "value", nullable = false, length = 40)
	public String getValue() {
		return this.value;
	}

	public void setAcqusitioncost(BigDecimal acqusitioncost) {
		this.acqusitioncost = acqusitioncost;
	}

	public void setActuallifetimevalue(BigDecimal actuallifetimevalue) {
		this.actuallifetimevalue = actuallifetimevalue;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdLanguage(String adLanguage) {
		this.adLanguage = adLanguage;
	}

	public void setAdOrgByAdForcedOrgId(AdOrg adOrgByAdForcedOrgId) {
		this.adOrgByAdForcedOrgId = adOrgByAdForcedOrgId;
	}

	public void setAdOrgByAdOrgId(AdOrg adOrgByAdOrgId) {
		this.adOrgByAdOrgId = adOrgByAdOrgId;
	}

	public void setAdOrginfos(Set<AdOrginfo> adOrginfos) {
		this.adOrginfos = adOrginfos;
	}

	public void setCBpartnerByBpartnerParentId(
			CBpartner CBpartnerByBpartnerParentId) {
		this.CBpartnerByBpartnerParentId = CBpartnerByBpartnerParentId;
	}

	public void setCBpartnerBySalesrepId(CBpartner CBpartnerBySalesrepId) {
		this.CBpartnerBySalesrepId = CBpartnerBySalesrepId;
	}

	public void setCBpartnerId(String CBpartnerId) {
		this.CBpartnerId = CBpartnerId;
	}

	public void setCBpartnerLocations(Set<CBpartnerLocation> CBpartnerLocations) {
		this.CBpartnerLocations = CBpartnerLocations;
	}

	public void setCBpartnersForBpartnerParentId(
			Set<CBpartner> CBpartnersForBpartnerParentId) {
		this.CBpartnersForBpartnerParentId = CBpartnersForBpartnerParentId;
	}

	public void setCBpartnersForSalesrepId(
			Set<CBpartner> CBpartnersForSalesrepId) {
		this.CBpartnersForSalesrepId = CBpartnersForSalesrepId;
	}

	public void setCBpGroupId(String CBpGroupId) {
		this.CBpGroupId = CBpGroupId;
	}

	public void setCGreetingId(String CGreetingId) {
		this.CGreetingId = CGreetingId;
	}

	public void setCInvoices(Set<CInvoice> CInvoices) {
		this.CInvoices = CInvoices;
	}

	public void setCInvoicescheduleId(String CInvoicescheduleId) {
		this.CInvoicescheduleId = CInvoicescheduleId;
	}

	public void setCOrdersForCBpartnerId(Set<COrder> COrdersForCBpartnerId) {
		this.COrdersForCBpartnerId = COrdersForCBpartnerId;
	}

	public void setCOrdersForDropshipBpartnerId(
			Set<COrder> COrdersForDropshipBpartnerId) {
		this.COrdersForDropshipBpartnerId = COrdersForDropshipBpartnerId;
	}

	public void setCPaymenttermByCPaymenttermId(
			CPaymentterm CPaymenttermByCPaymenttermId) {
		this.CPaymenttermByCPaymenttermId = CPaymenttermByCPaymenttermId;
	}

	public void setCPaymenttermByPoPaymenttermId(
			CPaymentterm CPaymenttermByPoPaymenttermId) {
		this.CPaymenttermByPoPaymenttermId = CPaymenttermByPoPaymenttermId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCSalaryCategoryId(String CSalaryCategoryId) {
		this.CSalaryCategoryId = CSalaryCategoryId;
	}

	public void setDeliveryrule(String deliveryrule) {
		this.deliveryrule = deliveryrule;
	}

	public void setDeliveryviarule(String deliveryviarule) {
		this.deliveryviarule = deliveryviarule;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDocumentcopies(Long documentcopies) {
		this.documentcopies = documentcopies;
	}

	public void setDuns(String duns) {
		this.duns = duns;
	}

	public void setFinFinancialAccountId(String finFinancialAccountId) {
		this.finFinancialAccountId = finFinancialAccountId;
	}

	public void setFinPaymentmethodByFinPaymentmethodId(
			FinPaymentmethod finPaymentmethodByFinPaymentmethodId) {
		this.finPaymentmethodByFinPaymentmethodId = finPaymentmethodByFinPaymentmethodId;
	}

	public void setFinPaymentmethodByPoPaymentmethodId(
			FinPaymentmethod finPaymentmethodByPoPaymentmethodId) {
		this.finPaymentmethodByPoPaymentmethodId = finPaymentmethodByPoPaymentmethodId;
	}

	public void setFirstsale(Date firstsale) {
		this.firstsale = firstsale;
	}

	public void setFiscalcode(String fiscalcode) {
		this.fiscalcode = fiscalcode;
	}

	public void setFixmonthday(Long fixmonthday) {
		this.fixmonthday = fixmonthday;
	}

	public void setFixmonthday2(Long fixmonthday2) {
		this.fixmonthday2 = fixmonthday2;
	}

	public void setFixmonthday3(Long fixmonthday3) {
		this.fixmonthday3 = fixmonthday3;
	}

	public void setInvoicegrouping(String invoicegrouping) {
		this.invoicegrouping = invoicegrouping;
	}

	public void setInvoicePrintformat(String invoicePrintformat) {
		this.invoicePrintformat = invoicePrintformat;
	}

	public void setInvoicerule(String invoicerule) {
		this.invoicerule = invoicerule;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIscustomer(char iscustomer) {
		this.iscustomer = iscustomer;
	}

	public void setIsdiscountprinted(Character isdiscountprinted) {
		this.isdiscountprinted = isdiscountprinted;
	}

	public void setIsemployee(char isemployee) {
		this.isemployee = isemployee;
	}

	public void setIsofiscalcode(String isofiscalcode) {
		this.isofiscalcode = isofiscalcode;
	}

	public void setIsonetime(char isonetime) {
		this.isonetime = isonetime;
	}

	public void setIsprospect(char isprospect) {
		this.isprospect = isprospect;
	}

	public void setIssalesrep(char issalesrep) {
		this.issalesrep = issalesrep;
	}

	public void setIssummary(char issummary) {
		this.issummary = issummary;
	}

	public void setIstaxexempt(Character istaxexempt) {
		this.istaxexempt = istaxexempt;
	}

	public void setIsvendor(char isvendor) {
		this.isvendor = isvendor;
	}

	public void setIsworker(Character isworker) {
		this.isworker = isworker;
	}

	public void setLastDays(Long lastDays) {
		this.lastDays = lastDays;
	}

	public void setMPricelistId(String MPricelistId) {
		this.MPricelistId = MPricelistId;
	}

	public void setMProducts(Set<MProduct> MProducts) {
		this.MProducts = MProducts;
	}

	public void setNaics(String naics) {
		this.naics = naics;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	public void setNumberemployees(Long numberemployees) {
		this.numberemployees = numberemployees;
	}

	public void setPaymentrule(String paymentrule) {
		this.paymentrule = paymentrule;
	}

	public void setPaymentrulepo(String paymentrulepo) {
		this.paymentrulepo = paymentrulepo;
	}

	public void setPoBankaccountId(String poBankaccountId) {
		this.poBankaccountId = poBankaccountId;
	}

	public void setPoBpTaxcategoryId(String poBpTaxcategoryId) {
		this.poBpTaxcategoryId = poBpTaxcategoryId;
	}

	public void setPoCIncotermsId(String poCIncotermsId) {
		this.poCIncotermsId = poCIncotermsId;
	}

	public void setPoFinancialAccountId(String poFinancialAccountId) {
		this.poFinancialAccountId = poFinancialAccountId;
	}

	public void setPoFixmonthday(Long poFixmonthday) {
		this.poFixmonthday = poFixmonthday;
	}

	public void setPoFixmonthday2(Long poFixmonthday2) {
		this.poFixmonthday2 = poFixmonthday2;
	}

	public void setPoFixmonthday3(Long poFixmonthday3) {
		this.poFixmonthday3 = poFixmonthday3;
	}

	public void setPoPricelistId(String poPricelistId) {
		this.poPricelistId = poPricelistId;
	}

	public void setPoreference(String poreference) {
		this.poreference = poreference;
	}

	public void setPotentiallifetimevalue(BigDecimal potentiallifetimevalue) {
		this.potentiallifetimevalue = potentiallifetimevalue;
	}

	public void setRating(Character rating) {
		this.rating = rating;
	}

	public void setReferenceno(String referenceno) {
		this.referenceno = referenceno;
	}

	public void setSalesvolume(Long salesvolume) {
		this.salesvolume = salesvolume;
	}

	public void setShareofcustomer(Long shareofcustomer) {
		this.shareofcustomer = shareofcustomer;
	}

	public void setShowpriceinorder(char showpriceinorder) {
		this.showpriceinorder = showpriceinorder;
	}

	public void setSoBankaccountId(String soBankaccountId) {
		this.soBankaccountId = soBankaccountId;
	}

	public void setSoBpTaxcategoryId(String soBpTaxcategoryId) {
		this.soBpTaxcategoryId = soBpTaxcategoryId;
	}

	public void setSoCIncotermsId(String soCIncotermsId) {
		this.soCIncotermsId = soCIncotermsId;
	}

	public void setSoCreditlimit(BigDecimal soCreditlimit) {
		this.soCreditlimit = soCreditlimit;
	}

	public void setSocreditstatus(String socreditstatus) {
		this.socreditstatus = socreditstatus;
	}

	public void setSoCreditused(BigDecimal soCreditused) {
		this.soCreditused = soCreditused;
	}

	public void setSoDescription(String soDescription) {
		this.soDescription = soDescription;
	}

	public void setTaxid(String taxid) {
		this.taxid = taxid;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
