package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CBpartnerLocation generated by hbm2java
 */
@Entity
@Table(name = "c_bpartner_location", schema = "public")
public class CBpartnerLocation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CBpartnerLocationId;
	private AdOrg adOrg;
	private CBpartner CBpartner;
	private CLocation CLocation;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String name;
	private char isbillto;
	private char isshipto;
	private char ispayfrom;
	private char isremitto;
	private String phone;
	private String phone2;
	private String fax;
	private String CSalesregionId;
	private char istaxlocation;
	private String upc;
	private Set<COrder> COrdersForDropshipLocationId = new HashSet<COrder>(0);
	private Set<COrder> COrdersForCBpartnerLocationId = new HashSet<COrder>(0);
	private Set<COrder> COrdersForDeliveryLocationId = new HashSet<COrder>(0);
	private Set<CInvoice> CInvoices = new HashSet<CInvoice>(0);
	private Set<COrder> COrdersForBilltoId = new HashSet<COrder>(0);

	public CBpartnerLocation() {
	}

	public CBpartnerLocation(String CBpartnerLocationId, AdOrg adOrg,
			CBpartner CBpartner, CLocation CLocation, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String name, char isbillto, char isshipto,
			char ispayfrom, char isremitto, String phone, String phone2,
			String fax, String CSalesregionId, char istaxlocation, String upc,
			Set<COrder> COrdersForDropshipLocationId,
			Set<COrder> COrdersForCBpartnerLocationId,
			Set<COrder> COrdersForDeliveryLocationId, Set<CInvoice> CInvoices,
			Set<COrder> COrdersForBilltoId) {
		this.CBpartnerLocationId = CBpartnerLocationId;
		this.adOrg = adOrg;
		this.CBpartner = CBpartner;
		this.CLocation = CLocation;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
		this.isbillto = isbillto;
		this.isshipto = isshipto;
		this.ispayfrom = ispayfrom;
		this.isremitto = isremitto;
		this.phone = phone;
		this.phone2 = phone2;
		this.fax = fax;
		this.CSalesregionId = CSalesregionId;
		this.istaxlocation = istaxlocation;
		this.upc = upc;
		this.COrdersForDropshipLocationId = COrdersForDropshipLocationId;
		this.COrdersForCBpartnerLocationId = COrdersForCBpartnerLocationId;
		this.COrdersForDeliveryLocationId = COrdersForDeliveryLocationId;
		this.CInvoices = CInvoices;
		this.COrdersForBilltoId = COrdersForBilltoId;
	}

	public CBpartnerLocation(String CBpartnerLocationId, AdOrg adOrg,
			CBpartner CBpartner, String adClientId, char isactive,
			Date created, String createdby, Date updated, String updatedby,
			String name, char isbillto, char isshipto, char ispayfrom,
			char isremitto, char istaxlocation) {
		this.CBpartnerLocationId = CBpartnerLocationId;
		this.adOrg = adOrg;
		this.CBpartner = CBpartner;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
		this.isbillto = isbillto;
		this.isshipto = isshipto;
		this.ispayfrom = ispayfrom;
		this.isremitto = isremitto;
		this.istaxlocation = istaxlocation;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_bpartner_id", nullable = false)
	public CBpartner getCBpartner() {
		return this.CBpartner;
	}

	@Id
	@Column(name = "c_bpartner_location_id", unique = true, nullable = false, length = 32)
	public String getCBpartnerLocationId() {
		return this.CBpartnerLocationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerLocation")
	public Set<CInvoice> getCInvoices() {
		return this.CInvoices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_location_id")
	public CLocation getCLocation() {
		return this.CLocation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerLocationByBilltoId")
	public Set<COrder> getCOrdersForBilltoId() {
		return this.COrdersForBilltoId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerLocationByCBpartnerLocationId")
	public Set<COrder> getCOrdersForCBpartnerLocationId() {
		return this.COrdersForCBpartnerLocationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerLocationByDeliveryLocationId")
	public Set<COrder> getCOrdersForDeliveryLocationId() {
		return this.COrdersForDeliveryLocationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CBpartnerLocationByDropshipLocationId")
	public Set<COrder> getCOrdersForDropshipLocationId() {
		return this.COrdersForDropshipLocationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Column(name = "c_salesregion_id", length = 32)
	public String getCSalesregionId() {
		return this.CSalesregionId;
	}

	@Column(name = "fax", length = 40)
	public String getFax() {
		return this.fax;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isbillto", nullable = false, length = 1)
	public char getIsbillto() {
		return this.isbillto;
	}

	@Column(name = "ispayfrom", nullable = false, length = 1)
	public char getIspayfrom() {
		return this.ispayfrom;
	}

	@Column(name = "isremitto", nullable = false, length = 1)
	public char getIsremitto() {
		return this.isremitto;
	}

	@Column(name = "isshipto", nullable = false, length = 1)
	public char getIsshipto() {
		return this.isshipto;
	}

	@Column(name = "istaxlocation", nullable = false, length = 1)
	public char getIstaxlocation() {
		return this.istaxlocation;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "phone", length = 40)
	public String getPhone() {
		return this.phone;
	}

	@Column(name = "phone2", length = 40)
	public String getPhone2() {
		return this.phone2;
	}

	@Column(name = "upc", length = 30)
	public String getUpc() {
		return this.upc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setCBpartner(CBpartner CBpartner) {
		this.CBpartner = CBpartner;
	}

	public void setCBpartnerLocationId(String CBpartnerLocationId) {
		this.CBpartnerLocationId = CBpartnerLocationId;
	}

	public void setCInvoices(Set<CInvoice> CInvoices) {
		this.CInvoices = CInvoices;
	}

	public void setCLocation(CLocation CLocation) {
		this.CLocation = CLocation;
	}

	public void setCOrdersForBilltoId(Set<COrder> COrdersForBilltoId) {
		this.COrdersForBilltoId = COrdersForBilltoId;
	}

	public void setCOrdersForCBpartnerLocationId(
			Set<COrder> COrdersForCBpartnerLocationId) {
		this.COrdersForCBpartnerLocationId = COrdersForCBpartnerLocationId;
	}

	public void setCOrdersForDeliveryLocationId(
			Set<COrder> COrdersForDeliveryLocationId) {
		this.COrdersForDeliveryLocationId = COrdersForDeliveryLocationId;
	}

	public void setCOrdersForDropshipLocationId(
			Set<COrder> COrdersForDropshipLocationId) {
		this.COrdersForDropshipLocationId = COrdersForDropshipLocationId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCSalesregionId(String CSalesregionId) {
		this.CSalesregionId = CSalesregionId;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsbillto(char isbillto) {
		this.isbillto = isbillto;
	}

	public void setIspayfrom(char ispayfrom) {
		this.ispayfrom = ispayfrom;
	}

	public void setIsremitto(char isremitto) {
		this.isremitto = isremitto;
	}

	public void setIsshipto(char isshipto) {
		this.isshipto = isshipto;
	}

	public void setIstaxlocation(char istaxlocation) {
		this.istaxlocation = istaxlocation;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

}
