package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CCurrency generated by hbm2java
 */
@Entity
@Table(name = "c_currency", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "iso_code"))
public class CCurrency implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CCurrencyId;
	private AdOrg adOrg;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String isoCode;
	private String cursymbol;
	private String description;
	private long stdprecision;
	private long costingprecision;
	private long priceprecision;
	private Character issymbolrightside;
	private Set<CInvoice> CInvoices = new HashSet<CInvoice>(0);
	private Set<CCountry> CCountries = new HashSet<CCountry>(0);
	private Set<COrder> COrders = new HashSet<COrder>(0);
	private Set<AdOrg> adOrgs = new HashSet<AdOrg>(0);

	public CCurrency() {
	}

	public CCurrency(String CCurrencyId, AdOrg adOrg, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String isoCode, String description,
			long stdprecision, long costingprecision, long priceprecision) {
		this.CCurrencyId = CCurrencyId;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.isoCode = isoCode;
		this.description = description;
		this.stdprecision = stdprecision;
		this.costingprecision = costingprecision;
		this.priceprecision = priceprecision;
	}

	public CCurrency(String CCurrencyId, AdOrg adOrg, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String isoCode, String cursymbol,
			String description, long stdprecision, long costingprecision,
			long priceprecision, Character issymbolrightside,
			Set<CInvoice> CInvoices, Set<CCountry> CCountries,
			Set<COrder> COrders, Set<AdOrg> adOrgs) {
		this.CCurrencyId = CCurrencyId;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.isoCode = isoCode;
		this.cursymbol = cursymbol;
		this.description = description;
		this.stdprecision = stdprecision;
		this.costingprecision = costingprecision;
		this.priceprecision = priceprecision;
		this.issymbolrightside = issymbolrightside;
		this.CInvoices = CInvoices;
		this.CCountries = CCountries;
		this.COrders = COrders;
		this.adOrgs = adOrgs;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CCurrency")
	public Set<AdOrg> getAdOrgs() {
		return this.adOrgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CCurrency")
	public Set<CCountry> getCCountries() {
		return this.CCountries;
	}

	@Id
	@Column(name = "c_currency_id", unique = true, nullable = false, length = 32)
	public String getCCurrencyId() {
		return this.CCurrencyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CCurrency")
	public Set<CInvoice> getCInvoices() {
		return this.CInvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CCurrency")
	public Set<COrder> getCOrders() {
		return this.COrders;
	}

	@Column(name = "costingprecision", nullable = false, precision = 10, scale = 0)
	public long getCostingprecision() {
		return this.costingprecision;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Column(name = "cursymbol", length = 10)
	public String getCursymbol() {
		return this.cursymbol;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "iso_code", unique = true, nullable = false, length = 3)
	public String getIsoCode() {
		return this.isoCode;
	}

	@Column(name = "issymbolrightside", length = 1)
	public Character getIssymbolrightside() {
		return this.issymbolrightside;
	}

	@Column(name = "priceprecision", nullable = false, precision = 10, scale = 0)
	public long getPriceprecision() {
		return this.priceprecision;
	}

	@Column(name = "stdprecision", nullable = false, precision = 10, scale = 0)
	public long getStdprecision() {
		return this.stdprecision;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setAdOrgs(Set<AdOrg> adOrgs) {
		this.adOrgs = adOrgs;
	}

	public void setCCountries(Set<CCountry> CCountries) {
		this.CCountries = CCountries;
	}

	public void setCCurrencyId(String CCurrencyId) {
		this.CCurrencyId = CCurrencyId;
	}

	public void setCInvoices(Set<CInvoice> CInvoices) {
		this.CInvoices = CInvoices;
	}

	public void setCOrders(Set<COrder> COrders) {
		this.COrders = COrders;
	}

	public void setCostingprecision(long costingprecision) {
		this.costingprecision = costingprecision;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCursymbol(String cursymbol) {
		this.cursymbol = cursymbol;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsoCode(String isoCode) {
		this.isoCode = isoCode;
	}

	public void setIssymbolrightside(Character issymbolrightside) {
		this.issymbolrightside = issymbolrightside;
	}

	public void setPriceprecision(long priceprecision) {
		this.priceprecision = priceprecision;
	}

	public void setStdprecision(long stdprecision) {
		this.stdprecision = stdprecision;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

}
