package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CDoctype generated by hbm2java
 */
@Entity
@Table(name = "c_doctype", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ad_client_id", "ad_org_id", "name" }))
public class CDoctype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CDoctypeId;
	private CDoctype CDoctypeByCDoctypeorderId;
	private AdOrg adOrg;
	private CDoctype CDoctypeByCDoctypeinvoiceId;
	private CDoctype CDoctypeByCDoctypeshipmentId;
	private CDoctype CDoctypeByCDoctypeReversedId;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String name;
	private String printname;
	private String description;
	private String docbasetype;
	private char issotrx;
	private String docsubtypeso;
	private char isdocnocontrolled;
	private String docnosequenceId;
	private String glCategoryId;
	private String documentnote;
	private char isdefault;
	private long documentcopies;
	private String adTableId;
	private char orgfiltered;
	private char isexpense;
	private char isreversal;
	private char isreturn;
	private Set<CDoctype> CDoctypesForCDoctypeorderId = new HashSet<CDoctype>(0);
	private Set<CDoctype> CDoctypesForCDoctypeinvoiceId = new HashSet<CDoctype>(
			0);
	private Set<CInvoice> CInvoicesForCDoctypeId = new HashSet<CInvoice>(0);
	private Set<CDoctype> CDoctypesForCDoctypeshipmentId = new HashSet<CDoctype>(
			0);
	private Set<COrder> COrdersForCDoctypetargetId = new HashSet<COrder>(0);
	private Set<CInvoice> CInvoicesForCDoctypetargetId = new HashSet<CInvoice>(
			0);
	private Set<CDoctype> CDoctypesForCDoctypeReversedId = new HashSet<CDoctype>(
			0);
	private Set<COrder> COrdersForCDoctypeId = new HashSet<COrder>(0);

	public CDoctype() {
	}

	public CDoctype(String CDoctypeId, AdOrg adOrg, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String name, String printname,
			String docbasetype, char issotrx, char isdocnocontrolled,
			String glCategoryId, char isdefault, long documentcopies,
			char orgfiltered, char isexpense, char isreversal, char isreturn) {
		this.CDoctypeId = CDoctypeId;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
		this.printname = printname;
		this.docbasetype = docbasetype;
		this.issotrx = issotrx;
		this.isdocnocontrolled = isdocnocontrolled;
		this.glCategoryId = glCategoryId;
		this.isdefault = isdefault;
		this.documentcopies = documentcopies;
		this.orgfiltered = orgfiltered;
		this.isexpense = isexpense;
		this.isreversal = isreversal;
		this.isreturn = isreturn;
	}

	public CDoctype(String CDoctypeId, CDoctype CDoctypeByCDoctypeorderId,
			AdOrg adOrg, CDoctype CDoctypeByCDoctypeinvoiceId,
			CDoctype CDoctypeByCDoctypeshipmentId,
			CDoctype CDoctypeByCDoctypeReversedId, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String name, String printname,
			String description, String docbasetype, char issotrx,
			String docsubtypeso, char isdocnocontrolled,
			String docnosequenceId, String glCategoryId, String documentnote,
			char isdefault, long documentcopies, String adTableId,
			char orgfiltered, char isexpense, char isreversal, char isreturn,
			Set<CDoctype> CDoctypesForCDoctypeorderId,
			Set<CDoctype> CDoctypesForCDoctypeinvoiceId,
			Set<CInvoice> CInvoicesForCDoctypeId,
			Set<CDoctype> CDoctypesForCDoctypeshipmentId,
			Set<COrder> COrdersForCDoctypetargetId,
			Set<CInvoice> CInvoicesForCDoctypetargetId,
			Set<CDoctype> CDoctypesForCDoctypeReversedId,
			Set<COrder> COrdersForCDoctypeId) {
		this.CDoctypeId = CDoctypeId;
		this.CDoctypeByCDoctypeorderId = CDoctypeByCDoctypeorderId;
		this.adOrg = adOrg;
		this.CDoctypeByCDoctypeinvoiceId = CDoctypeByCDoctypeinvoiceId;
		this.CDoctypeByCDoctypeshipmentId = CDoctypeByCDoctypeshipmentId;
		this.CDoctypeByCDoctypeReversedId = CDoctypeByCDoctypeReversedId;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
		this.printname = printname;
		this.description = description;
		this.docbasetype = docbasetype;
		this.issotrx = issotrx;
		this.docsubtypeso = docsubtypeso;
		this.isdocnocontrolled = isdocnocontrolled;
		this.docnosequenceId = docnosequenceId;
		this.glCategoryId = glCategoryId;
		this.documentnote = documentnote;
		this.isdefault = isdefault;
		this.documentcopies = documentcopies;
		this.adTableId = adTableId;
		this.orgfiltered = orgfiltered;
		this.isexpense = isexpense;
		this.isreversal = isreversal;
		this.isreturn = isreturn;
		this.CDoctypesForCDoctypeorderId = CDoctypesForCDoctypeorderId;
		this.CDoctypesForCDoctypeinvoiceId = CDoctypesForCDoctypeinvoiceId;
		this.CInvoicesForCDoctypeId = CInvoicesForCDoctypeId;
		this.CDoctypesForCDoctypeshipmentId = CDoctypesForCDoctypeshipmentId;
		this.COrdersForCDoctypetargetId = COrdersForCDoctypetargetId;
		this.CInvoicesForCDoctypetargetId = CInvoicesForCDoctypetargetId;
		this.CDoctypesForCDoctypeReversedId = CDoctypesForCDoctypeReversedId;
		this.COrdersForCDoctypeId = COrdersForCDoctypeId;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@Column(name = "ad_table_id", length = 32)
	public String getAdTableId() {
		return this.adTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_doctypeinvoice_id")
	public CDoctype getCDoctypeByCDoctypeinvoiceId() {
		return this.CDoctypeByCDoctypeinvoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_doctypeorder_id")
	public CDoctype getCDoctypeByCDoctypeorderId() {
		return this.CDoctypeByCDoctypeorderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_doctype_reversed_id")
	public CDoctype getCDoctypeByCDoctypeReversedId() {
		return this.CDoctypeByCDoctypeReversedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_doctypeshipment_id")
	public CDoctype getCDoctypeByCDoctypeshipmentId() {
		return this.CDoctypeByCDoctypeshipmentId;
	}

	@Id
	@Column(name = "c_doctype_id", unique = true, nullable = false, length = 32)
	public String getCDoctypeId() {
		return this.CDoctypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypeinvoiceId")
	public Set<CDoctype> getCDoctypesForCDoctypeinvoiceId() {
		return this.CDoctypesForCDoctypeinvoiceId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypeorderId")
	public Set<CDoctype> getCDoctypesForCDoctypeorderId() {
		return this.CDoctypesForCDoctypeorderId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypeReversedId")
	public Set<CDoctype> getCDoctypesForCDoctypeReversedId() {
		return this.CDoctypesForCDoctypeReversedId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypeshipmentId")
	public Set<CDoctype> getCDoctypesForCDoctypeshipmentId() {
		return this.CDoctypesForCDoctypeshipmentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypeId")
	public Set<CInvoice> getCInvoicesForCDoctypeId() {
		return this.CInvoicesForCDoctypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypetargetId")
	public Set<CInvoice> getCInvoicesForCDoctypetargetId() {
		return this.CInvoicesForCDoctypetargetId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypeId")
	public Set<COrder> getCOrdersForCDoctypeId() {
		return this.COrdersForCDoctypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CDoctypeByCDoctypetargetId")
	public Set<COrder> getCOrdersForCDoctypetargetId() {
		return this.COrdersForCDoctypetargetId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@Column(name = "docbasetype", nullable = false, length = 60)
	public String getDocbasetype() {
		return this.docbasetype;
	}

	@Column(name = "docnosequence_id", length = 32)
	public String getDocnosequenceId() {
		return this.docnosequenceId;
	}

	@Column(name = "docsubtypeso", length = 60)
	public String getDocsubtypeso() {
		return this.docsubtypeso;
	}

	@Column(name = "documentcopies", nullable = false, precision = 10, scale = 0)
	public long getDocumentcopies() {
		return this.documentcopies;
	}

	@Column(name = "documentnote", length = 2000)
	public String getDocumentnote() {
		return this.documentnote;
	}

	@Column(name = "gl_category_id", nullable = false, length = 32)
	public String getGlCategoryId() {
		return this.glCategoryId;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isdefault", nullable = false, length = 1)
	public char getIsdefault() {
		return this.isdefault;
	}

	@Column(name = "isdocnocontrolled", nullable = false, length = 1)
	public char getIsdocnocontrolled() {
		return this.isdocnocontrolled;
	}

	@Column(name = "isexpense", nullable = false, length = 1)
	public char getIsexpense() {
		return this.isexpense;
	}

	@Column(name = "isreturn", nullable = false, length = 1)
	public char getIsreturn() {
		return this.isreturn;
	}

	@Column(name = "isreversal", nullable = false, length = 1)
	public char getIsreversal() {
		return this.isreversal;
	}

	@Column(name = "issotrx", nullable = false, length = 1)
	public char getIssotrx() {
		return this.issotrx;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "orgfiltered", nullable = false, length = 1)
	public char getOrgfiltered() {
		return this.orgfiltered;
	}

	@Column(name = "printname", nullable = false, length = 60)
	public String getPrintname() {
		return this.printname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setAdTableId(String adTableId) {
		this.adTableId = adTableId;
	}

	public void setCDoctypeByCDoctypeinvoiceId(
			CDoctype CDoctypeByCDoctypeinvoiceId) {
		this.CDoctypeByCDoctypeinvoiceId = CDoctypeByCDoctypeinvoiceId;
	}

	public void setCDoctypeByCDoctypeorderId(CDoctype CDoctypeByCDoctypeorderId) {
		this.CDoctypeByCDoctypeorderId = CDoctypeByCDoctypeorderId;
	}

	public void setCDoctypeByCDoctypeReversedId(
			CDoctype CDoctypeByCDoctypeReversedId) {
		this.CDoctypeByCDoctypeReversedId = CDoctypeByCDoctypeReversedId;
	}

	public void setCDoctypeByCDoctypeshipmentId(
			CDoctype CDoctypeByCDoctypeshipmentId) {
		this.CDoctypeByCDoctypeshipmentId = CDoctypeByCDoctypeshipmentId;
	}

	public void setCDoctypeId(String CDoctypeId) {
		this.CDoctypeId = CDoctypeId;
	}

	public void setCDoctypesForCDoctypeinvoiceId(
			Set<CDoctype> CDoctypesForCDoctypeinvoiceId) {
		this.CDoctypesForCDoctypeinvoiceId = CDoctypesForCDoctypeinvoiceId;
	}

	public void setCDoctypesForCDoctypeorderId(
			Set<CDoctype> CDoctypesForCDoctypeorderId) {
		this.CDoctypesForCDoctypeorderId = CDoctypesForCDoctypeorderId;
	}

	public void setCDoctypesForCDoctypeReversedId(
			Set<CDoctype> CDoctypesForCDoctypeReversedId) {
		this.CDoctypesForCDoctypeReversedId = CDoctypesForCDoctypeReversedId;
	}

	public void setCDoctypesForCDoctypeshipmentId(
			Set<CDoctype> CDoctypesForCDoctypeshipmentId) {
		this.CDoctypesForCDoctypeshipmentId = CDoctypesForCDoctypeshipmentId;
	}

	public void setCInvoicesForCDoctypeId(Set<CInvoice> CInvoicesForCDoctypeId) {
		this.CInvoicesForCDoctypeId = CInvoicesForCDoctypeId;
	}

	public void setCInvoicesForCDoctypetargetId(
			Set<CInvoice> CInvoicesForCDoctypetargetId) {
		this.CInvoicesForCDoctypetargetId = CInvoicesForCDoctypetargetId;
	}

	public void setCOrdersForCDoctypeId(Set<COrder> COrdersForCDoctypeId) {
		this.COrdersForCDoctypeId = COrdersForCDoctypeId;
	}

	public void setCOrdersForCDoctypetargetId(
			Set<COrder> COrdersForCDoctypetargetId) {
		this.COrdersForCDoctypetargetId = COrdersForCDoctypetargetId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDocbasetype(String docbasetype) {
		this.docbasetype = docbasetype;
	}

	public void setDocnosequenceId(String docnosequenceId) {
		this.docnosequenceId = docnosequenceId;
	}

	public void setDocsubtypeso(String docsubtypeso) {
		this.docsubtypeso = docsubtypeso;
	}

	public void setDocumentcopies(long documentcopies) {
		this.documentcopies = documentcopies;
	}

	public void setDocumentnote(String documentnote) {
		this.documentnote = documentnote;
	}

	public void setGlCategoryId(String glCategoryId) {
		this.glCategoryId = glCategoryId;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsdefault(char isdefault) {
		this.isdefault = isdefault;
	}

	public void setIsdocnocontrolled(char isdocnocontrolled) {
		this.isdocnocontrolled = isdocnocontrolled;
	}

	public void setIsexpense(char isexpense) {
		this.isexpense = isexpense;
	}

	public void setIsreturn(char isreturn) {
		this.isreturn = isreturn;
	}

	public void setIsreversal(char isreversal) {
		this.isreversal = isreversal;
	}

	public void setIssotrx(char issotrx) {
		this.issotrx = issotrx;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setOrgfiltered(char orgfiltered) {
		this.orgfiltered = orgfiltered;
	}

	public void setPrintname(String printname) {
		this.printname = printname;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

}
