package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CInvoicetax generated by hbm2java
 */
@Entity
@Table(name = "c_invoicetax", schema = "public")
public class CInvoicetax implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CInvoicetaxId;
	private CInvoice CInvoice;
	private AdOrg adOrg;
	private CTax CTax;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private BigDecimal taxbaseamt;
	private BigDecimal taxamt;
	private BigDecimal line;
	private char recalculate;

	public CInvoicetax() {
	}

	public CInvoicetax(String CInvoicetaxId, CInvoice CInvoice, AdOrg adOrg,
			CTax CTax, String adClientId, char isactive, Date created,
			String createdby, Date updated, String updatedby,
			BigDecimal taxbaseamt, BigDecimal taxamt, BigDecimal line,
			char recalculate) {
		this.CInvoicetaxId = CInvoicetaxId;
		this.CInvoice = CInvoice;
		this.adOrg = adOrg;
		this.CTax = CTax;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.taxbaseamt = taxbaseamt;
		this.taxamt = taxamt;
		this.line = line;
		this.recalculate = recalculate;
	}

	public CInvoicetax(String CInvoicetaxId, CInvoice CInvoice, AdOrg adOrg,
			CTax CTax, String adClientId, char isactive, Date created,
			String createdby, Date updated, String updatedby,
			BigDecimal taxbaseamt, BigDecimal taxamt, char recalculate) {
		this.CInvoicetaxId = CInvoicetaxId;
		this.CInvoice = CInvoice;
		this.adOrg = adOrg;
		this.CTax = CTax;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.taxbaseamt = taxbaseamt;
		this.taxamt = taxamt;
		this.recalculate = recalculate;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_invoice_id", nullable = false)
	public CInvoice getCInvoice() {
		return this.CInvoice;
	}

	@Id
	@Column(name = "c_invoicetax_id", unique = true, nullable = false, length = 32)
	public String getCInvoicetaxId() {
		return this.CInvoicetaxId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_tax_id", nullable = false)
	public CTax getCTax() {
		return this.CTax;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "line", precision = 131089, scale = 0)
	public BigDecimal getLine() {
		return this.line;
	}

	@Column(name = "recalculate", nullable = false, length = 1)
	public char getRecalculate() {
		return this.recalculate;
	}

	@Column(name = "taxamt", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getTaxamt() {
		return this.taxamt;
	}

	@Column(name = "taxbaseamt", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getTaxbaseamt() {
		return this.taxbaseamt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setCInvoice(CInvoice CInvoice) {
		this.CInvoice = CInvoice;
	}

	public void setCInvoicetaxId(String CInvoicetaxId) {
		this.CInvoicetaxId = CInvoicetaxId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCTax(CTax CTax) {
		this.CTax = CTax;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setLine(BigDecimal line) {
		this.line = line;
	}

	public void setRecalculate(char recalculate) {
		this.recalculate = recalculate;
	}

	public void setTaxamt(BigDecimal taxamt) {
		this.taxamt = taxamt;
	}

	public void setTaxbaseamt(BigDecimal taxbaseamt) {
		this.taxbaseamt = taxbaseamt;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

}
