package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CInvoiceline generated by hbm2java
 */
@Entity
@Table(name = "c_invoiceline", schema = "public")
public class CInvoiceline implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CInvoicelineId;
	private CInvoice CInvoice;
	private AdOrg adOrg;
	private CTax CTax;
	private MProduct MProduct;
	private CUom CUom;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String COrderlineId;
	private String MInoutlineId;
	private long line;
	private String description;
	private char financialInvoiceLine;
	private String accountId;
	private BigDecimal qtyinvoiced;
	private BigDecimal pricelist;
	private BigDecimal priceactual;
	private BigDecimal pricelimit;
	private BigDecimal linenetamt;
	private String CChargeId;
	private BigDecimal chargeamt;
	private String SResourceassignmentId;
	private BigDecimal taxamt;
	private String MAttributesetinstanceId;
	private char isdescription;
	private BigDecimal quantityorder;
	private String MProductUomId;
	private String CInvoiceDiscountId;
	private String CProjectlineId;
	private String MOfferId;
	private BigDecimal pricestd;
	private Character excludeforwithholding;
	private Character iseditlinenetamt;
	private BigDecimal taxbaseamt;
	private BigDecimal lineGrossAmount;
	private BigDecimal grossUnitPrice;
	private BigDecimal periodnumber;
	private BigDecimal grosspricestd;
	private String defplantype;
	private BigDecimal grosspricelist;
	private char isdeferred;
	private String CPeriodId;

	public CInvoiceline() {
	}

	public CInvoiceline(String CInvoicelineId, CInvoice CInvoice, AdOrg adOrg,
			CTax CTax, MProduct MProduct, CUom CUom, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String COrderlineId, String MInoutlineId,
			long line, String description, char financialInvoiceLine,
			String accountId, BigDecimal qtyinvoiced, BigDecimal pricelist,
			BigDecimal priceactual, BigDecimal pricelimit,
			BigDecimal linenetamt, String CChargeId, BigDecimal chargeamt,
			String SResourceassignmentId, BigDecimal taxamt,
			String MAttributesetinstanceId, char isdescription,
			BigDecimal quantityorder, String MProductUomId,
			String CInvoiceDiscountId, String CProjectlineId, String MOfferId,
			BigDecimal pricestd, Character excludeforwithholding,
			Character iseditlinenetamt, BigDecimal taxbaseamt,
			BigDecimal lineGrossAmount, BigDecimal grossUnitPrice,
			BigDecimal periodnumber, BigDecimal grosspricestd,
			String defplantype, BigDecimal grosspricelist, char isdeferred,
			String CPeriodId) {
		this.CInvoicelineId = CInvoicelineId;
		this.CInvoice = CInvoice;
		this.adOrg = adOrg;
		this.CTax = CTax;
		this.MProduct = MProduct;
		this.CUom = CUom;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.COrderlineId = COrderlineId;
		this.MInoutlineId = MInoutlineId;
		this.line = line;
		this.description = description;
		this.financialInvoiceLine = financialInvoiceLine;
		this.accountId = accountId;
		this.qtyinvoiced = qtyinvoiced;
		this.pricelist = pricelist;
		this.priceactual = priceactual;
		this.pricelimit = pricelimit;
		this.linenetamt = linenetamt;
		this.CChargeId = CChargeId;
		this.chargeamt = chargeamt;
		this.SResourceassignmentId = SResourceassignmentId;
		this.taxamt = taxamt;
		this.MAttributesetinstanceId = MAttributesetinstanceId;
		this.isdescription = isdescription;
		this.quantityorder = quantityorder;
		this.MProductUomId = MProductUomId;
		this.CInvoiceDiscountId = CInvoiceDiscountId;
		this.CProjectlineId = CProjectlineId;
		this.MOfferId = MOfferId;
		this.pricestd = pricestd;
		this.excludeforwithholding = excludeforwithholding;
		this.iseditlinenetamt = iseditlinenetamt;
		this.taxbaseamt = taxbaseamt;
		this.lineGrossAmount = lineGrossAmount;
		this.grossUnitPrice = grossUnitPrice;
		this.periodnumber = periodnumber;
		this.grosspricestd = grosspricestd;
		this.defplantype = defplantype;
		this.grosspricelist = grosspricelist;
		this.isdeferred = isdeferred;
		this.CPeriodId = CPeriodId;
	}

	public CInvoiceline(String CInvoicelineId, CInvoice CInvoice, AdOrg adOrg,
			String adClientId, char isactive, Date created, String createdby,
			Date updated, String updatedby, long line,
			char financialInvoiceLine, BigDecimal qtyinvoiced,
			BigDecimal pricelist, BigDecimal priceactual,
			BigDecimal pricelimit, BigDecimal linenetamt, char isdescription,
			BigDecimal pricestd, BigDecimal grosspricestd,
			BigDecimal grosspricelist, char isdeferred) {
		this.CInvoicelineId = CInvoicelineId;
		this.CInvoice = CInvoice;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.line = line;
		this.financialInvoiceLine = financialInvoiceLine;
		this.qtyinvoiced = qtyinvoiced;
		this.pricelist = pricelist;
		this.priceactual = priceactual;
		this.pricelimit = pricelimit;
		this.linenetamt = linenetamt;
		this.isdescription = isdescription;
		this.pricestd = pricestd;
		this.grosspricestd = grosspricestd;
		this.grosspricelist = grosspricelist;
		this.isdeferred = isdeferred;
	}

	@Column(name = "account_id", length = 32)
	public String getAccountId() {
		return this.accountId;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@Column(name = "c_charge_id", length = 32)
	public String getCChargeId() {
		return this.CChargeId;
	}

	@Column(name = "chargeamt", precision = 131089, scale = 0)
	public BigDecimal getChargeamt() {
		return this.chargeamt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_invoice_id", nullable = false)
	public CInvoice getCInvoice() {
		return this.CInvoice;
	}

	@Column(name = "c_invoice_discount_id", length = 32)
	public String getCInvoiceDiscountId() {
		return this.CInvoiceDiscountId;
	}

	@Id
	@Column(name = "c_invoiceline_id", unique = true, nullable = false, length = 32)
	public String getCInvoicelineId() {
		return this.CInvoicelineId;
	}

	@Column(name = "c_orderline_id", length = 32)
	public String getCOrderlineId() {
		return this.COrderlineId;
	}

	@Column(name = "c_period_id", length = 32)
	public String getCPeriodId() {
		return this.CPeriodId;
	}

	@Column(name = "c_projectline_id", length = 32)
	public String getCProjectlineId() {
		return this.CProjectlineId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_tax_id")
	public CTax getCTax() {
		return this.CTax;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_uom_id")
	public CUom getCUom() {
		return this.CUom;
	}

	@Column(name = "defplantype", length = 60)
	public String getDefplantype() {
		return this.defplantype;
	}

	@Column(name = "description", length = 2000)
	public String getDescription() {
		return this.description;
	}

	@Column(name = "excludeforwithholding", length = 1)
	public Character getExcludeforwithholding() {
		return this.excludeforwithholding;
	}

	@Column(name = "financial_invoice_line", nullable = false, length = 1)
	public char getFinancialInvoiceLine() {
		return this.financialInvoiceLine;
	}

	@Column(name = "grosspricelist", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getGrosspricelist() {
		return this.grosspricelist;
	}

	@Column(name = "grosspricestd", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getGrosspricestd() {
		return this.grosspricestd;
	}

	@Column(name = "gross_unit_price", precision = 131089, scale = 0)
	public BigDecimal getGrossUnitPrice() {
		return this.grossUnitPrice;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isdeferred", nullable = false, length = 1)
	public char getIsdeferred() {
		return this.isdeferred;
	}

	@Column(name = "isdescription", nullable = false, length = 1)
	public char getIsdescription() {
		return this.isdescription;
	}

	@Column(name = "iseditlinenetamt", length = 1)
	public Character getIseditlinenetamt() {
		return this.iseditlinenetamt;
	}

	@Column(name = "line", nullable = false, precision = 10, scale = 0)
	public long getLine() {
		return this.line;
	}

	@Column(name = "line_gross_amount", precision = 131089, scale = 0)
	public BigDecimal getLineGrossAmount() {
		return this.lineGrossAmount;
	}

	@Column(name = "linenetamt", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLinenetamt() {
		return this.linenetamt;
	}

	@Column(name = "m_attributesetinstance_id", length = 32)
	public String getMAttributesetinstanceId() {
		return this.MAttributesetinstanceId;
	}

	@Column(name = "m_inoutline_id", length = 32)
	public String getMInoutlineId() {
		return this.MInoutlineId;
	}

	@Column(name = "m_offer_id", length = 32)
	public String getMOfferId() {
		return this.MOfferId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "m_product_id")
	public MProduct getMProduct() {
		return this.MProduct;
	}

	@Column(name = "m_product_uom_id", length = 32)
	public String getMProductUomId() {
		return this.MProductUomId;
	}

	@Column(name = "periodnumber", precision = 131089, scale = 0)
	public BigDecimal getPeriodnumber() {
		return this.periodnumber;
	}

	@Column(name = "priceactual", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPriceactual() {
		return this.priceactual;
	}

	@Column(name = "pricelimit", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPricelimit() {
		return this.pricelimit;
	}

	@Column(name = "pricelist", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPricelist() {
		return this.pricelist;
	}

	@Column(name = "pricestd", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPricestd() {
		return this.pricestd;
	}

	@Column(name = "qtyinvoiced", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQtyinvoiced() {
		return this.qtyinvoiced;
	}

	@Column(name = "quantityorder", precision = 131089, scale = 0)
	public BigDecimal getQuantityorder() {
		return this.quantityorder;
	}

	@Column(name = "s_resourceassignment_id", length = 32)
	public String getSResourceassignmentId() {
		return this.SResourceassignmentId;
	}

	@Column(name = "taxamt", precision = 131089, scale = 0)
	public BigDecimal getTaxamt() {
		return this.taxamt;
	}

	@Column(name = "taxbaseamt", precision = 131089, scale = 0)
	public BigDecimal getTaxbaseamt() {
		return this.taxbaseamt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setCChargeId(String CChargeId) {
		this.CChargeId = CChargeId;
	}

	public void setChargeamt(BigDecimal chargeamt) {
		this.chargeamt = chargeamt;
	}

	public void setCInvoice(CInvoice CInvoice) {
		this.CInvoice = CInvoice;
	}

	public void setCInvoiceDiscountId(String CInvoiceDiscountId) {
		this.CInvoiceDiscountId = CInvoiceDiscountId;
	}

	public void setCInvoicelineId(String CInvoicelineId) {
		this.CInvoicelineId = CInvoicelineId;
	}

	public void setCOrderlineId(String COrderlineId) {
		this.COrderlineId = COrderlineId;
	}

	public void setCPeriodId(String CPeriodId) {
		this.CPeriodId = CPeriodId;
	}

	public void setCProjectlineId(String CProjectlineId) {
		this.CProjectlineId = CProjectlineId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCTax(CTax CTax) {
		this.CTax = CTax;
	}

	public void setCUom(CUom CUom) {
		this.CUom = CUom;
	}

	public void setDefplantype(String defplantype) {
		this.defplantype = defplantype;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setExcludeforwithholding(Character excludeforwithholding) {
		this.excludeforwithholding = excludeforwithholding;
	}

	public void setFinancialInvoiceLine(char financialInvoiceLine) {
		this.financialInvoiceLine = financialInvoiceLine;
	}

	public void setGrosspricelist(BigDecimal grosspricelist) {
		this.grosspricelist = grosspricelist;
	}

	public void setGrosspricestd(BigDecimal grosspricestd) {
		this.grosspricestd = grosspricestd;
	}

	public void setGrossUnitPrice(BigDecimal grossUnitPrice) {
		this.grossUnitPrice = grossUnitPrice;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsdeferred(char isdeferred) {
		this.isdeferred = isdeferred;
	}

	public void setIsdescription(char isdescription) {
		this.isdescription = isdescription;
	}

	public void setIseditlinenetamt(Character iseditlinenetamt) {
		this.iseditlinenetamt = iseditlinenetamt;
	}

	public void setLine(long line) {
		this.line = line;
	}

	public void setLineGrossAmount(BigDecimal lineGrossAmount) {
		this.lineGrossAmount = lineGrossAmount;
	}

	public void setLinenetamt(BigDecimal linenetamt) {
		this.linenetamt = linenetamt;
	}

	public void setMAttributesetinstanceId(String MAttributesetinstanceId) {
		this.MAttributesetinstanceId = MAttributesetinstanceId;
	}

	public void setMInoutlineId(String MInoutlineId) {
		this.MInoutlineId = MInoutlineId;
	}

	public void setMOfferId(String MOfferId) {
		this.MOfferId = MOfferId;
	}

	public void setMProduct(MProduct MProduct) {
		this.MProduct = MProduct;
	}

	public void setMProductUomId(String MProductUomId) {
		this.MProductUomId = MProductUomId;
	}

	public void setPeriodnumber(BigDecimal periodnumber) {
		this.periodnumber = periodnumber;
	}

	public void setPriceactual(BigDecimal priceactual) {
		this.priceactual = priceactual;
	}

	public void setPricelimit(BigDecimal pricelimit) {
		this.pricelimit = pricelimit;
	}

	public void setPricelist(BigDecimal pricelist) {
		this.pricelist = pricelist;
	}

	public void setPricestd(BigDecimal pricestd) {
		this.pricestd = pricestd;
	}

	public void setQtyinvoiced(BigDecimal qtyinvoiced) {
		this.qtyinvoiced = qtyinvoiced;
	}

	public void setQuantityorder(BigDecimal quantityorder) {
		this.quantityorder = quantityorder;
	}

	public void setSResourceassignmentId(String SResourceassignmentId) {
		this.SResourceassignmentId = SResourceassignmentId;
	}

	public void setTaxamt(BigDecimal taxamt) {
		this.taxamt = taxamt;
	}

	public void setTaxbaseamt(BigDecimal taxbaseamt) {
		this.taxbaseamt = taxbaseamt;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

}
