package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CLocation generated by hbm2java
 */
@Entity
@Table(name = "c_location", schema = "public")
public class CLocation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CLocationId;
	private AdOrg adOrg;
	private CCountry CCountry;
	private CRegion CRegion;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String address1;
	private String address2;
	private String city;
	private String postal;
	private String postalAdd;
	private String CCityId;
	private String regionname;
	private Set<AdOrginfo> adOrginfos = new HashSet<AdOrginfo>(0);
	private Set<CBpartnerLocation> CBpartnerLocations = new HashSet<CBpartnerLocation>(
			0);

	public CLocation() {
	}

	public CLocation(String CLocationId, AdOrg adOrg, CCountry CCountry,
			CRegion CRegion, String adClientId, char isactive, Date created,
			String createdby, Date updated, String updatedby, String address1,
			String address2, String city, String postal, String postalAdd,
			String CCityId, String regionname, Set<AdOrginfo> adOrginfos,
			Set<CBpartnerLocation> CBpartnerLocations) {
		this.CLocationId = CLocationId;
		this.adOrg = adOrg;
		this.CCountry = CCountry;
		this.CRegion = CRegion;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.postal = postal;
		this.postalAdd = postalAdd;
		this.CCityId = CCityId;
		this.regionname = regionname;
		this.adOrginfos = adOrginfos;
		this.CBpartnerLocations = CBpartnerLocations;
	}

	public CLocation(String CLocationId, AdOrg adOrg, CCountry CCountry,
			String adClientId, char isactive, Date created, String createdby,
			Date updated, String updatedby) {
		this.CLocationId = CLocationId;
		this.adOrg = adOrg;
		this.CCountry = CCountry;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@Column(name = "address1", length = 60)
	public String getAddress1() {
		return this.address1;
	}

	@Column(name = "address2", length = 60)
	public String getAddress2() {
		return this.address2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CLocation")
	public Set<AdOrginfo> getAdOrginfos() {
		return this.adOrginfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CLocation")
	public Set<CBpartnerLocation> getCBpartnerLocations() {
		return this.CBpartnerLocations;
	}

	@Column(name = "c_city_id", length = 32)
	public String getCCityId() {
		return this.CCityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_country_id", nullable = false)
	public CCountry getCCountry() {
		return this.CCountry;
	}

	@Column(name = "city", length = 60)
	public String getCity() {
		return this.city;
	}

	@Id
	@Column(name = "c_location_id", unique = true, nullable = false, length = 32)
	public String getCLocationId() {
		return this.CLocationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_region_id")
	public CRegion getCRegion() {
		return this.CRegion;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "postal", length = 10)
	public String getPostal() {
		return this.postal;
	}

	@Column(name = "postal_add", length = 10)
	public String getPostalAdd() {
		return this.postalAdd;
	}

	@Column(name = "regionname", length = 40)
	public String getRegionname() {
		return this.regionname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setAdOrginfos(Set<AdOrginfo> adOrginfos) {
		this.adOrginfos = adOrginfos;
	}

	public void setCBpartnerLocations(Set<CBpartnerLocation> CBpartnerLocations) {
		this.CBpartnerLocations = CBpartnerLocations;
	}

	public void setCCityId(String CCityId) {
		this.CCityId = CCityId;
	}

	public void setCCountry(CCountry CCountry) {
		this.CCountry = CCountry;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public void setCLocationId(String CLocationId) {
		this.CLocationId = CLocationId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCRegion(CRegion CRegion) {
		this.CRegion = CRegion;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setPostal(String postal) {
		this.postal = postal;
	}

	public void setPostalAdd(String postalAdd) {
		this.postalAdd = postalAdd;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

}
