package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * COrder generated by hbm2java
 */
@Entity
@Table(name = "c_order", schema = "public")
public class COrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String COrderId;
	private COrder COrder;
	private CBpartnerLocation CBpartnerLocationByDeliveryLocationId;
	private CBpartnerLocation CBpartnerLocationByBilltoId;
	private CDoctype CDoctypeByCDoctypeId;
	private FinPaymentmethod finPaymentmethod;
	private AdOrg adOrgByAdOrgtrxId;
	private CBpartner CBpartnerByDropshipBpartnerId;
	private AdOrg adOrgByAdOrgId;
	private CDoctype CDoctypeByCDoctypetargetId;
	private CBpartnerLocation CBpartnerLocationByCBpartnerLocationId;
	private CBpartner CBpartnerByCBpartnerId;
	private CBpartnerLocation CBpartnerLocationByDropshipLocationId;
	private CPaymentterm CPaymentterm;
	private CCurrency CCurrency;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private char issotrx;
	private String documentno;
	private String docstatus;
	private String docaction;
	private Character processing;
	private char processed;
	private String description;
	private char isdelivered;
	private char isinvoiced;
	private char isprinted;
	private char isselected;
	private String salesrepId;
	private Date dateordered;
	private Date datepromised;
	private Date dateprinted;
	private Date dateacct;
	private String poreference;
	private char isdiscountprinted;
	private String paymentrule;
	private String invoicerule;
	private String deliveryrule;
	private String freightcostrule;
	private BigDecimal freightamt;
	private String deliveryviarule;
	private String MShipperId;
	private String CChargeId;
	private BigDecimal chargeamt;
	private String priorityrule;
	private BigDecimal totallines;
	private BigDecimal grandtotal;
	private String MWarehouseId;
	private String MPricelistId;
	private Character istaxincluded;
	private String CCampaignId;
	private String CProjectId;
	private String CActivityId;
	private String posted;
	private String adUserId;
	private Character copyfrom;
	private String dropshipUserId;
	private char isselfservice;
	private String user1Id;
	private String user2Id;
	private String deliverynotes;
	private String CIncotermsId;
	private String incotermsdescription;
	private Character generatetemplate;
	private Character copyfrompo;
	private String finPaymentPriorityId;
	private Character rmPickfromshipment;
	private Character rmReceivematerials;
	private String rmCreateinvoice;
	private String CReturnReasonId;
	private Character rmAddorphanline;
	private String calculatePromotions;
	private Character convertquotation;
	private String CRejectReasonId;
	private Date validuntil;
	private Set<COrder> COrders = new HashSet<COrder>(0);
	private Set<CInvoice> CInvoices = new HashSet<CInvoice>(0);

	public COrder() {
	}

	public COrder(String COrderId, CDoctype CDoctypeByCDoctypeId,
			AdOrg adOrgByAdOrgId, CDoctype CDoctypeByCDoctypetargetId,
			CBpartnerLocation CBpartnerLocationByCBpartnerLocationId,
			CBpartner CBpartnerByCBpartnerId, CPaymentterm CPaymentterm,
			CCurrency CCurrency, String adClientId, char isactive,
			Date created, String createdby, Date updated, String updatedby,
			char issotrx, String documentno, String docstatus,
			String docaction, char processed, char isdelivered,
			char isinvoiced, char isprinted, char isselected, Date dateordered,
			Date dateacct, char isdiscountprinted, String paymentrule,
			String invoicerule, String deliveryrule, String freightcostrule,
			String deliveryviarule, String priorityrule, BigDecimal totallines,
			BigDecimal grandtotal, String MWarehouseId, String MPricelistId,
			String posted, char isselfservice) {
		this.COrderId = COrderId;
		this.CDoctypeByCDoctypeId = CDoctypeByCDoctypeId;
		this.adOrgByAdOrgId = adOrgByAdOrgId;
		this.CDoctypeByCDoctypetargetId = CDoctypeByCDoctypetargetId;
		this.CBpartnerLocationByCBpartnerLocationId = CBpartnerLocationByCBpartnerLocationId;
		this.CBpartnerByCBpartnerId = CBpartnerByCBpartnerId;
		this.CPaymentterm = CPaymentterm;
		this.CCurrency = CCurrency;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.issotrx = issotrx;
		this.documentno = documentno;
		this.docstatus = docstatus;
		this.docaction = docaction;
		this.processed = processed;
		this.isdelivered = isdelivered;
		this.isinvoiced = isinvoiced;
		this.isprinted = isprinted;
		this.isselected = isselected;
		this.dateordered = dateordered;
		this.dateacct = dateacct;
		this.isdiscountprinted = isdiscountprinted;
		this.paymentrule = paymentrule;
		this.invoicerule = invoicerule;
		this.deliveryrule = deliveryrule;
		this.freightcostrule = freightcostrule;
		this.deliveryviarule = deliveryviarule;
		this.priorityrule = priorityrule;
		this.totallines = totallines;
		this.grandtotal = grandtotal;
		this.MWarehouseId = MWarehouseId;
		this.MPricelistId = MPricelistId;
		this.posted = posted;
		this.isselfservice = isselfservice;
	}

	public COrder(String COrderId, COrder COrder,
			CBpartnerLocation CBpartnerLocationByDeliveryLocationId,
			CBpartnerLocation CBpartnerLocationByBilltoId,
			CDoctype CDoctypeByCDoctypeId, FinPaymentmethod finPaymentmethod,
			AdOrg adOrgByAdOrgtrxId, CBpartner CBpartnerByDropshipBpartnerId,
			AdOrg adOrgByAdOrgId, CDoctype CDoctypeByCDoctypetargetId,
			CBpartnerLocation CBpartnerLocationByCBpartnerLocationId,
			CBpartner CBpartnerByCBpartnerId,
			CBpartnerLocation CBpartnerLocationByDropshipLocationId,
			CPaymentterm CPaymentterm, CCurrency CCurrency, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, char issotrx, String documentno,
			String docstatus, String docaction, Character processing,
			char processed, String description, char isdelivered,
			char isinvoiced, char isprinted, char isselected,
			String salesrepId, Date dateordered, Date datepromised,
			Date dateprinted, Date dateacct, String poreference,
			char isdiscountprinted, String paymentrule, String invoicerule,
			String deliveryrule, String freightcostrule, BigDecimal freightamt,
			String deliveryviarule, String MShipperId, String CChargeId,
			BigDecimal chargeamt, String priorityrule, BigDecimal totallines,
			BigDecimal grandtotal, String MWarehouseId, String MPricelistId,
			Character istaxincluded, String CCampaignId, String CProjectId,
			String CActivityId, String posted, String adUserId,
			Character copyfrom, String dropshipUserId, char isselfservice,
			String user1Id, String user2Id, String deliverynotes,
			String CIncotermsId, String incotermsdescription,
			Character generatetemplate, Character copyfrompo,
			String finPaymentPriorityId, Character rmPickfromshipment,
			Character rmReceivematerials, String rmCreateinvoice,
			String CReturnReasonId, Character rmAddorphanline,
			String calculatePromotions, Character convertquotation,
			String CRejectReasonId, Date validuntil, Set<COrder> COrders,
			Set<CInvoice> CInvoices) {
		this.COrderId = COrderId;
		this.COrder = COrder;
		this.CBpartnerLocationByDeliveryLocationId = CBpartnerLocationByDeliveryLocationId;
		this.CBpartnerLocationByBilltoId = CBpartnerLocationByBilltoId;
		this.CDoctypeByCDoctypeId = CDoctypeByCDoctypeId;
		this.finPaymentmethod = finPaymentmethod;
		this.adOrgByAdOrgtrxId = adOrgByAdOrgtrxId;
		this.CBpartnerByDropshipBpartnerId = CBpartnerByDropshipBpartnerId;
		this.adOrgByAdOrgId = adOrgByAdOrgId;
		this.CDoctypeByCDoctypetargetId = CDoctypeByCDoctypetargetId;
		this.CBpartnerLocationByCBpartnerLocationId = CBpartnerLocationByCBpartnerLocationId;
		this.CBpartnerByCBpartnerId = CBpartnerByCBpartnerId;
		this.CBpartnerLocationByDropshipLocationId = CBpartnerLocationByDropshipLocationId;
		this.CPaymentterm = CPaymentterm;
		this.CCurrency = CCurrency;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.issotrx = issotrx;
		this.documentno = documentno;
		this.docstatus = docstatus;
		this.docaction = docaction;
		this.processing = processing;
		this.processed = processed;
		this.description = description;
		this.isdelivered = isdelivered;
		this.isinvoiced = isinvoiced;
		this.isprinted = isprinted;
		this.isselected = isselected;
		this.salesrepId = salesrepId;
		this.dateordered = dateordered;
		this.datepromised = datepromised;
		this.dateprinted = dateprinted;
		this.dateacct = dateacct;
		this.poreference = poreference;
		this.isdiscountprinted = isdiscountprinted;
		this.paymentrule = paymentrule;
		this.invoicerule = invoicerule;
		this.deliveryrule = deliveryrule;
		this.freightcostrule = freightcostrule;
		this.freightamt = freightamt;
		this.deliveryviarule = deliveryviarule;
		this.MShipperId = MShipperId;
		this.CChargeId = CChargeId;
		this.chargeamt = chargeamt;
		this.priorityrule = priorityrule;
		this.totallines = totallines;
		this.grandtotal = grandtotal;
		this.MWarehouseId = MWarehouseId;
		this.MPricelistId = MPricelistId;
		this.istaxincluded = istaxincluded;
		this.CCampaignId = CCampaignId;
		this.CProjectId = CProjectId;
		this.CActivityId = CActivityId;
		this.posted = posted;
		this.adUserId = adUserId;
		this.copyfrom = copyfrom;
		this.dropshipUserId = dropshipUserId;
		this.isselfservice = isselfservice;
		this.user1Id = user1Id;
		this.user2Id = user2Id;
		this.deliverynotes = deliverynotes;
		this.CIncotermsId = CIncotermsId;
		this.incotermsdescription = incotermsdescription;
		this.generatetemplate = generatetemplate;
		this.copyfrompo = copyfrompo;
		this.finPaymentPriorityId = finPaymentPriorityId;
		this.rmPickfromshipment = rmPickfromshipment;
		this.rmReceivematerials = rmReceivematerials;
		this.rmCreateinvoice = rmCreateinvoice;
		this.CReturnReasonId = CReturnReasonId;
		this.rmAddorphanline = rmAddorphanline;
		this.calculatePromotions = calculatePromotions;
		this.convertquotation = convertquotation;
		this.CRejectReasonId = CRejectReasonId;
		this.validuntil = validuntil;
		this.COrders = COrders;
		this.CInvoices = CInvoices;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrgByAdOrgId() {
		return this.adOrgByAdOrgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_orgtrx_id")
	public AdOrg getAdOrgByAdOrgtrxId() {
		return this.adOrgByAdOrgtrxId;
	}

	@Column(name = "ad_user_id", length = 32)
	public String getAdUserId() {
		return this.adUserId;
	}

	@Column(name = "c_activity_id", length = 32)
	public String getCActivityId() {
		return this.CActivityId;
	}

	@Column(name = "calculate_promotions", length = 1)
	public String getCalculatePromotions() {
		return this.calculatePromotions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_bpartner_id", nullable = false)
	public CBpartner getCBpartnerByCBpartnerId() {
		return this.CBpartnerByCBpartnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dropship_bpartner_id")
	public CBpartner getCBpartnerByDropshipBpartnerId() {
		return this.CBpartnerByDropshipBpartnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billto_id")
	public CBpartnerLocation getCBpartnerLocationByBilltoId() {
		return this.CBpartnerLocationByBilltoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_bpartner_location_id", nullable = false)
	public CBpartnerLocation getCBpartnerLocationByCBpartnerLocationId() {
		return this.CBpartnerLocationByCBpartnerLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delivery_location_id")
	public CBpartnerLocation getCBpartnerLocationByDeliveryLocationId() {
		return this.CBpartnerLocationByDeliveryLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dropship_location_id")
	public CBpartnerLocation getCBpartnerLocationByDropshipLocationId() {
		return this.CBpartnerLocationByDropshipLocationId;
	}

	@Column(name = "c_campaign_id", length = 32)
	public String getCCampaignId() {
		return this.CCampaignId;
	}

	@Column(name = "c_charge_id", length = 32)
	public String getCChargeId() {
		return this.CChargeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_currency_id", nullable = false)
	public CCurrency getCCurrency() {
		return this.CCurrency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_doctype_id", nullable = false)
	public CDoctype getCDoctypeByCDoctypeId() {
		return this.CDoctypeByCDoctypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_doctypetarget_id", nullable = false)
	public CDoctype getCDoctypeByCDoctypetargetId() {
		return this.CDoctypeByCDoctypetargetId;
	}

	@Column(name = "chargeamt", precision = 131089, scale = 0)
	public BigDecimal getChargeamt() {
		return this.chargeamt;
	}

	@Column(name = "c_incoterms_id", length = 32)
	public String getCIncotermsId() {
		return this.CIncotermsId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "COrder")
	public Set<CInvoice> getCInvoices() {
		return this.CInvoices;
	}

	@Column(name = "convertquotation", length = 1)
	public Character getConvertquotation() {
		return this.convertquotation;
	}

	@Column(name = "copyfrom", length = 1)
	public Character getCopyfrom() {
		return this.copyfrom;
	}

	@Column(name = "copyfrompo", length = 1)
	public Character getCopyfrompo() {
		return this.copyfrompo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quotation_id")
	public COrder getCOrder() {
		return this.COrder;
	}

	@Id
	@Column(name = "c_order_id", unique = true, nullable = false, length = 32)
	public String getCOrderId() {
		return this.COrderId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "COrder")
	public Set<COrder> getCOrders() {
		return this.COrders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_paymentterm_id", nullable = false)
	public CPaymentterm getCPaymentterm() {
		return this.CPaymentterm;
	}

	@Column(name = "c_project_id", length = 32)
	public String getCProjectId() {
		return this.CProjectId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Column(name = "c_reject_reason_id", length = 32)
	public String getCRejectReasonId() {
		return this.CRejectReasonId;
	}

	@Column(name = "c_return_reason_id", length = 32)
	public String getCReturnReasonId() {
		return this.CReturnReasonId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateacct", nullable = false, length = 29)
	public Date getDateacct() {
		return this.dateacct;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateordered", nullable = false, length = 29)
	public Date getDateordered() {
		return this.dateordered;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateprinted", length = 29)
	public Date getDateprinted() {
		return this.dateprinted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datepromised", length = 29)
	public Date getDatepromised() {
		return this.datepromised;
	}

	@Column(name = "deliverynotes", length = 2000)
	public String getDeliverynotes() {
		return this.deliverynotes;
	}

	@Column(name = "deliveryrule", nullable = false, length = 60)
	public String getDeliveryrule() {
		return this.deliveryrule;
	}

	@Column(name = "deliveryviarule", nullable = false, length = 60)
	public String getDeliveryviarule() {
		return this.deliveryviarule;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@Column(name = "docaction", nullable = false, length = 60)
	public String getDocaction() {
		return this.docaction;
	}

	@Column(name = "docstatus", nullable = false, length = 60)
	public String getDocstatus() {
		return this.docstatus;
	}

	@Column(name = "documentno", nullable = false, length = 30)
	public String getDocumentno() {
		return this.documentno;
	}

	@Column(name = "dropship_user_id", length = 32)
	public String getDropshipUserId() {
		return this.dropshipUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fin_paymentmethod_id")
	public FinPaymentmethod getFinPaymentmethod() {
		return this.finPaymentmethod;
	}

	@Column(name = "fin_payment_priority_id", length = 32)
	public String getFinPaymentPriorityId() {
		return this.finPaymentPriorityId;
	}

	@Column(name = "freightamt", precision = 131089, scale = 0)
	public BigDecimal getFreightamt() {
		return this.freightamt;
	}

	@Column(name = "freightcostrule", nullable = false, length = 60)
	public String getFreightcostrule() {
		return this.freightcostrule;
	}

	@Column(name = "generatetemplate", length = 1)
	public Character getGeneratetemplate() {
		return this.generatetemplate;
	}

	@Column(name = "grandtotal", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getGrandtotal() {
		return this.grandtotal;
	}

	@Column(name = "incotermsdescription")
	public String getIncotermsdescription() {
		return this.incotermsdescription;
	}

	@Column(name = "invoicerule", nullable = false, length = 60)
	public String getInvoicerule() {
		return this.invoicerule;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isdelivered", nullable = false, length = 1)
	public char getIsdelivered() {
		return this.isdelivered;
	}

	@Column(name = "isdiscountprinted", nullable = false, length = 1)
	public char getIsdiscountprinted() {
		return this.isdiscountprinted;
	}

	@Column(name = "isinvoiced", nullable = false, length = 1)
	public char getIsinvoiced() {
		return this.isinvoiced;
	}

	@Column(name = "isprinted", nullable = false, length = 1)
	public char getIsprinted() {
		return this.isprinted;
	}

	@Column(name = "isselected", nullable = false, length = 1)
	public char getIsselected() {
		return this.isselected;
	}

	@Column(name = "isselfservice", nullable = false, length = 1)
	public char getIsselfservice() {
		return this.isselfservice;
	}

	@Column(name = "issotrx", nullable = false, length = 1)
	public char getIssotrx() {
		return this.issotrx;
	}

	@Column(name = "istaxincluded", length = 1)
	public Character getIstaxincluded() {
		return this.istaxincluded;
	}

	@Column(name = "m_pricelist_id", nullable = false, length = 32)
	public String getMPricelistId() {
		return this.MPricelistId;
	}

	@Column(name = "m_shipper_id", length = 32)
	public String getMShipperId() {
		return this.MShipperId;
	}

	@Column(name = "m_warehouse_id", nullable = false, length = 32)
	public String getMWarehouseId() {
		return this.MWarehouseId;
	}

	@Column(name = "paymentrule", nullable = false, length = 60)
	public String getPaymentrule() {
		return this.paymentrule;
	}

	@Column(name = "poreference", length = 20)
	public String getPoreference() {
		return this.poreference;
	}

	@Column(name = "posted", nullable = false, length = 60)
	public String getPosted() {
		return this.posted;
	}

	@Column(name = "priorityrule", nullable = false, length = 60)
	public String getPriorityrule() {
		return this.priorityrule;
	}

	@Column(name = "processed", nullable = false, length = 1)
	public char getProcessed() {
		return this.processed;
	}

	@Column(name = "processing", length = 1)
	public Character getProcessing() {
		return this.processing;
	}

	@Column(name = "rm_addorphanline", length = 1)
	public Character getRmAddorphanline() {
		return this.rmAddorphanline;
	}

	@Column(name = "rm_createinvoice", length = 60)
	public String getRmCreateinvoice() {
		return this.rmCreateinvoice;
	}

	@Column(name = "rm_pickfromshipment", length = 1)
	public Character getRmPickfromshipment() {
		return this.rmPickfromshipment;
	}

	@Column(name = "rm_receivematerials", length = 1)
	public Character getRmReceivematerials() {
		return this.rmReceivematerials;
	}

	@Column(name = "salesrep_id", length = 32)
	public String getSalesrepId() {
		return this.salesrepId;
	}

	@Column(name = "totallines", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getTotallines() {
		return this.totallines;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "user1_id", length = 32)
	public String getUser1Id() {
		return this.user1Id;
	}

	@Column(name = "user2_id", length = 32)
	public String getUser2Id() {
		return this.user2Id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "validuntil", length = 29)
	public Date getValiduntil() {
		return this.validuntil;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrgByAdOrgId(AdOrg adOrgByAdOrgId) {
		this.adOrgByAdOrgId = adOrgByAdOrgId;
	}

	public void setAdOrgByAdOrgtrxId(AdOrg adOrgByAdOrgtrxId) {
		this.adOrgByAdOrgtrxId = adOrgByAdOrgtrxId;
	}

	public void setAdUserId(String adUserId) {
		this.adUserId = adUserId;
	}

	public void setCActivityId(String CActivityId) {
		this.CActivityId = CActivityId;
	}

	public void setCalculatePromotions(String calculatePromotions) {
		this.calculatePromotions = calculatePromotions;
	}

	public void setCBpartnerByCBpartnerId(CBpartner CBpartnerByCBpartnerId) {
		this.CBpartnerByCBpartnerId = CBpartnerByCBpartnerId;
	}

	public void setCBpartnerByDropshipBpartnerId(
			CBpartner CBpartnerByDropshipBpartnerId) {
		this.CBpartnerByDropshipBpartnerId = CBpartnerByDropshipBpartnerId;
	}

	public void setCBpartnerLocationByBilltoId(
			CBpartnerLocation CBpartnerLocationByBilltoId) {
		this.CBpartnerLocationByBilltoId = CBpartnerLocationByBilltoId;
	}

	public void setCBpartnerLocationByCBpartnerLocationId(
			CBpartnerLocation CBpartnerLocationByCBpartnerLocationId) {
		this.CBpartnerLocationByCBpartnerLocationId = CBpartnerLocationByCBpartnerLocationId;
	}

	public void setCBpartnerLocationByDeliveryLocationId(
			CBpartnerLocation CBpartnerLocationByDeliveryLocationId) {
		this.CBpartnerLocationByDeliveryLocationId = CBpartnerLocationByDeliveryLocationId;
	}

	public void setCBpartnerLocationByDropshipLocationId(
			CBpartnerLocation CBpartnerLocationByDropshipLocationId) {
		this.CBpartnerLocationByDropshipLocationId = CBpartnerLocationByDropshipLocationId;
	}

	public void setCCampaignId(String CCampaignId) {
		this.CCampaignId = CCampaignId;
	}

	public void setCChargeId(String CChargeId) {
		this.CChargeId = CChargeId;
	}

	public void setCCurrency(CCurrency CCurrency) {
		this.CCurrency = CCurrency;
	}

	public void setCDoctypeByCDoctypeId(CDoctype CDoctypeByCDoctypeId) {
		this.CDoctypeByCDoctypeId = CDoctypeByCDoctypeId;
	}

	public void setCDoctypeByCDoctypetargetId(
			CDoctype CDoctypeByCDoctypetargetId) {
		this.CDoctypeByCDoctypetargetId = CDoctypeByCDoctypetargetId;
	}

	public void setChargeamt(BigDecimal chargeamt) {
		this.chargeamt = chargeamt;
	}

	public void setCIncotermsId(String CIncotermsId) {
		this.CIncotermsId = CIncotermsId;
	}

	public void setCInvoices(Set<CInvoice> CInvoices) {
		this.CInvoices = CInvoices;
	}

	public void setConvertquotation(Character convertquotation) {
		this.convertquotation = convertquotation;
	}

	public void setCopyfrom(Character copyfrom) {
		this.copyfrom = copyfrom;
	}

	public void setCopyfrompo(Character copyfrompo) {
		this.copyfrompo = copyfrompo;
	}

	public void setCOrder(COrder COrder) {
		this.COrder = COrder;
	}

	public void setCOrderId(String COrderId) {
		this.COrderId = COrderId;
	}

	public void setCOrders(Set<COrder> COrders) {
		this.COrders = COrders;
	}

	public void setCPaymentterm(CPaymentterm CPaymentterm) {
		this.CPaymentterm = CPaymentterm;
	}

	public void setCProjectId(String CProjectId) {
		this.CProjectId = CProjectId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCRejectReasonId(String CRejectReasonId) {
		this.CRejectReasonId = CRejectReasonId;
	}

	public void setCReturnReasonId(String CReturnReasonId) {
		this.CReturnReasonId = CReturnReasonId;
	}

	public void setDateacct(Date dateacct) {
		this.dateacct = dateacct;
	}

	public void setDateordered(Date dateordered) {
		this.dateordered = dateordered;
	}

	public void setDateprinted(Date dateprinted) {
		this.dateprinted = dateprinted;
	}

	public void setDatepromised(Date datepromised) {
		this.datepromised = datepromised;
	}

	public void setDeliverynotes(String deliverynotes) {
		this.deliverynotes = deliverynotes;
	}

	public void setDeliveryrule(String deliveryrule) {
		this.deliveryrule = deliveryrule;
	}

	public void setDeliveryviarule(String deliveryviarule) {
		this.deliveryviarule = deliveryviarule;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDocaction(String docaction) {
		this.docaction = docaction;
	}

	public void setDocstatus(String docstatus) {
		this.docstatus = docstatus;
	}

	public void setDocumentno(String documentno) {
		this.documentno = documentno;
	}

	public void setDropshipUserId(String dropshipUserId) {
		this.dropshipUserId = dropshipUserId;
	}

	public void setFinPaymentmethod(FinPaymentmethod finPaymentmethod) {
		this.finPaymentmethod = finPaymentmethod;
	}

	public void setFinPaymentPriorityId(String finPaymentPriorityId) {
		this.finPaymentPriorityId = finPaymentPriorityId;
	}

	public void setFreightamt(BigDecimal freightamt) {
		this.freightamt = freightamt;
	}

	public void setFreightcostrule(String freightcostrule) {
		this.freightcostrule = freightcostrule;
	}

	public void setGeneratetemplate(Character generatetemplate) {
		this.generatetemplate = generatetemplate;
	}

	public void setGrandtotal(BigDecimal grandtotal) {
		this.grandtotal = grandtotal;
	}

	public void setIncotermsdescription(String incotermsdescription) {
		this.incotermsdescription = incotermsdescription;
	}

	public void setInvoicerule(String invoicerule) {
		this.invoicerule = invoicerule;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsdelivered(char isdelivered) {
		this.isdelivered = isdelivered;
	}

	public void setIsdiscountprinted(char isdiscountprinted) {
		this.isdiscountprinted = isdiscountprinted;
	}

	public void setIsinvoiced(char isinvoiced) {
		this.isinvoiced = isinvoiced;
	}

	public void setIsprinted(char isprinted) {
		this.isprinted = isprinted;
	}

	public void setIsselected(char isselected) {
		this.isselected = isselected;
	}

	public void setIsselfservice(char isselfservice) {
		this.isselfservice = isselfservice;
	}

	public void setIssotrx(char issotrx) {
		this.issotrx = issotrx;
	}

	public void setIstaxincluded(Character istaxincluded) {
		this.istaxincluded = istaxincluded;
	}

	public void setMPricelistId(String MPricelistId) {
		this.MPricelistId = MPricelistId;
	}

	public void setMShipperId(String MShipperId) {
		this.MShipperId = MShipperId;
	}

	public void setMWarehouseId(String MWarehouseId) {
		this.MWarehouseId = MWarehouseId;
	}

	public void setPaymentrule(String paymentrule) {
		this.paymentrule = paymentrule;
	}

	public void setPoreference(String poreference) {
		this.poreference = poreference;
	}

	public void setPosted(String posted) {
		this.posted = posted;
	}

	public void setPriorityrule(String priorityrule) {
		this.priorityrule = priorityrule;
	}

	public void setProcessed(char processed) {
		this.processed = processed;
	}

	public void setProcessing(Character processing) {
		this.processing = processing;
	}

	public void setRmAddorphanline(Character rmAddorphanline) {
		this.rmAddorphanline = rmAddorphanline;
	}

	public void setRmCreateinvoice(String rmCreateinvoice) {
		this.rmCreateinvoice = rmCreateinvoice;
	}

	public void setRmPickfromshipment(Character rmPickfromshipment) {
		this.rmPickfromshipment = rmPickfromshipment;
	}

	public void setRmReceivematerials(Character rmReceivematerials) {
		this.rmReceivematerials = rmReceivematerials;
	}

	public void setSalesrepId(String salesrepId) {
		this.salesrepId = salesrepId;
	}

	public void setTotallines(BigDecimal totallines) {
		this.totallines = totallines;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setUser1Id(String user1Id) {
		this.user1Id = user1Id;
	}

	public void setUser2Id(String user2Id) {
		this.user2Id = user2Id;
	}

	public void setValiduntil(Date validuntil) {
		this.validuntil = validuntil;
	}

}
