package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CPaymentterm generated by hbm2java
 */
@Entity
@Table(name = "c_paymentterm", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ad_client_id", "name" }))
public class CPaymentterm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CPaymenttermId;
	private AdOrg adOrg;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String name;
	private String description;
	private String documentnote;
	private char isduefixed;
	private long netdays;
	private Long fixmonthday;
	private Long fixmonthoffset;
	private Character isnextbusinessday;
	private Character isdefault;
	private String value;
	private String netday;
	private char isvalid;
	private Long fixmonthday2;
	private Long fixmonthday3;
	private Set<CBpartner> CBpartnersForCPaymenttermId = new HashSet<CBpartner>(
			0);
	private Set<COrder> COrders = new HashSet<COrder>(0);
	private Set<CInvoice> CInvoices = new HashSet<CInvoice>(0);
	private Set<CBpartner> CBpartnersForPoPaymenttermId = new HashSet<CBpartner>(
			0);

	public CPaymentterm() {
	}

	public CPaymentterm(String CPaymenttermId, AdOrg adOrg, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String name, char isduefixed, long netdays,
			String value, char isvalid) {
		this.CPaymenttermId = CPaymenttermId;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
		this.isduefixed = isduefixed;
		this.netdays = netdays;
		this.value = value;
		this.isvalid = isvalid;
	}

	public CPaymentterm(String CPaymenttermId, AdOrg adOrg, String adClientId,
			char isactive, Date created, String createdby, Date updated,
			String updatedby, String name, String description,
			String documentnote, char isduefixed, long netdays,
			Long fixmonthday, Long fixmonthoffset, Character isnextbusinessday,
			Character isdefault, String value, String netday, char isvalid,
			Long fixmonthday2, Long fixmonthday3,
			Set<CBpartner> CBpartnersForCPaymenttermId, Set<COrder> COrders,
			Set<CInvoice> CInvoices, Set<CBpartner> CBpartnersForPoPaymenttermId) {
		this.CPaymenttermId = CPaymenttermId;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
		this.description = description;
		this.documentnote = documentnote;
		this.isduefixed = isduefixed;
		this.netdays = netdays;
		this.fixmonthday = fixmonthday;
		this.fixmonthoffset = fixmonthoffset;
		this.isnextbusinessday = isnextbusinessday;
		this.isdefault = isdefault;
		this.value = value;
		this.netday = netday;
		this.isvalid = isvalid;
		this.fixmonthday2 = fixmonthday2;
		this.fixmonthday3 = fixmonthday3;
		this.CBpartnersForCPaymenttermId = CBpartnersForCPaymenttermId;
		this.COrders = COrders;
		this.CInvoices = CInvoices;
		this.CBpartnersForPoPaymenttermId = CBpartnersForPoPaymenttermId;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CPaymenttermByCPaymenttermId")
	public Set<CBpartner> getCBpartnersForCPaymenttermId() {
		return this.CBpartnersForCPaymenttermId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CPaymenttermByPoPaymenttermId")
	public Set<CBpartner> getCBpartnersForPoPaymenttermId() {
		return this.CBpartnersForPoPaymenttermId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CPaymentterm")
	public Set<CInvoice> getCInvoices() {
		return this.CInvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CPaymentterm")
	public Set<COrder> getCOrders() {
		return this.COrders;
	}

	@Id
	@Column(name = "c_paymentterm_id", unique = true, nullable = false, length = 32)
	public String getCPaymenttermId() {
		return this.CPaymenttermId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@Column(name = "documentnote", length = 2000)
	public String getDocumentnote() {
		return this.documentnote;
	}

	@Column(name = "fixmonthday", precision = 10, scale = 0)
	public Long getFixmonthday() {
		return this.fixmonthday;
	}

	@Column(name = "fixmonthday2", precision = 10, scale = 0)
	public Long getFixmonthday2() {
		return this.fixmonthday2;
	}

	@Column(name = "fixmonthday3", precision = 10, scale = 0)
	public Long getFixmonthday3() {
		return this.fixmonthday3;
	}

	@Column(name = "fixmonthoffset", precision = 10, scale = 0)
	public Long getFixmonthoffset() {
		return this.fixmonthoffset;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isdefault", length = 1)
	public Character getIsdefault() {
		return this.isdefault;
	}

	@Column(name = "isduefixed", nullable = false, length = 1)
	public char getIsduefixed() {
		return this.isduefixed;
	}

	@Column(name = "isnextbusinessday", length = 1)
	public Character getIsnextbusinessday() {
		return this.isnextbusinessday;
	}

	@Column(name = "isvalid", nullable = false, length = 1)
	public char getIsvalid() {
		return this.isvalid;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "netday", length = 60)
	public String getNetday() {
		return this.netday;
	}

	@Column(name = "netdays", nullable = false, precision = 10, scale = 0)
	public long getNetdays() {
		return this.netdays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "value", nullable = false, length = 40)
	public String getValue() {
		return this.value;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setCBpartnersForCPaymenttermId(
			Set<CBpartner> CBpartnersForCPaymenttermId) {
		this.CBpartnersForCPaymenttermId = CBpartnersForCPaymenttermId;
	}

	public void setCBpartnersForPoPaymenttermId(
			Set<CBpartner> CBpartnersForPoPaymenttermId) {
		this.CBpartnersForPoPaymenttermId = CBpartnersForPoPaymenttermId;
	}

	public void setCInvoices(Set<CInvoice> CInvoices) {
		this.CInvoices = CInvoices;
	}

	public void setCOrders(Set<COrder> COrders) {
		this.COrders = COrders;
	}

	public void setCPaymenttermId(String CPaymenttermId) {
		this.CPaymenttermId = CPaymenttermId;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDocumentnote(String documentnote) {
		this.documentnote = documentnote;
	}

	public void setFixmonthday(Long fixmonthday) {
		this.fixmonthday = fixmonthday;
	}

	public void setFixmonthday2(Long fixmonthday2) {
		this.fixmonthday2 = fixmonthday2;
	}

	public void setFixmonthday3(Long fixmonthday3) {
		this.fixmonthday3 = fixmonthday3;
	}

	public void setFixmonthoffset(Long fixmonthoffset) {
		this.fixmonthoffset = fixmonthoffset;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsdefault(Character isdefault) {
		this.isdefault = isdefault;
	}

	public void setIsduefixed(char isduefixed) {
		this.isduefixed = isduefixed;
	}

	public void setIsnextbusinessday(Character isnextbusinessday) {
		this.isnextbusinessday = isnextbusinessday;
	}

	public void setIsvalid(char isvalid) {
		this.isvalid = isvalid;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setNetday(String netday) {
		this.netday = netday;
	}

	public void setNetdays(long netdays) {
		this.netdays = netdays;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
