package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CRegion generated by hbm2java
 */
@Entity
@Table(name = "c_region", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"c_country_id", "name" }))
public class CRegion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CRegionId;
	private AdOrg adOrg;
	private CCountry CCountry;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String name;
	private String description;
	private Character isdefault;
	private String value;
	private Set<CLocation> CLocations = new HashSet<CLocation>(0);
	private Set<CTax> CTaxesForCRegionId = new HashSet<CTax>(0);
	private Set<CTax> CTaxesForToRegionId = new HashSet<CTax>(0);

	public CRegion() {
	}

	public CRegion(String CRegionId, AdOrg adOrg, CCountry CCountry,
			String adClientId, char isactive, Date created, String createdby,
			Date updated, String updatedby, String name) {
		this.CRegionId = CRegionId;
		this.adOrg = adOrg;
		this.CCountry = CCountry;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
	}

	public CRegion(String CRegionId, AdOrg adOrg, CCountry CCountry,
			String adClientId, char isactive, Date created, String createdby,
			Date updated, String updatedby, String name, String description,
			Character isdefault, String value, Set<CLocation> CLocations,
			Set<CTax> CTaxesForCRegionId, Set<CTax> CTaxesForToRegionId) {
		this.CRegionId = CRegionId;
		this.adOrg = adOrg;
		this.CCountry = CCountry;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.name = name;
		this.description = description;
		this.isdefault = isdefault;
		this.value = value;
		this.CLocations = CLocations;
		this.CTaxesForCRegionId = CTaxesForCRegionId;
		this.CTaxesForToRegionId = CTaxesForToRegionId;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_country_id", nullable = false)
	public CCountry getCCountry() {
		return this.CCountry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CRegion")
	public Set<CLocation> getCLocations() {
		return this.CLocations;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Id
	@Column(name = "c_region_id", unique = true, nullable = false, length = 32)
	public String getCRegionId() {
		return this.CRegionId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CRegionByCRegionId")
	public Set<CTax> getCTaxesForCRegionId() {
		return this.CTaxesForCRegionId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CRegionByToRegionId")
	public Set<CTax> getCTaxesForToRegionId() {
		return this.CTaxesForToRegionId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isdefault", length = 1)
	public Character getIsdefault() {
		return this.isdefault;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "value", length = 2)
	public String getValue() {
		return this.value;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setCCountry(CCountry CCountry) {
		this.CCountry = CCountry;
	}

	public void setCLocations(Set<CLocation> CLocations) {
		this.CLocations = CLocations;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCRegionId(String CRegionId) {
		this.CRegionId = CRegionId;
	}

	public void setCTaxesForCRegionId(Set<CTax> CTaxesForCRegionId) {
		this.CTaxesForCRegionId = CTaxesForCRegionId;
	}

	public void setCTaxesForToRegionId(Set<CTax> CTaxesForToRegionId) {
		this.CTaxesForToRegionId = CTaxesForToRegionId;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsdefault(Character isdefault) {
		this.isdefault = isdefault;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
