package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CUom generated by hbm2java
 */
@Entity
@Table(name = "c_uom", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ad_client_id", "name" }))
public class CUom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String CUomId;
	private AdOrg adOrg;
	private String adClientId;
	private char isactive;
	private Date created;
	private Date updated;
	private String createdby;
	private String updatedby;
	private String x12de355;
	private String uomsymbol;
	private String name;
	private String description;
	private long stdprecision;
	private long costingprecision;
	private char isdefault;
	private Character breakdown;
	private Set<CInvoiceline> CInvoicelines = new HashSet<CInvoiceline>(0);
	private Set<MProduct> MProducts = new HashSet<MProduct>(0);

	public CUom() {
	}

	public CUom(String CUomId, AdOrg adOrg, String adClientId, char isactive,
			Date created, Date updated, String createdby, String updatedby,
			String x12de355, String name, long stdprecision,
			long costingprecision, char isdefault) {
		this.CUomId = CUomId;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.updated = updated;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.x12de355 = x12de355;
		this.name = name;
		this.stdprecision = stdprecision;
		this.costingprecision = costingprecision;
		this.isdefault = isdefault;
	}

	public CUom(String CUomId, AdOrg adOrg, String adClientId, char isactive,
			Date created, Date updated, String createdby, String updatedby,
			String x12de355, String uomsymbol, String name, String description,
			long stdprecision, long costingprecision, char isdefault,
			Character breakdown, Set<CInvoiceline> CInvoicelines,
			Set<MProduct> MProducts) {
		this.CUomId = CUomId;
		this.adOrg = adOrg;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.updated = updated;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.x12de355 = x12de355;
		this.uomsymbol = uomsymbol;
		this.name = name;
		this.description = description;
		this.stdprecision = stdprecision;
		this.costingprecision = costingprecision;
		this.isdefault = isdefault;
		this.breakdown = breakdown;
		this.CInvoicelines = CInvoicelines;
		this.MProducts = MProducts;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@Column(name = "breakdown", length = 1)
	public Character getBreakdown() {
		return this.breakdown;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CUom")
	public Set<CInvoiceline> getCInvoicelines() {
		return this.CInvoicelines;
	}

	@Column(name = "costingprecision", nullable = false, precision = 10, scale = 0)
	public long getCostingprecision() {
		return this.costingprecision;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Id
	@Column(name = "c_uom_id", unique = true, nullable = false, length = 32)
	public String getCUomId() {
		return this.CUomId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isdefault", nullable = false, length = 1)
	public char getIsdefault() {
		return this.isdefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CUom")
	public Set<MProduct> getMProducts() {
		return this.MProducts;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "stdprecision", nullable = false, precision = 10, scale = 0)
	public long getStdprecision() {
		return this.stdprecision;
	}

	@Column(name = "uomsymbol", length = 3)
	public String getUomsymbol() {
		return this.uomsymbol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "x12de355", nullable = false, length = 2)
	public String getX12de355() {
		return this.x12de355;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setBreakdown(Character breakdown) {
		this.breakdown = breakdown;
	}

	public void setCInvoicelines(Set<CInvoiceline> CInvoicelines) {
		this.CInvoicelines = CInvoicelines;
	}

	public void setCostingprecision(long costingprecision) {
		this.costingprecision = costingprecision;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCUomId(String CUomId) {
		this.CUomId = CUomId;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsdefault(char isdefault) {
		this.isdefault = isdefault;
	}

	public void setMProducts(Set<MProduct> MProducts) {
		this.MProducts = MProducts;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setStdprecision(long stdprecision) {
		this.stdprecision = stdprecision;
	}

	public void setUomsymbol(String uomsymbol) {
		this.uomsymbol = uomsymbol;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setX12de355(String x12de355) {
		this.x12de355 = x12de355;
	}

}
