package mx.redts.ob3.model;

// Generated 03-jun-2014 0:22:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MProduct generated by hbm2java
 */
@Entity
@Table(name = "m_product", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "ad_client_id", "value" }),
		@UniqueConstraint(columnNames = "s_expensetype_id"),
		@UniqueConstraint(columnNames = "s_resource_id") })
public class MProduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String MProductId;
	private AdOrg adOrg;
	private CUom CUom;
	private CBpartner CBpartner;
	private String adClientId;
	private char isactive;
	private Date created;
	private String createdby;
	private Date updated;
	private String updatedby;
	private String value;
	private String name;
	private String description;
	private String documentnote;
	private String help;
	private String upc;
	private String sku;
	private String salesrepId;
	private char issummary;
	private char isstocked;
	private char ispurchased;
	private char issold;
	private char isbom;
	private char isinvoiceprintdetails;
	private char ispicklistprintdetails;
	private char isverified;
	private String MProductCategoryId;
	private Character classification;
	private BigDecimal volume;
	private BigDecimal weight;
	private Long shelfwidth;
	private Long shelfheight;
	private Long shelfdepth;
	private Long unitsperpallet;
	private String CTaxcategoryId;
	private String SResourceId;
	private Character discontinued;
	private Date discontinuedby;
	private char processing;
	private String SExpensetypeId;
	private String producttype;
	private String imageurl;
	private String descriptionurl;
	private Long guaranteedays;
	private String versionno;
	private String MAttributesetId;
	private String MAttributesetinstanceId;
	private String downloadurl;
	private String MFreightcategoryId;
	private String MLocatorId;
	private String adImageId;
	private Character ispriceprinted;
	private String name2;
	private String costtype;
	private BigDecimal coststd;
	private Long stockMin;
	private Character enforceAttribute;
	private char calculated;
	private String maProcessplanId;
	private char production;
	private BigDecimal capacity;
	private BigDecimal delaymin;
	private String mrpPlannerId;
	private String mrpPlanningmethodId;
	private BigDecimal qtymax;
	private BigDecimal qtymin;
	private BigDecimal qtystd;
	private Character qtytype;
	private BigDecimal stockmin;
	private String attrsetvaluetype;
	private char isquantityvariable;
	private char isdeferredrevenue;
	private String revplantype;
	private BigDecimal periodnumber;
	private char isdeferredexpense;
	private String expplantype;
	private BigDecimal periodnumberExp;
	private String defaultperiod;
	private String defaultperiodExp;
	private Set<CInvoiceline> CInvoicelines = new HashSet<CInvoiceline>(0);

	public MProduct() {
	}

	public MProduct(String MProductId, AdOrg adOrg, CUom CUom,
			CBpartner CBpartner, String adClientId, char isactive,
			Date created, String createdby, Date updated, String updatedby,
			String value, String name, String description, String documentnote,
			String help, String upc, String sku, String salesrepId,
			char issummary, char isstocked, char ispurchased, char issold,
			char isbom, char isinvoiceprintdetails,
			char ispicklistprintdetails, char isverified,
			String MProductCategoryId, Character classification,
			BigDecimal volume, BigDecimal weight, Long shelfwidth,
			Long shelfheight, Long shelfdepth, Long unitsperpallet,
			String CTaxcategoryId, String SResourceId, Character discontinued,
			Date discontinuedby, char processing, String SExpensetypeId,
			String producttype, String imageurl, String descriptionurl,
			Long guaranteedays, String versionno, String MAttributesetId,
			String MAttributesetinstanceId, String downloadurl,
			String MFreightcategoryId, String MLocatorId, String adImageId,
			Character ispriceprinted, String name2, String costtype,
			BigDecimal coststd, Long stockMin, Character enforceAttribute,
			char calculated, String maProcessplanId, char production,
			BigDecimal capacity, BigDecimal delaymin, String mrpPlannerId,
			String mrpPlanningmethodId, BigDecimal qtymax, BigDecimal qtymin,
			BigDecimal qtystd, Character qtytype, BigDecimal stockmin,
			String attrsetvaluetype, char isquantityvariable,
			char isdeferredrevenue, String revplantype,
			BigDecimal periodnumber, char isdeferredexpense,
			String expplantype, BigDecimal periodnumberExp,
			String defaultperiod, String defaultperiodExp,
			Set<CInvoiceline> CInvoicelines) {
		this.MProductId = MProductId;
		this.adOrg = adOrg;
		this.CUom = CUom;
		this.CBpartner = CBpartner;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.value = value;
		this.name = name;
		this.description = description;
		this.documentnote = documentnote;
		this.help = help;
		this.upc = upc;
		this.sku = sku;
		this.salesrepId = salesrepId;
		this.issummary = issummary;
		this.isstocked = isstocked;
		this.ispurchased = ispurchased;
		this.issold = issold;
		this.isbom = isbom;
		this.isinvoiceprintdetails = isinvoiceprintdetails;
		this.ispicklistprintdetails = ispicklistprintdetails;
		this.isverified = isverified;
		this.MProductCategoryId = MProductCategoryId;
		this.classification = classification;
		this.volume = volume;
		this.weight = weight;
		this.shelfwidth = shelfwidth;
		this.shelfheight = shelfheight;
		this.shelfdepth = shelfdepth;
		this.unitsperpallet = unitsperpallet;
		this.CTaxcategoryId = CTaxcategoryId;
		this.SResourceId = SResourceId;
		this.discontinued = discontinued;
		this.discontinuedby = discontinuedby;
		this.processing = processing;
		this.SExpensetypeId = SExpensetypeId;
		this.producttype = producttype;
		this.imageurl = imageurl;
		this.descriptionurl = descriptionurl;
		this.guaranteedays = guaranteedays;
		this.versionno = versionno;
		this.MAttributesetId = MAttributesetId;
		this.MAttributesetinstanceId = MAttributesetinstanceId;
		this.downloadurl = downloadurl;
		this.MFreightcategoryId = MFreightcategoryId;
		this.MLocatorId = MLocatorId;
		this.adImageId = adImageId;
		this.ispriceprinted = ispriceprinted;
		this.name2 = name2;
		this.costtype = costtype;
		this.coststd = coststd;
		this.stockMin = stockMin;
		this.enforceAttribute = enforceAttribute;
		this.calculated = calculated;
		this.maProcessplanId = maProcessplanId;
		this.production = production;
		this.capacity = capacity;
		this.delaymin = delaymin;
		this.mrpPlannerId = mrpPlannerId;
		this.mrpPlanningmethodId = mrpPlanningmethodId;
		this.qtymax = qtymax;
		this.qtymin = qtymin;
		this.qtystd = qtystd;
		this.qtytype = qtytype;
		this.stockmin = stockmin;
		this.attrsetvaluetype = attrsetvaluetype;
		this.isquantityvariable = isquantityvariable;
		this.isdeferredrevenue = isdeferredrevenue;
		this.revplantype = revplantype;
		this.periodnumber = periodnumber;
		this.isdeferredexpense = isdeferredexpense;
		this.expplantype = expplantype;
		this.periodnumberExp = periodnumberExp;
		this.defaultperiod = defaultperiod;
		this.defaultperiodExp = defaultperiodExp;
		this.CInvoicelines = CInvoicelines;
	}

	public MProduct(String MProductId, AdOrg adOrg, CUom CUom,
			String adClientId, char isactive, Date created, String createdby,
			Date updated, String updatedby, String value, String name,
			char issummary, char isstocked, char ispurchased, char issold,
			char isbom, char isinvoiceprintdetails,
			char ispicklistprintdetails, char isverified,
			String MProductCategoryId, String CTaxcategoryId, char processing,
			String producttype, char calculated, char production,
			char isquantityvariable, char isdeferredrevenue,
			char isdeferredexpense) {
		this.MProductId = MProductId;
		this.adOrg = adOrg;
		this.CUom = CUom;
		this.adClientId = adClientId;
		this.isactive = isactive;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.value = value;
		this.name = name;
		this.issummary = issummary;
		this.isstocked = isstocked;
		this.ispurchased = ispurchased;
		this.issold = issold;
		this.isbom = isbom;
		this.isinvoiceprintdetails = isinvoiceprintdetails;
		this.ispicklistprintdetails = ispicklistprintdetails;
		this.isverified = isverified;
		this.MProductCategoryId = MProductCategoryId;
		this.CTaxcategoryId = CTaxcategoryId;
		this.processing = processing;
		this.producttype = producttype;
		this.calculated = calculated;
		this.production = production;
		this.isquantityvariable = isquantityvariable;
		this.isdeferredrevenue = isdeferredrevenue;
		this.isdeferredexpense = isdeferredexpense;
	}

	@Column(name = "ad_client_id", nullable = false, length = 32)
	public String getAdClientId() {
		return this.adClientId;
	}

	@Column(name = "ad_image_id", length = 32)
	public String getAdImageId() {
		return this.adImageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_org_id", nullable = false)
	public AdOrg getAdOrg() {
		return this.adOrg;
	}

	@Column(name = "attrsetvaluetype", length = 60)
	public String getAttrsetvaluetype() {
		return this.attrsetvaluetype;
	}

	@Column(name = "calculated", nullable = false, length = 1)
	public char getCalculated() {
		return this.calculated;
	}

	@Column(name = "capacity", precision = 131089, scale = 0)
	public BigDecimal getCapacity() {
		return this.capacity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_bpartner_id")
	public CBpartner getCBpartner() {
		return this.CBpartner;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MProduct")
	public Set<CInvoiceline> getCInvoicelines() {
		return this.CInvoicelines;
	}

	@Column(name = "classification", length = 1)
	public Character getClassification() {
		return this.classification;
	}

	@Column(name = "coststd", precision = 131089, scale = 0)
	public BigDecimal getCoststd() {
		return this.coststd;
	}

	@Column(name = "costtype", length = 60)
	public String getCosttype() {
		return this.costtype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	@Column(name = "createdby", nullable = false, length = 32)
	public String getCreatedby() {
		return this.createdby;
	}

	@Column(name = "c_taxcategory_id", nullable = false, length = 32)
	public String getCTaxcategoryId() {
		return this.CTaxcategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_uom_id", nullable = false)
	public CUom getCUom() {
		return this.CUom;
	}

	@Column(name = "defaultperiod", length = 60)
	public String getDefaultperiod() {
		return this.defaultperiod;
	}

	@Column(name = "defaultperiod_exp", length = 60)
	public String getDefaultperiodExp() {
		return this.defaultperiodExp;
	}

	@Column(name = "delaymin", precision = 131089, scale = 0)
	public BigDecimal getDelaymin() {
		return this.delaymin;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	@Column(name = "descriptionurl", length = 120)
	public String getDescriptionurl() {
		return this.descriptionurl;
	}

	@Column(name = "discontinued", length = 1)
	public Character getDiscontinued() {
		return this.discontinued;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "discontinuedby", length = 29)
	public Date getDiscontinuedby() {
		return this.discontinuedby;
	}

	@Column(name = "documentnote", length = 2000)
	public String getDocumentnote() {
		return this.documentnote;
	}

	@Column(name = "downloadurl", length = 120)
	public String getDownloadurl() {
		return this.downloadurl;
	}

	@Column(name = "enforce_attribute", length = 1)
	public Character getEnforceAttribute() {
		return this.enforceAttribute;
	}

	@Column(name = "expplantype", length = 60)
	public String getExpplantype() {
		return this.expplantype;
	}

	@Column(name = "guaranteedays", precision = 10, scale = 0)
	public Long getGuaranteedays() {
		return this.guaranteedays;
	}

	@Column(name = "help", length = 2000)
	public String getHelp() {
		return this.help;
	}

	@Column(name = "imageurl", length = 120)
	public String getImageurl() {
		return this.imageurl;
	}

	@Column(name = "isactive", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	@Column(name = "isbom", nullable = false, length = 1)
	public char getIsbom() {
		return this.isbom;
	}

	@Column(name = "isdeferredexpense", nullable = false, length = 1)
	public char getIsdeferredexpense() {
		return this.isdeferredexpense;
	}

	@Column(name = "isdeferredrevenue", nullable = false, length = 1)
	public char getIsdeferredrevenue() {
		return this.isdeferredrevenue;
	}

	@Column(name = "isinvoiceprintdetails", nullable = false, length = 1)
	public char getIsinvoiceprintdetails() {
		return this.isinvoiceprintdetails;
	}

	@Column(name = "ispicklistprintdetails", nullable = false, length = 1)
	public char getIspicklistprintdetails() {
		return this.ispicklistprintdetails;
	}

	@Column(name = "ispriceprinted", length = 1)
	public Character getIspriceprinted() {
		return this.ispriceprinted;
	}

	@Column(name = "ispurchased", nullable = false, length = 1)
	public char getIspurchased() {
		return this.ispurchased;
	}

	@Column(name = "isquantityvariable", nullable = false, length = 1)
	public char getIsquantityvariable() {
		return this.isquantityvariable;
	}

	@Column(name = "issold", nullable = false, length = 1)
	public char getIssold() {
		return this.issold;
	}

	@Column(name = "isstocked", nullable = false, length = 1)
	public char getIsstocked() {
		return this.isstocked;
	}

	@Column(name = "issummary", nullable = false, length = 1)
	public char getIssummary() {
		return this.issummary;
	}

	@Column(name = "isverified", nullable = false, length = 1)
	public char getIsverified() {
		return this.isverified;
	}

	@Column(name = "ma_processplan_id", length = 32)
	public String getMaProcessplanId() {
		return this.maProcessplanId;
	}

	@Column(name = "m_attributeset_id", length = 32)
	public String getMAttributesetId() {
		return this.MAttributesetId;
	}

	@Column(name = "m_attributesetinstance_id", length = 32)
	public String getMAttributesetinstanceId() {
		return this.MAttributesetinstanceId;
	}

	@Column(name = "m_freightcategory_id", length = 32)
	public String getMFreightcategoryId() {
		return this.MFreightcategoryId;
	}

	@Column(name = "m_locator_id", length = 32)
	public String getMLocatorId() {
		return this.MLocatorId;
	}

	@Column(name = "m_product_category_id", nullable = false, length = 32)
	public String getMProductCategoryId() {
		return this.MProductCategoryId;
	}

	@Id
	@Column(name = "m_product_id", unique = true, nullable = false, length = 32)
	public String getMProductId() {
		return this.MProductId;
	}

	@Column(name = "mrp_planner_id", length = 32)
	public String getMrpPlannerId() {
		return this.mrpPlannerId;
	}

	@Column(name = "mrp_planningmethod_id", length = 32)
	public String getMrpPlanningmethodId() {
		return this.mrpPlanningmethodId;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	@Column(name = "name2", length = 60)
	public String getName2() {
		return this.name2;
	}

	@Column(name = "periodnumber", precision = 131089, scale = 0)
	public BigDecimal getPeriodnumber() {
		return this.periodnumber;
	}

	@Column(name = "periodnumber_exp", precision = 131089, scale = 0)
	public BigDecimal getPeriodnumberExp() {
		return this.periodnumberExp;
	}

	@Column(name = "processing", nullable = false, length = 1)
	public char getProcessing() {
		return this.processing;
	}

	@Column(name = "production", nullable = false, length = 1)
	public char getProduction() {
		return this.production;
	}

	@Column(name = "producttype", nullable = false, length = 60)
	public String getProducttype() {
		return this.producttype;
	}

	@Column(name = "qtymax", precision = 131089, scale = 0)
	public BigDecimal getQtymax() {
		return this.qtymax;
	}

	@Column(name = "qtymin", precision = 131089, scale = 0)
	public BigDecimal getQtymin() {
		return this.qtymin;
	}

	@Column(name = "qtystd", precision = 131089, scale = 0)
	public BigDecimal getQtystd() {
		return this.qtystd;
	}

	@Column(name = "qtytype", length = 1)
	public Character getQtytype() {
		return this.qtytype;
	}

	@Column(name = "revplantype", length = 60)
	public String getRevplantype() {
		return this.revplantype;
	}

	@Column(name = "salesrep_id", length = 32)
	public String getSalesrepId() {
		return this.salesrepId;
	}

	@Column(name = "s_expensetype_id", unique = true, length = 32)
	public String getSExpensetypeId() {
		return this.SExpensetypeId;
	}

	@Column(name = "shelfdepth", precision = 10, scale = 0)
	public Long getShelfdepth() {
		return this.shelfdepth;
	}

	@Column(name = "shelfheight", precision = 10, scale = 0)
	public Long getShelfheight() {
		return this.shelfheight;
	}

	@Column(name = "shelfwidth", precision = 10, scale = 0)
	public Long getShelfwidth() {
		return this.shelfwidth;
	}

	@Column(name = "sku", length = 30)
	public String getSku() {
		return this.sku;
	}

	@Column(name = "s_resource_id", unique = true, length = 32)
	public String getSResourceId() {
		return this.SResourceId;
	}

	@Column(name = "stockmin", precision = 131089, scale = 0)
	public BigDecimal getStockmin() {
		return this.stockmin;
	}

	@Column(name = "stock_min", precision = 10, scale = 0)
	public Long getStockMin() {
		return this.stockMin;
	}

	@Column(name = "unitsperpallet", precision = 10, scale = 0)
	public Long getUnitsperpallet() {
		return this.unitsperpallet;
	}

	@Column(name = "upc", length = 30)
	public String getUpc() {
		return this.upc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	@Column(name = "updatedby", nullable = false, length = 32)
	public String getUpdatedby() {
		return this.updatedby;
	}

	@Column(name = "value", nullable = false, length = 40)
	public String getValue() {
		return this.value;
	}

	@Column(name = "versionno", length = 20)
	public String getVersionno() {
		return this.versionno;
	}

	@Column(name = "volume", precision = 131089, scale = 0)
	public BigDecimal getVolume() {
		return this.volume;
	}

	@Column(name = "weight", precision = 131089, scale = 0)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setAdClientId(String adClientId) {
		this.adClientId = adClientId;
	}

	public void setAdImageId(String adImageId) {
		this.adImageId = adImageId;
	}

	public void setAdOrg(AdOrg adOrg) {
		this.adOrg = adOrg;
	}

	public void setAttrsetvaluetype(String attrsetvaluetype) {
		this.attrsetvaluetype = attrsetvaluetype;
	}

	public void setCalculated(char calculated) {
		this.calculated = calculated;
	}

	public void setCapacity(BigDecimal capacity) {
		this.capacity = capacity;
	}

	public void setCBpartner(CBpartner CBpartner) {
		this.CBpartner = CBpartner;
	}

	public void setCInvoicelines(Set<CInvoiceline> CInvoicelines) {
		this.CInvoicelines = CInvoicelines;
	}

	public void setClassification(Character classification) {
		this.classification = classification;
	}

	public void setCoststd(BigDecimal coststd) {
		this.coststd = coststd;
	}

	public void setCosttype(String costtype) {
		this.costtype = costtype;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public void setCTaxcategoryId(String CTaxcategoryId) {
		this.CTaxcategoryId = CTaxcategoryId;
	}

	public void setCUom(CUom CUom) {
		this.CUom = CUom;
	}

	public void setDefaultperiod(String defaultperiod) {
		this.defaultperiod = defaultperiod;
	}

	public void setDefaultperiodExp(String defaultperiodExp) {
		this.defaultperiodExp = defaultperiodExp;
	}

	public void setDelaymin(BigDecimal delaymin) {
		this.delaymin = delaymin;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDescriptionurl(String descriptionurl) {
		this.descriptionurl = descriptionurl;
	}

	public void setDiscontinued(Character discontinued) {
		this.discontinued = discontinued;
	}

	public void setDiscontinuedby(Date discontinuedby) {
		this.discontinuedby = discontinuedby;
	}

	public void setDocumentnote(String documentnote) {
		this.documentnote = documentnote;
	}

	public void setDownloadurl(String downloadurl) {
		this.downloadurl = downloadurl;
	}

	public void setEnforceAttribute(Character enforceAttribute) {
		this.enforceAttribute = enforceAttribute;
	}

	public void setExpplantype(String expplantype) {
		this.expplantype = expplantype;
	}

	public void setGuaranteedays(Long guaranteedays) {
		this.guaranteedays = guaranteedays;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	public void setIsbom(char isbom) {
		this.isbom = isbom;
	}

	public void setIsdeferredexpense(char isdeferredexpense) {
		this.isdeferredexpense = isdeferredexpense;
	}

	public void setIsdeferredrevenue(char isdeferredrevenue) {
		this.isdeferredrevenue = isdeferredrevenue;
	}

	public void setIsinvoiceprintdetails(char isinvoiceprintdetails) {
		this.isinvoiceprintdetails = isinvoiceprintdetails;
	}

	public void setIspicklistprintdetails(char ispicklistprintdetails) {
		this.ispicklistprintdetails = ispicklistprintdetails;
	}

	public void setIspriceprinted(Character ispriceprinted) {
		this.ispriceprinted = ispriceprinted;
	}

	public void setIspurchased(char ispurchased) {
		this.ispurchased = ispurchased;
	}

	public void setIsquantityvariable(char isquantityvariable) {
		this.isquantityvariable = isquantityvariable;
	}

	public void setIssold(char issold) {
		this.issold = issold;
	}

	public void setIsstocked(char isstocked) {
		this.isstocked = isstocked;
	}

	public void setIssummary(char issummary) {
		this.issummary = issummary;
	}

	public void setIsverified(char isverified) {
		this.isverified = isverified;
	}

	public void setMaProcessplanId(String maProcessplanId) {
		this.maProcessplanId = maProcessplanId;
	}

	public void setMAttributesetId(String MAttributesetId) {
		this.MAttributesetId = MAttributesetId;
	}

	public void setMAttributesetinstanceId(String MAttributesetinstanceId) {
		this.MAttributesetinstanceId = MAttributesetinstanceId;
	}

	public void setMFreightcategoryId(String MFreightcategoryId) {
		this.MFreightcategoryId = MFreightcategoryId;
	}

	public void setMLocatorId(String MLocatorId) {
		this.MLocatorId = MLocatorId;
	}

	public void setMProductCategoryId(String MProductCategoryId) {
		this.MProductCategoryId = MProductCategoryId;
	}

	public void setMProductId(String MProductId) {
		this.MProductId = MProductId;
	}

	public void setMrpPlannerId(String mrpPlannerId) {
		this.mrpPlannerId = mrpPlannerId;
	}

	public void setMrpPlanningmethodId(String mrpPlanningmethodId) {
		this.mrpPlanningmethodId = mrpPlanningmethodId;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	public void setPeriodnumber(BigDecimal periodnumber) {
		this.periodnumber = periodnumber;
	}

	public void setPeriodnumberExp(BigDecimal periodnumberExp) {
		this.periodnumberExp = periodnumberExp;
	}

	public void setProcessing(char processing) {
		this.processing = processing;
	}

	public void setProduction(char production) {
		this.production = production;
	}

	public void setProducttype(String producttype) {
		this.producttype = producttype;
	}

	public void setQtymax(BigDecimal qtymax) {
		this.qtymax = qtymax;
	}

	public void setQtymin(BigDecimal qtymin) {
		this.qtymin = qtymin;
	}

	public void setQtystd(BigDecimal qtystd) {
		this.qtystd = qtystd;
	}

	public void setQtytype(Character qtytype) {
		this.qtytype = qtytype;
	}

	public void setRevplantype(String revplantype) {
		this.revplantype = revplantype;
	}

	public void setSalesrepId(String salesrepId) {
		this.salesrepId = salesrepId;
	}

	public void setSExpensetypeId(String SExpensetypeId) {
		this.SExpensetypeId = SExpensetypeId;
	}

	public void setShelfdepth(Long shelfdepth) {
		this.shelfdepth = shelfdepth;
	}

	public void setShelfheight(Long shelfheight) {
		this.shelfheight = shelfheight;
	}

	public void setShelfwidth(Long shelfwidth) {
		this.shelfwidth = shelfwidth;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public void setSResourceId(String SResourceId) {
		this.SResourceId = SResourceId;
	}

	public void setStockmin(BigDecimal stockmin) {
		this.stockmin = stockmin;
	}

	public void setStockMin(Long stockMin) {
		this.stockMin = stockMin;
	}

	public void setUnitsperpallet(Long unitsperpallet) {
		this.unitsperpallet = unitsperpallet;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public void setVersionno(String versionno) {
		this.versionno = versionno;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

}
