package mx.redts.simoc.model.entities;

// Generated 26/10/2013 04:35:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchivoProcesado generated by hbm2java
 */
@Entity
@Table(name = "archivo_procesado", schema = "public")
public class ArchivoProcesado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4290722481119570167L;
	private int idOrdenCompra;
	private String estatusOrdenCompra;
	private String nombreOrdenCompra;
	private String nombreArchivo;
	private Date fechaRecepcion;
	private String cliente;
	private String organizacion;

	public ArchivoProcesado() {
	}

	public ArchivoProcesado(int idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	public ArchivoProcesado(int idOrdenCompra, String estatusOrdenCompra,
			String nombreOrdenCompra, String nombreArchivo,
			Date fechaRecepcion, String cliente, String organizacion) {
		this.idOrdenCompra = idOrdenCompra;
		this.estatusOrdenCompra = estatusOrdenCompra;
		this.nombreOrdenCompra = nombreOrdenCompra;
		this.nombreArchivo = nombreArchivo;
		this.fechaRecepcion = fechaRecepcion;
		this.cliente = cliente;
		this.organizacion = organizacion;
	}

	@Column(name = "cliente", length = 200)
	public String getCliente() {
		return this.cliente;
	}

	@Column(name = "estatus_orden_compra", length = 50)
	public String getEstatusOrdenCompra() {
		return this.estatusOrdenCompra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion", length = 13)
	public Date getFechaRecepcion() {
		return this.fechaRecepcion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ArchivoProcSequence")
	@SequenceGenerator(name = "ArchivoProcSequence", sequenceName = "archivo_proc_seq", allocationSize = 1)
	@Column(name = "id_orden_compra", unique = true, nullable = false)
	public int getIdOrdenCompra() {
		return this.idOrdenCompra;
	}

	@Column(name = "nombre_archivo", length = 50)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	@Column(name = "nombre_orden_compra", length = 50)
	public String getNombreOrdenCompra() {
		return this.nombreOrdenCompra;
	}

	@Column(name = "organizacion", length = 200)
	public String getOrganizacion() {
		return this.organizacion;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public void setEstatusOrdenCompra(String estatusOrdenCompra) {
		this.estatusOrdenCompra = estatusOrdenCompra;
	}

	public void setFechaRecepcion(Date fechaRecepcion) {
		this.fechaRecepcion = fechaRecepcion;
	}

	public void setIdOrdenCompra(int idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	public void setNombreOrdenCompra(String nombreOrdenCompra) {
		this.nombreOrdenCompra = nombreOrdenCompra;
	}

	public void setOrganizacion(String organizacion) {
		this.organizacion = organizacion;
	}

	public String toString() {
		return estatusOrdenCompra;

	}

}
