package mx.redts.simoc.model.entities;

// Generated 27/10/2013 03:26:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * COrganizacion generated by hbm2java
 */
@Entity
@Table(name = "c_organizacion", schema = "public")
public class COrganizacion implements java.io.Serializable {

	/**
	 * serialVersionUID long COrganizacion.java
	 */
	private static final long serialVersionUID = 8255424456393823688L;
	private int idOrg;
	private String idOb3;
	private String nameOrg;

	public COrganizacion() {
	}

	public COrganizacion(int idOrg) {
		this.idOrg = idOrg;
	}

	public COrganizacion(int idOrg, String idOb3, String nameOrg) {
		this.idOrg = idOrg;
		this.idOb3 = idOb3;
		this.nameOrg = nameOrg;
	}

	@Column(name = "id_ob3", length = 32)
	public String getIdOb3() {
		return this.idOb3;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "OrganizacionSeq")
	@SequenceGenerator(name = "OrganizacionSeq", sequenceName = "organizacion_seq", allocationSize = 1)
	@Column(name = "id_org", unique = true, nullable = false)
	public int getIdOrg() {
		return this.idOrg;
	}

	@Column(name = "name_org", length = 50)
	public String getNameOrg() {
		return this.nameOrg;
	}

	public void setIdOb3(String idOb3) {
		this.idOb3 = idOb3;
	}

	public void setIdOrg(int idOrg) {
		this.idOrg = idOrg;
	}

	public void setNameOrg(String nameOrg) {
		this.nameOrg = nameOrg;
	}

	public String toString() {
		return this.nameOrg;
	}

}
