package mx.redts.simoc.model.entities;

// Generated 26/10/2013 01:41:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ImportarOrdenes generated by hbm2java
 */
@Entity
@Table(name = "importar_ordenes", schema = "public")
public class ImportarOrdenes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idImportar;
	private String importProcessComplete;
	private String numDocumento;
	private String operacionDeVenta;
	private String descripcion;
	private String tarifa;
	private String paymentTermKey;
	private String almacen;
	private Date fechaPedido;
	private Date fechaComprometida;
	private String businessPartnerSearchKey;
	private String direccion;
	private String upcEan;
	private String cantidadPedido;
	private String precioUnitario;
	private String impuesto;
	private String impuestos;
	private String procesado;
	private String estatus;

	public ImportarOrdenes() {
	}

	public ImportarOrdenes(int idImportar) {
		this.idImportar = idImportar;
	}

	public ImportarOrdenes(int idImportar, String importProcessComplete,
			String numDocumento, String operacionDeVenta, String descripcion,
			String tarifa, String paymentTermKey, String almacen,
			Date fechaPedido, Date fechaComprometida,
			String businessPartnerSearchKey, String direccion, String upcEan,
			String cantidadPedido, String precioUnitario, String impuesto,
			String impuestos, String procesado, String estatus) {
		this.idImportar = idImportar;
		this.importProcessComplete = importProcessComplete;
		this.numDocumento = numDocumento;
		this.operacionDeVenta = operacionDeVenta;
		this.descripcion = descripcion;
		this.tarifa = tarifa;
		this.paymentTermKey = paymentTermKey;
		this.almacen = almacen;
		this.fechaPedido = fechaPedido;
		this.fechaComprometida = fechaComprometida;
		this.businessPartnerSearchKey = businessPartnerSearchKey;
		this.direccion = direccion;
		this.upcEan = upcEan;
		this.cantidadPedido = cantidadPedido;
		this.precioUnitario = precioUnitario;
		this.impuesto = impuesto;
		this.impuestos = impuestos;
		this.procesado = procesado;
		this.estatus = estatus;
	}

	@Column(name = "almacen", length = 25)
	public String getAlmacen() {
		return this.almacen;
	}

	@Column(name = "business_partner_search_key", length = 25)
	public String getBusinessPartnerSearchKey() {
		return this.businessPartnerSearchKey;
	}

	@Column(name = "cantidad_pedido", length = 25)
	public String getCantidadPedido() {
		return this.cantidadPedido;
	}

	@Column(name = "descripcion", length = 25)
	public String getDescripcion() {
		return this.descripcion;
	}

	@Column(name = "direccion", length = 25)
	public String getDireccion() {
		return this.direccion;
	}

	@Column(name = "estatus", length = 25)
	public String getEstatus() {
		return this.estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_comprometida", length = 13)
	public Date getFechaComprometida() {
		return this.fechaComprometida;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_pedido", length = 13)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	@Id
	@Column(name = "id_importar", unique = true, nullable = false)
	public int getIdImportar() {
		return this.idImportar;
	}

	@Column(name = "import_process_complete", length = 10)
	public String getImportProcessComplete() {
		return this.importProcessComplete;
	}

	@Column(name = "impuesto", length = 25)
	public String getImpuesto() {
		return this.impuesto;
	}

	@Column(name = "impuestos", length = 25)
	public String getImpuestos() {
		return this.impuestos;
	}

	@Column(name = "num_documento", length = 25)
	public String getNumDocumento() {
		return this.numDocumento;
	}

	@Column(name = "operacion_de_venta", length = 10)
	public String getOperacionDeVenta() {
		return this.operacionDeVenta;
	}

	@Column(name = "payment_term_key", length = 25)
	public String getPaymentTermKey() {
		return this.paymentTermKey;
	}

	@Column(name = "precio_unitario", length = 25)
	public String getPrecioUnitario() {
		return this.precioUnitario;
	}

	@Column(name = "procesado", length = 25)
	public String getProcesado() {
		return this.procesado;
	}

	@Column(name = "tarifa", length = 25)
	public String getTarifa() {
		return this.tarifa;
	}

	@Column(name = "upc_ean", length = 25)
	public String getUpcEan() {
		return this.upcEan;
	}

	public void setAlmacen(String almacen) {
		this.almacen = almacen;
	}

	public void setBusinessPartnerSearchKey(String businessPartnerSearchKey) {
		this.businessPartnerSearchKey = businessPartnerSearchKey;
	}

	public void setCantidadPedido(String cantidadPedido) {
		this.cantidadPedido = cantidadPedido;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}

	public void setFechaComprometida(Date fechaComprometida) {
		this.fechaComprometida = fechaComprometida;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public void setIdImportar(int idImportar) {
		this.idImportar = idImportar;
	}

	public void setImportProcessComplete(String importProcessComplete) {
		this.importProcessComplete = importProcessComplete;
	}

	public void setImpuesto(String impuesto) {
		this.impuesto = impuesto;
	}

	public void setImpuestos(String impuestos) {
		this.impuestos = impuestos;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	public void setOperacionDeVenta(String operacionDeVenta) {
		this.operacionDeVenta = operacionDeVenta;
	}

	public void setPaymentTermKey(String paymentTermKey) {
		this.paymentTermKey = paymentTermKey;
	}

	public void setPrecioUnitario(String precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public void setProcesado(String procesado) {
		this.procesado = procesado;
	}

	public void setTarifa(String tarifa) {
		this.tarifa = tarifa;
	}

	public void setUpcEan(String upcEan) {
		this.upcEan = upcEan;
	}

}
