package mx.redts.simoc.model.entities;

// Generated 26/10/2013 05:09:17 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcfileOriginal generated by hbm2java
 */
@Entity
@Table(name = "ocfile_original", schema = "public")
public class OcfileOriginal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4789702858775970445L;
	private int idOrdeCompra;
	private String ocxml;

	public OcfileOriginal() {
	}

	public OcfileOriginal(int idOrdeCompra) {
		this.idOrdeCompra = idOrdeCompra;
	}

	public OcfileOriginal(int idOrdeCompra, String ocxml) {
		this.idOrdeCompra = idOrdeCompra;
		this.ocxml = ocxml;
	}

	@Id
	@Column(name = "id_orde_compra", unique = true, nullable = false)
	public int getIdOrdeCompra() {
		return this.idOrdeCompra;
	}

	@Column(name = "ocxml")
	public String getOcxml() {
		return this.ocxml;
	}

	public void setIdOrdeCompra(int idOrdeCompra) {
		this.idOrdeCompra = idOrdeCompra;
	}

	public void setOcxml(String ocxml) {
		this.ocxml = ocxml;
	}

}
