package mx.redts.simoc.model.entities;

// Generated 27/10/2013 05:02:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parametros generated by hbm2java
 */
@Entity
@Table(name = "parametros", schema = "public")
public class Parametros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7056457490755130056L;
	private String paramName;
	private String paramValue;
	private String paramDesc;

	public Parametros() {
	}

	public Parametros(String paramName) {
		this.paramName = paramName;
	}

	public Parametros(String paramName, String paramValue, String paramDesc) {
		this.paramName = paramName;
		this.paramValue = paramValue;
		this.paramDesc = paramDesc;
	}

	@Column(name = "param_desc", length = 100)
	public String getParamDesc() {
		return this.paramDesc;
	}

	@Id
	@Column(name = "param_name", unique = true, nullable = false, length = 30)
	public String getParamName() {
		return this.paramName;
	}

	@Column(name = "param_value", length = 250)
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamDesc(String paramDesc) {
		this.paramDesc = paramDesc;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

}
